### ISSUE TITLE
Why was the last one outdated?

### ISSUE THREAD

**Issue by quantumproducer** [MyEtherWallet/MyEtherWallet#1]
Hi, why was the last one outdated and a new repo necessary?

**Comment by WyseNynja** [comment]
It seems like this new one isn't the one even being used. When will it be? https://github.com/kvhnuke/etherwallet looks to be the actual site

**Comment by kvhnuke** [comment]
We decided the last version is no longer suitable for our Target audience, we are revamping the complete look and feel. In upcoming months, we will be making an announcement about a beta site with this version.

**Comment by gamalielhere** [comment]
Closing this now. Don't hesitate to open again if needed.
