### ISSUE TITLE
Uncaught error not a V3 wallet (old keystore)

### ISSUE THREAD

**Issue by KatyaMik** [MyEtherWallet/MyEtherWallet#1000]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

*Also, this error message should be fixed for more user-readable

https://www.reddit.com/r/MyEtherWallet/comments/bhhyh3/cant_open_my_ethereum_json_keystroke_file_on/

Now, up until 1 year ago I managed to open it in Myetherwallet easily and use it, now it says this: "uncaught error: not a v3 wallet"...
I tried to follow this advice: https://kb.myetherwallet.com/posts/migration/importing-v2-json-file/ which is: - Download zipped geth - Unzip it - copy the json file into same folder - and through command line paste: geth account import NameOfMyWalletFile and this is where I got stuck... it says an error: Fatal: Failed to load the private key: encoding/hex: invalid byte: U+007B '{'

**Comment by gamalielhere** [comment]
Fixed in #976.
