### ISSUE TITLE
A new scenario for "Register Domain"

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#1018]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**
  - Briefly explain the feature you would like us to implement
A new scenario for "Register Domain".

![image](https://user-images.githubusercontent.com/31494364/57113464-8a08cd80-6cf9-11e9-8ad4-6864b86e7665.png)

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/tree/ui/update-register-domain
