### ISSUE TITLE
Warn of darklisted domains

### ISSUE THREAD

**Issue by 409H** [MyEtherWallet/MyEtherWallet#104]
Using [ethereum-lists](https://github.com/MyEtherWallet/ethereum-lists), would it be part of MEWs vision to show an alert if you're sending funds to a darklisted address?

Perhaps inform the user with a red error box above the button to finalise sending funds.

**Comment by tayvano** [comment]
Yes. It'll ideally be in a message box, like on the current site, that we use to confirm if an address is 👍 or 👎. Typically these have been used to remind people to use proper gas limit / gas price, but their usecase has expanded.

**Comment by 409H** [comment]
Great, I'll start on this during the week and hopefully finish it up this weekend if time permits

**Comment by dternyak** [comment]
@409H I believe this has been completed, and for the future we should be able to use /meta. Let me know if you would like this issue to be re-opened 😁
