### ISSUE TITLE
Header image links to https://www.myetherwallet.com instead of /

### ISSUE THREAD

**Issue by noman-land** [MyEtherWallet/MyEtherWallet#112]
This is a subtle one but I think it's worth addressing. When downloading the zip file of the project and opening the index.html file locally with a URL like:

`file:///Users/JohnDoe/etherwallet-v3.10.0.2/index.html`

The header image is for some reason hard coded to:

`https://www.myetherwallet.com/`

I wanted to submit a PR to fix this but I'm actually not sure why it's happening, because the `Link` is pointing to `'/'` in its `to` prop.

https://github.com/MyEtherWallet/MyEtherWallet/blob/7fd7ba66c9b13879c6acf7c4074452eb09b291e6/common/components/Header/index.jsx#L34-L35

Perhaps it happens during build somehow?

The result is that I'm running an app locally in "offline" mode but can accidentally switch into "online" mode without realizing it just by clicking on the header image with the intention of simply going back to the home screen.

**Comment by tayvano** [comment]
Live site is http://github.com/kvhnuke/etherwallet

I think this was leftover. At one point I was hoping the phishing sites would use hardcoded logo and I could break it. They never did. ☹

I'll fix now. Thanks.

**Comment by noman-land** [comment]
Oh wow. First of all, nice idea. Second of all :(.
