### ISSUE TITLE
 test-nets ENS support 

### ISSUE THREAD

**Issue by tamnich** [MyEtherWallet/MyEtherWallet#1120]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - i want to use ENS on MEW for ropsten net
  - right now when using ENS name it returns "ENS name is invalid or not found" 
 i have used ".test" TLD 

are you planing to have this feature?

**Comment by kvhnuke** [comment]
ropsten support `.eth` names now, which is identical to the permanent registrar in mainnet. try registering your name with `.eth` at the end
