### ISSUE TITLE
Network error on https://api.myetherwallet.com/eth

### ISSUE THREAD

**Issue by Priyankaagrawal** [MyEtherWallet/MyEtherWallet#1130]
Mybuild was successfull and dist folder is created but when I m running it offline it is showing me **network error** on calling the api- https://api.myetherwallet.com/eth

I have also checked the console.. In console, it is showing cross-origin issue.. 
![image](https://user-images.githubusercontent.com/8734801/58624221-5bc4e080-82ed-11e9-8d70-6ab1fa9f7cac.png)

I also tried by using https://cors-anywhere.herokuapp.com but in that case response get is "Invalid Origin"

**Comment by gamalielhere** [comment]
@Priyankaagrawal your port has to be 8080. At the moment, we're blocking localhost calls that aren't set to port 8080.
