### ISSUE TITLE
Hosting a local MEW with local RPC over HTTPS w/NGINX

### ISSUE THREAD

**Issue by MysticRyuujin** [MyEtherWallet/MyEtherWallet#1153]
- **I'm submitting a ...**

  - [x] Feature request
  - [x] Bug report

- **Bug Report**
I'm trying to run a local (same network, not same system) instance of MEW based on the latest release zip file. I downloaded the ZIP, and I hosted it on an NGINX server. The problem is that the local instance is trying to make calls back to `https://api.myetherwallet.com/eth` so I get a pop up saying network error. When I use the developer tools I see

```
Request URL: https://api.myetherwallet.com/eth
Request Method: OPTIONS
Status Code: 403 Forbidden
```

I think that the REASON it's doing this is because it's trying to talk to your RPC hosts? Which is all well and fine but I can't seem to figure out how I can use my own RPC host. The reason I'm using NGINX is to serve all of this over HTTPS and I have my own RPC hosts available via HTTPS as well...

- **Feature Request**
Allow me to specify my own RPC host like the old version did?

**Comment by MysticRyuujin** [comment]
So I was able to run a `sed -i s#https://api.myetherwallet.com/eth#https://node.my.domain#g` against all of the files containing `https://api.myetherwallet.com/eth` and it seems to have fixed the issue...it would be nice if I didn't have to do that 😄

**Comment by gamalielhere** [comment]
@MysticRyuujin set your port to 8080. At the moment, we're blocking localhost calls that aren't set to port 8080.

**Comment by MysticRyuujin** [comment]
1. There's no option to change it as far as I can find
2. It's not a localhost anyway

**Comment by kvhnuke** [comment]
@MysticRyuujin actually you no longer have to do the NGINX HTTPS stuff. If you are either on chrome or firefox, they consider localhost as partially secure means of communications, and lets https sites talk to localhost apps. You should be able to do `npm start` and then goto `https://localhost:8080` and add your localhost node as a custom network make sure you use the following `http://localhost:8545` for HTTP RPC and `ws://localhost:8546/` for WS RPC. Note the `/` at the end for websockets

**Comment by MysticRyuujin** [comment]
@kvhnuke my Geth node is not hosted on my localhost, it's a separate server. I do not NGINX/MEW on the Geth server either. Nor do I build it from source, I use the release files.

So at no point in the chain can I use 'localhost', either for connecting to MEW, or connecting to Geth. I also don't run npm to host MEW...

**Comment by kvhnuke** [comment]
ah I see!
Yea in that case you can still add it as a custom node, if you'd like to compile your own version with just your node all the source files are here
https://github.com/MyEtherWallet/MyEtherWallet/tree/master/src/networks/nodes

**Comment by MysticRyuujin** [comment]
Alright so you guys kept saying I could add a custom node and I was really getting frustrated and confused because I had no idea how to do it other than building from source or running it via npm, etc. so I investigated further and I found that you have to first unlock your wallet using one of the available networks from the list and only THEN can you click the change network button and add a custom node.

My bad...I did not realize, I thought that the list of network provides was static.

**Comment by kvhnuke** [comment]
I'm sorry should've been more clear :)
I'm glad it worked out at the end! Let me know if you need any other help. 
Closing this.

**Comment by vrogojin** [comment]
Mew v6.0.4 does not seem to support adding custom nodes anymore. One can only choose networks from a fixed list.
