### ISSUE TITLE
ledger wallet webusb transport

### ISSUE THREAD

**Issue by ljq8896** [MyEtherWallet/MyEtherWallet#1156]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**
Since windows 1903, u2f was't supported by Microsoft. Chrome, firefox and opera are using webauthn and Windows Hello API instead. Ledger wallet may suggest to use Webusb even though windows have to fix a problem in Webusb. I have read [some enhancement](https://github.com/MyCryptoHQ/MyCrypto/pull/2569) from Mycrypto. 
And they have [fall back to U2F on Windows with Ledger devices](https://github.com/MyCryptoHQ/MyCrypto/pull/2581).
Is there any plan to add Webusb support for Ledger wallet user?

**Comment by gamalielhere** [comment]
@ljq8896 We already support Webusb with Ledger in MacOS and Linux for browsers that support WebUsb. As for windows, we fallback to u2f as seen [here](https://github.com/MyEtherWallet/MyEtherWallet/blob/master/src/wallets/hardware/ledger/index.js#L138)

**Comment by ljq8896** [comment]
Thank you. And how about to permit Chrome for android users access our Ledger walltet. Webusb is support in Chrome for android. Maybe some UI need to fix mobile.
