### ISSUE TITLE
Not finding my address with ledger nano s

### ISSUE THREAD

**Issue by s1r-mar71n** [MyEtherWallet/MyEtherWallet#1161]
- **I'm submitting a ...**
  - [+] Bug report

- **Bug Report**
  I used my ledger nano s in combination with myetherwallet in a timeframe from 09.10.2017 until 21.04.2018 without issues. 
But after that, it stopped showing my ethereum account with all of my balance. As derivation path, I used the default one, that MEW suggested to use (m/44'/60'/0') but I also tried different ones aswell. 
I did not lose my pin or recovery seed or anything like that, however after beeing unsuccessful in attempting to access my ether, I've updated, recovered etc. 
And for everybody claiming, that probably one word of my seed is wrong: In the same timeframe as mentioned above, I used the Ledger to also deal with NEO (with success) and after recovering from the seed, I'm still able to access that NEO. 
I do get that my behavior should not be possible (proper seed + derivation path = proper accounts), however it is the case here. 
And thats why I think it has to be a bug (something like MEW using a different derivation path despite showing a default one, or ledger doing that kind of thing).

**Comment by ljq8896** [comment]
Have you tried Ledger Live? That app scan both new derivation m/44'/60'/x'/0/0 and old ones m/44'/60'/0'/x. MEW suggested m/44'/60'/0'/x is correct derivation path in your timeframe. Do you use some advance function of nano s like 2nd password?
refer [this issue](https://github.com/MyCryptoHQ/MyCrypto/issues/2070)
