### ISSUE TITLE
Error "Cannot read property 'getAddressString' of null" when trying to acces MEW with Trezor

### ISSUE THREAD

**Issue by pankrats** [MyEtherWallet/MyEtherWallet#1162]
- **I'm submitting a ...**

  - [ ] Bug report

- **Bug Report**
browser Chrome, OS X

Steps-to-reproduce: 
1. go to https://www.myetherwallet.com/access-my-wallet, select Trezor
2. In Network and Addresses dialog do not select any address and click Access my Wallet:
<img width="523" alt="Screenshot 2019-06-10 at 14 27 14" src="https://user-images.githubusercontent.com/31442634/59195606-af0c1e00-8b8c-11e9-804f-3264b88973b8.png">

Result: 

<img width="518" alt="Screenshot 2019-06-10 at 14 27 22" src="https://user-images.githubusercontent.com/31442634/59195629-be8b6700-8b8c-11e9-9568-ea1d35bed678.png">

**Comment by pankrats** [comment]
Perhaps, it is related to this one https://github.com/MyEtherWallet/MyEtherWallet/issues/1148

**Comment by gamalielhere** [comment]
@pankrats This is related to #1148. I'll go and close this issue. Thanks!
