### ISSUE TITLE
PASSWORD DON' REQUIRED

### ISSUE THREAD

**Issue by kaifaty** [MyEtherWallet/MyEtherWallet#1169]
1. Create new wallet with seed phrase + password
2. Install MEW Connect
3. Restore wallet -> Input seeds.
Password is not required, just call to set new for MEW Connect!

**Comment by gamalielhere** [comment]
@kaifaty I suggest creating a new wallet with MEWconnect instead of restoring a seed from MEW5. If you have some balance, you can move it over through regular transactions.

**Comment by kaifaty** [comment]
I'm talking about the security issue.
I created a new wallet on the mnemonic phrase and chose password option. 
There is said: ![изображение](https://user-images.githubusercontent.com/11953142/59451287-8d2cc880-8e24-11e9-90ee-17b5c4430a30.png)

The next thing I did was install MEV Connect and press the "restore wallet" button. I was asked to enter only 24 words of the mnemonic phrase generated during creation. No one asked for a password, but they should have.
