### ISSUE TITLE
Remove PropTypes in Production Build

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#119]
Possibly via [babel-plugin-transform-react-remove-prop-types](https://www.npmjs.com/package/babel-plugin-transform-react-remove-prop-types)

**Comment by crptm** [comment]
Lets ditch proptypse all together

**Comment by dternyak** [comment]
Can you provide an example of type-checking a React components props so we can use that a best-practice moving forward?

**Comment by dternyak** [comment]
No longer relevant after switching to TypeScript.
