### ISSUE TITLE
Re-render translations on language change

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#121]
Right now our translations happen outside of the react ecosystem. Because of that, components that don't receive anything language related as a prop or implement componentShouldUpdate don't re-render upon changing languge. There are a few ways we could get around this:

1) Refresh the page on changing language. Not ideal UX, but this would also open us up to not sending all languages in the main JS build, slimming it down by a bit. You would only load the language you use.
2) Use something like https://github.com/gaearon/react-deep-force-update to force all components to re-render, even if they don't use translation, whenever the language changes. A little dirty, but would allow us to keep all other code exactly the same.
3) Create a `connect`ed `<Translation>` component, and use that instead.
4) Find an existing solution for localization, like `react-intl`.

Let me know what you think is best!

**Comment by wbobeirne** [comment]
Looks like force update is out: https://github.com/gaearon/react-deep-force-update/issues/2

**Comment by dternyak** [comment]
Fixed by https://github.com/MyEtherWallet/MyEtherWallet/pull/120
