### ISSUE TITLE
build 5.0.14-hotfix.2 show me error

### ISSUE THREAD

**Issue by collinswang** [MyEtherWallet/MyEtherWallet#1215]
build 5.0.14-hotfix.2 show me follow error
These dependencies were not found:

* @/contracts/contract-abi-akroma.json in ./src/networks/types/AKA.js
* @/contracts/contract-abi-ath.json in ./src/networks/types/ATH.js
* @/contracts/contract-abi-clo.json in ./src/networks/types/CLO.js
* @/contracts/contract-abi-egem.json in ./src/networks/types/EGEM.js
* @/contracts/contract-abi-ella.json in ./src/networks/types/ELLA.js
* @/contracts/contract-abi-esn.json in ./src/networks/types/ESN.js
* @/contracts/contract-abi-etc.json in ./src/networks/types/ETC.js
* @/contracts/contract-abi-eth.json in ./src/networks/types/ETH.js
* @/contracts/contract-abi-etho.json in ./src/networks/types/ETHO.js
* @/contracts/contract-abi-exp.json in ./src/networks/types/EXP.js
* @/contracts/contract-abi-go.json in ./src/networks/types/GO.js
* @/contracts/contract-abi-goerli.json in ./src/networks/types/GOERLI.js
* @/contracts/contract-abi-iolite.json in ./src/networks/types/IOLITE.js
* @/contracts/contract-abi-kov.json in ./src/networks/types/KOV.js
* @/contracts/contract-abi-mix.json in ./src/networks/types/MIX.js
* @/contracts/contract-abi-music.json in ./src/networks/types/MUSIC.js
* @/contracts/contract-abi-pirl.json in ./src/networks/types/PIRL.js
* @/contracts/contract-abi-poa.json in ./src/networks/types/POA.js
* @/contracts/contract-abi-reosc.json in ./src/networks/types/REOSC.js
* @/contracts/contract-abi-rin.json in ./src/networks/types/RIN.js
* @/contracts/contract-abi-rop.json in ./src/networks/types/ROP.js
* @/contracts/contract-abi-rsk-test.json in ./src/networks/types/RSKTEST.js
* @/contracts/contract-abi-rsk.json in ./src/networks/types/RSK.js
* @/contracts/contract-abi-tomo.json in ./src/networks/types/TOMO.js
* @/contracts/contract-abi-tt.json in ./src/networks/types/TT.js
* @/contracts/contract-abi-ubq.json in ./src/networks/types/UBQ.js
* @/contracts/contract-abi-web.json in ./src/networks/types/WEB.js
* @/darklist/address-darklist.json in ./src/store/state.js
* @/tokens/tokens-akroma.json in ./src/networks/types/AKA.js
* @/tokens/tokens-ath.json in ./src/networks/types/ATH.js
* @/tokens/tokens-clo.json in ./src/networks/types/CLO.js
* @/tokens/tokens-egem.json in ./src/networks/types/EGEM.js
* @/tokens/tokens-ella.json in ./src/networks/types/ELLA.js
* @/tokens/tokens-esn.json in ./src/networks/types/ESN.js
* @/tokens/tokens-etc.json in ./src/networks/types/ETC.js
* @/tokens/tokens-eth.json in ./src/networks/types/ETH.js
* @/tokens/tokens-etho.json in ./src/networks/types/ETHO.js
* @/tokens/tokens-exp.json in ./src/networks/types/EXP.js
* @/tokens/tokens-go.json in ./src/networks/types/GO.js
* @/tokens/tokens-goerli.json in ./src/networks/types/GOERLI.js
* @/tokens/tokens-iolite.json in ./src/networks/types/IOLITE.js
* @/tokens/tokens-kov.json in ./src/networks/types/KOV.js
* @/tokens/tokens-mix.json in ./src/networks/types/MIX.js
* @/tokens/tokens-music.json in ./src/networks/types/MUSIC.js
* @/tokens/tokens-pirl.json in ./src/networks/types/PIRL.js
* @/tokens/tokens-poa.json in ./src/networks/types/POA.js
* @/tokens/tokens-reosc.json in ./src/networks/types/REOSC.js
* @/tokens/tokens-rin.json in ./src/networks/types/RIN.js
* @/tokens/tokens-rop.json in ./src/networks/types/ROP.js
* @/tokens/tokens-rsk-test.json in ./src/networks/types/RSKTEST.js
* @/tokens/tokens-rsk.json in ./src/networks/types/RSK.js
* @/tokens/tokens-tomo.json in ./src/networks/types/TOMO.js
* @/tokens/tokens-tt.json in ./src/networks/types/TT.js
* @/tokens/tokens-ubq.json in ./src/networks/types/UBQ.js
* @/tokens/tokens-web.json in ./src/networks/types/WEB.js
* websocket in ./node_modules/web3-core-requestmanager/node_modules/web3-providers-ws/src/index.js, ./node_modules/web3-providers-ws/src/index.js

is that mean this repo lost /src/tokens  and /src/contracts directory ? 

how to fix it ?

platform Ubuntu 18.04

**Comment by gamalielhere** [comment]
@collinswang these files are created when you build the app locally. Try running `npm install; npm run build`
