### ISSUE TITLE
how to fix: Not enough Gas to send. on MEW. 400,000 + HOT tokens , but no gas??

### ISSUE THREAD

**Issue by robballonoff** [MyEtherWallet/MyEtherWallet#1232]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required
  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

- **Bug Report**
  - What is the current behavior?
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior?
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
    - Browser and version
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by robballonoff** [comment]
how to fix: "Not enough Gas to send." on MEW. 400,000 + HOT tokens , but no gas??
Instructions say just enter the tokens you want to send and the gas cost will auto fill. Nope...
How to fix that?? Otherwise my tokens are stuck in MEW and I can't access them...

**Comment by keepkeyjon** [comment]
You need ETH to pay for gas in order to send ERC20 tokens. Send some ETH to your deposit address, and then you'll be able to send your HOT tokens.

**Comment by robballonoff** [comment]
Thanks for that info. Seems easy answers aren't so easy after all. No wonder mass adoption is taking forever.
Rob B

    On ‎Saturday‎, ‎July‎ ‎6‎, ‎2019‎ ‎09‎:‎08‎:‎03‎ ‎PM‎ ‎EDT, keepkeyjon <notifications@github.com> wrote:  
 
 
You need ETH to pay for gas in order to send ERC20 tokens. Send some ETH to your deposit address, and then you'll be able to send your HOT tokens.

**Comment by truthman1990** [comment]
why don't you put that in the error message instead of making it cryptic?

**Comment by truthman1990** [comment]
> You need ETH to pay for gas in order to send ERC20 tokens. Send some ETH to your deposit address, and then you'll be able to send your HOT tokens.

could you put this in the error message? It would be very beneficial for new comers instead of having to google the error.
