### ISSUE TITLE
myetherwallet.com urls do not redirect to www.myetherwallet.com in all cases

### ISSUE THREAD

**Issue by tamirms** [MyEtherWallet/MyEtherWallet#1261]
- **I'm submitting a ...**

  - [ ] Feature request
  - [ x] Bug report

- **Bug Report**

If you go to https://myetherwallet.com/ the page redirects to https://www.myetherwallet.com/

However, if you go to https://myetherwallet.com/access-my-wallet or any other url where the URI path is not `/`, the page remains on the myetherwallet.com domain and does not redirect to  the www.myetherwallet.com domain.

This is problematic because 'https://api.myetherwallet.com/eth' from origin 'https://myetherwallet.com' is blocked by your CORS policy. So the app is essentially in a broken state because it can't make requests to `api.myetherwallet.com`

To fix the issue, either properly redirect all myetherwallet.com requests to www.myetherwallet.com, or, configure the api.myetherwallet.com CORS policy so that api.myetherwallet.com can be accessed from the myetherwallet.com domain.

**Comment by kvhnuke** [comment]
fixed! it might take couple of mins to propagate
Tested and working for me
@tamirms thanks for bringing this to our attention

**Comment by tamirms** [comment]
@kvhnuke I have verified that your fix works on my end. Unrelated to this issue, but could you take a look at https://github.com/MyEtherWallet/MyEtherWallet/pull/1260 when you have a chance? thanks!
