### ISSUE TITLE
Myetherwallet does not allow secure wallet creation offline

### ISSUE THREAD

**Issue by aids9345435345** [MyEtherWallet/MyEtherWallet#1272]
- **I'm submitting a ...**
  - [x] Bug report

Myetherwallet Keystore option only works online due to an error that happens with every browser. That leaves the option to download the mobile app to generate it, or do it online, which users with security in mind obviously not going to do because its not going to be storing noob amounts. Users can't easily find the vintage version for the same intended offline usage either.

Error:
https://i.imgur.com/kkRyoWg.png

**Comment by gamalielhere** [comment]
Fixed in #1273
