### ISSUE TITLE
Support iframe wallets, specifically ethvault.xyz

### ISSUE THREAD

**Issue by moodysalem** [MyEtherWallet/MyEtherWallet#1287]
**Feature Request**

  - Briefly explain the feature you would like to implement

Support iframe wallets, specifically Ethvault

  - What are the current issues this feature will solve

Convenience with regards to the ability to use a single Ethereum account from multiple devices. 
  
- Is this feature cross compatible with other ethereum networks

Yes

  - Are you willing to help us with development support if required

Yes

  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

Wallet selection

Please see these links:
About Ethvault: https://ethvault.xyz/about
Integration guide: https://github.com/ethvault/integration-guide

**Comment by s595** [comment]
Could some one just set my shit up my etherwallett

**Comment by kvhnuke** [comment]
unfortunately we wont be able to implement this due to security concerns around iframes
