### ISSUE TITLE
Rinkeby public resolver contract

### ISSUE THREAD

**Issue by nolash** [MyEtherWallet/MyEtherWallet#131]
- **I'm submitting a ...**

  - [X] Feature request
  - [ ] Bug report

- **Feature Request**

The Rinkeby ENS public resolver contract address seems to be missing from the interact with contract interface. Please consider adding it.

https://docs.ens.domains/en/latest/quickstart.html

**Comment by gamalielhere** [comment]
Closing, this should be included in #145 now.
