### ISSUE TITLE
How does MyEtherWallet calculate the correct transaction nonce?

### ISSUE THREAD

**Issue by tarekskr** [MyEtherWallet/MyEtherWallet#133]
How does MyEtherWallet calculate the correct transaction nonce (including pending transactions) when multiple transactions are being issued?

It's well known that [eth_getTransactionCount does not return the correct number of pending transactions](https://github.com/ethereum/go-ethereum/issues/2880), so I was wondering how you guys do it. Could be really beneficial for the community to learn from.

**Comment by gamalielhere** [comment]
@tarekskr Currently we use the eth.getTransactionCount. Since users can interact with the chain outside of MEW, we have to depend on the latest txcount on the chain. We might add a cacher and an automatic nonce incrementing function in the future but this has not been implemented yet.

**Comment by gamalielhere** [comment]
@tarekskr We are aware of that. But then again, users might have different activities outside of MEW, so we have no way to accurately estimate nonces. As mentioned above, we are looking to implement a cache system to keep track of nonces.

**Comment by gamalielhere** [comment]
Closing this issue. Let me know if you need anything else.
