### ISSUE TITLE
Print Mnemonic Phrase won't work

### ISSUE THREAD

**Issue by hsurf22** [MyEtherWallet/MyEtherWallet#1334]
- [x] Bug report

  - What is the current behavior?
     When I press [Print Mnemonic Phrase] button, Mnemonic Phrase table breaks.

  - What is the expected behavior?
     It supposed to show printable table.

  - Please tell us about your environment:
    - Operating system
      Ubuntu 19.04

    - Browser and version
      Chrome Version 76.0.3809.100 (Official Build) (64-bit)

![Screenshot from 2019-08-07 16-18-55](https://user-images.githubusercontent.com/9893774/62664133-41336700-b92f-11e9-85d5-c8adb2f54169.png)

![Screenshot from 2019-08-07 16-08-17](https://user-images.githubusercontent.com/9893774/62664075-f74a8100-b92e-11e9-92cb-324628428256.png)

**Comment by gamalielhere** [comment]
[This is fixed for the next release](https://github.com/MyEtherWallet/MyEtherWallet/blob/7c7dfb18d7a5581150a0713ef364b3ee05ed0ae9/src/layouts/CreateWalletLayout/containers/ByMnemonicContainer/components/PrintModal/PrintModal.vue#L72).
