### ISSUE TITLE
Fix invalid Lightstreams Network Ledger path

### ISSUE THREAD

**Issue by ggarri** [MyEtherWallet/MyEtherWallet#1349]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
There was an update done by other developer which affected the ledger path for Lightstreams network as we can see [in this commit](https://github.com/MyEtherWallet/MyEtherWallet/commit/8cfd705d594eda9663e4f4b586a1125d70848348#diff-68533bdf45afb84f4330fbb06949ceddL167). This issue intends to update Lightstreams network ledger path to use `m/44'/60'/0'`

**Comment by EnchanterIO** [comment]
Hey guys @kvhnuke / @gamalielhere, Gabriel's colleague here. Could we please get this one merged to fix the current bug for MeW Lightstreams users? 

Let us know if we can help anyhow more or you need more clarification!
