### ISSUE TITLE
Move BalanaceComponent Sidebar Items into Separate Component

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#145]
Reference: https://github.com/MyEtherWallet/MyEtherWallet/pull/141#discussion-diff-136209982R134

Bryan:
> All of these look pretty repetitive with the <li><span ...>, also all using formatNumber(balance.times.... Maybe pull it out to a component that takes in a rate & denomination and returns the li, span, denomination, and runs formatNumber.

- https://github.com/MyEtherWallet/MyEtherWallet/pull/141#discussion_r136209982

**Comment by wbobeirne** [comment]
I'll be doing this as a part of the style updates.
