### ISSUE TITLE
Choosing network through URL query string

### ISSUE THREAD

**Issue by yograterol** [MyEtherWallet/MyEtherWallet#1458]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - I would like to know if is possible to access to MEW passing the chain through the URL, by example `https://www.myetherwallet.com/?chain=CLO` and if not, why? do you like the feature?
  - Thinking the last point, it could be useful for dApps, passing more variables like `/?chain=CLO&to=0x....&data=0x....&value=1000`

**Comment by gamalielhere** [comment]
@yograterol at the moment, it isn't. We can include but I don't see a use case for it given that most dApps lay on specific networks, and the dApps integrated in MEW also checks for which network the user is currently on.

Other than switching networks automatically when you access MEW, what other use cases do you see this feature?

**Comment by yograterol** [comment]
@gamalielhere Got it, the primary uses for Callisto right now would be:

- Cold Staking dApp integrated to MEW.
- Direct link to MEW with CLO network selected.
- Direct link to Cold Staking dApp
- Integration with dApps using links to MEW with the transaction fields prefilled.

**Comment by gamalielhere** [comment]
@yograterol I see. Our current implementation only pre-fills send tx and send offline tx. I can add it there for now until we have integrated the dapps that would need them. Thanks for submitting this request!

**Comment by SarahFurkty** [comment]
Please contact marsarahfurkty@gmail.com if you are interested in good business and more thanks
Regards...
