### ISSUE TITLE
Can not access a Mnemonic Phrase ETH wallet 

### ISSUE THREAD

**Issue by TCB1234** [MyEtherWallet/MyEtherWallet#146]
I originally created a ETH wallet on a IMtoken app and have the Mnemonic phase keystone and private key for this wallet.  Then I went onto myetherwallet and accessed it with my Mnemonic Phrase and Password.  Then chose a address to access 0xa8d782bc7557D3c97B4429f2874f4aA9663F8C19. Then sent over 6 ETH but now when I signed back into myetherwallet with same Mnemonic Phrase and Password this address is not showing up? How can I access this address.  I don't understand why it is not showing on my list of addresses anymore.

**Comment by Zwilla** [comment]
which path did you choose on Mnemonic converter?

**Comment by TCB1234** [comment]
m/44'/60'/0'/0 i believe

**Comment by Zwilla** [comment]
ok! Wrong answer! 6 ETH and you believe ???

Try this path now: m/44'/0'/0'/0

**Comment by TCB1234** [comment]
Yeah I know I got careless, That Path m/44'/0'/0'/0 did not show the address, and neither do any of the other built in paths to choose from.

**Comment by Zwilla** [comment]
ok, I got the problem.

try it without password please

**Comment by TCB1234** [comment]
Still don't see it.

**Comment by Zwilla** [comment]
which software did you you to generate a Mnemonic Phrase?

You can use my converter to check it also:

https://mytokenwallet.com/bip39.html

Use it offline

**Comment by TCB1234** [comment]
The address that was generated and I sent the ETH to was different address than the original one that was generated in IMtoken,  was this where I messed up by putting my password in?  Because when I did not put the Password in it showed the IMtoken address at the top.

**Comment by Zwilla** [comment]
ok, let me guess! You got also on my converter you will get you address!

You discovered a new BUG on mew and mtw, because if you set a password or not you will get everytime the same address!

I will let you know that your money is not lost!

**Comment by TCB1234** [comment]
I got the original address that was generated from IMtoken at the top of the list when I put in my Mnemonic,  Is this what you mean?

**Comment by TCB1234** [comment]
And Thanks for all your help/responses

**Comment by Zwilla** [comment]
yes this is that what I mean. Address 0

**Comment by TCB1234** [comment]
I generated a Mnemonic and Addresses without and with passwords, 

0x46B386bDd3944ed95062f39e580Ff31E34621964 - without password

0xA4e93D7B1b7122499a4480D5519002C0022C9596 - with password

Went over to MEW 

put in Mnemonic in with out password and generated - 0x46B386bDd3944ed95062f39e580Ff31E34621964

Then click on new menu tab and the entered the Mnemonic in with password and generated - 0xA4e93D7B1b7122499a4480D5519002C0022C9596

**Comment by TCB1234** [comment]
Although I may have lost a lot of money kind of cool that I may have found a bug. If I need to do anything else let me know.  I also need to get some sleep, thanks again for the help and look forward to knowing the next steps.

**Comment by Zwilla** [comment]
if you use your Mnemonic and password, did you get your address 0xa8d782bc7557D3c97B4429f2874f4aA9663F8C19 on first place?

I will answer you later, after sleeping

**Comment by TCB1234** [comment]
Realized that the Mnemonic and Password generates random address and that if you change them new addresses are generated, didn't realize this before.  And if MEW didn't have a bug I must have done something wrong on my end.  Started playing around with the my password and found that I had entered it wrong originally and the 0xa8d782bc7557D3c97B4429f2874f4aA9663F8C19 popped up!  But so sorry I made you waste your time.   I will be sending you some ETH for you time though. Is that ETH address on your page good to send to?

**Comment by Zwilla** [comment]
## before give up try this

* try with your IMtoken App Mnemonic Phrase and your password to get the same address

* on your password field inside IMtoken App check for this issues:
    * spell checker which changes your text
    * size of the field: Example: you entered 21 letters but only 15 will be supported
    * typo’s: you thought: ‘hello’ but typed ‘hellp’
    * Text: left to right(LTR) or right to left (RTL)
        * if your password was: ‘hallo’  try ‘ollah'

**Comment by Zwilla** [comment]
## I installed IMToken=(*1) app

1.  the Mnemonic(*1) you get there  => use this on mew or mtw **without** a password!
    * why? Because on (*1) is the password included and the result is just a 12 Word mn

2.  the private key(*1) is exactly the same which you get when you unlock your on mtw with (1.)

***

thx
0xD78ec516C31A0fcd22D3CC6DC454FB87d686444e

If you really give up send me a direct mail under save@mytokenwallet.com 

**WARNING** **NEVER SEND YOUR PRIVATE KEY !!!*** 
** Also not to my email address. **
With that information your amount will be transferred to my account!
But if you did it: I will send you 4 ETH back, I hope :)

**Comment by dternyak** [comment]
@TCB1234 I'm glad your issue was resolved. Thank you @Zwilla for providing support. 

For the future, please file issues against the [V3 repo](github.com/kvhnuke/etherwallet) until we release V4

**Comment by Zwilla** [comment]
thx @TCB1234 for the donation 👍 and I’m glad about solving this problem!
