### ISSUE TITLE
chromium - local https webserver - cannot connect to ledger - NetworkError: Unable to reset the device

### ISSUE THREAD

**Issue by nonnanna** [MyEtherWallet/MyEtherWallet#1472]
Opened a local webserver with https in chromium.

Doing this since I cannot open without local webserver in chrome as reported in https://github.com/MyEtherWallet/MyEtherWallet/issues/1471

Tried to connect to ledger.

Same if in ledger main menu or inside ethereum app on ledger.

`{"event_id":"b288ffaba8e54754839d26ff92ebf77b","level":"error","message":"NetworkError: Unable to reset the device.","exception":{"values":[{"value":"NetworkError: Unable to reset the device.","type":"Error","mechanism":{"handled":true,"type":"generic"}}]},"platform":"javascript","sdk":{"name":"sentry.javascript.browser","packages":[{"name":"npm:@sentry/browser","version":"5.6.3"}],"version":"5.6.3","integrations":["InboundFilters","FunctionToString","TryCatch","Breadcrumbs","GlobalHandlers","LinkedErrors","UserAgent","Vue"]},"environment":"web","release":"5.1.4","request":{"url":"https://127.0.0.1:4443/MyEtherWallet-v5.1.4/#/access-my-wallet","headers":{"User-Agent":"Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/76.0.3809.100 Safari/537.36"}},"tags":{"network":"","service":"","walletType":""}}
`

**Comment by kvhnuke** [comment]
this sounds like an device issue, are you able to use it on the live site?
