### ISSUE TITLE
Disable or Show Loading Indicator of Token Options Selection While Loading

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#149]
Currently the selection menu only shows `ether` until the request resolves, whereby the selection is populated with additional token values like so: 
<img width="400" alt="screen shot 2017-08-30 at 7 16 27 pm" src="https://user-images.githubusercontent.com/7861465/29903250-c0f2260c-8db7-11e7-96fd-310aeb89ce1e.png">

While the request is resolving, we should provide either an indication that it is resolving, or disable the selection entirely.

I welcome opinions on the correct UX to best inform the user additional token options will be soon(™).

**Comment by wbobeirne** [comment]
The token list is now instantly loaded since it comes from local storage. This issue is no longer relevant.
