### ISSUE TITLE
Can't find the gpg public key for the releases

### ISSUE THREAD

**Issue by adminerest** [MyEtherWallet/MyEtherWallet#1563]
There is a .sig file in every release but I just can't find the gpg public key to verify the file. So where is it?

**Comment by liqu10** [comment]
The pub key is here: https://github.com/kvhnuke/etherwallet/blob/mercury/MEW-PUP-KEY-GPG

I dont understand why they havent put their public key in the new repo. Security is supposed to come first.

**Comment by adminerest** [comment]
> The pub key is here: https://github.com/kvhnuke/etherwallet/blob/mercury/MEW-PUP-KEY-GPG
> 
> I dont understand why they havent put their public key in the new repo. Security is supposed to come first.

Thanks!

**Comment by kvhnuke** [comment]
> The pub key is here: https://github.com/kvhnuke/etherwallet/blob/mercury/MEW-PUP-KEY-GPG
> 
> I dont understand why they havent put their public key in the new repo. Security is supposed to come first.

Will add a copy to this repo as well! 
@gamalielhere
