### ISSUE TITLE
Please cross sign pgp key with others in the WOT

### ISSUE THREAD

**Issue by jonathancross** [MyEtherWallet/MyEtherWallet#1565]
- **I'm submitting a ...**

[x] Feature request

- **Feature Request**

Please have your GPG key `2FCA 4A1E 3AF4 278F 7AD3  B763 7F05 9C0F 7B9A 12F0` cross-signed by others in the PGP Web Of Trust so we can establish that it is in fact authentic.

**Comment by liqu10** [comment]
I agree, please can you do this?

**Comment by kvhnuke** [comment]
please provide us a list of people/institutions you believe will be willing to sign. We can try reaching out to them

**Comment by jonathancross** [comment]
@kvhnuke - A lot of this depends on where the person controlling the key is located and which events they attend.

- At [FOSSDEM 2020](https://fosdem.org/2020/) you are guaranteed to find many people willing to sign keys from the Web Of Trust Strong Set.
- Anyone going to be at [36C3](https://events.ccc.de/congress/2019/wiki/index.php/Main_Page) in Leipzig?  I and many others willing to sign keys will be there.
- Devs form Debian tend to have well-connected keys as are leads from other cryptocurrency projects like Bitcoin.
- You have someone in german-speaking Switzerland?
- Unfortunately I don't directly know anyone in the Ethereum community that take security seriously and uses PGP.

I'm happy to make suggestions if you can provide more info.

**Comment by jonathancross** [comment]
ping @kvhnuke

**Comment by jonathancross** [comment]
ping @kvhnuke
