### ISSUE TITLE
Unable to withdraw ETH from a CDP

### ISSUE THREAD

**Issue by roncoejr** [MyEtherWallet/MyEtherWallet#1643]
- **I'm submitting a ...**

  - [ ] Feature request
  - [X] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required
  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

- **Bug Report**
  - What is the current behavior?  After repaying the DAI debt on a CDP I am unable to withdraw the collateralized ETH
![MEWcdpETHWithDrawFailure](https://user-images.githubusercontent.com/25880798/68769400-39e8bd00-05f2-11ea-808d-36095433e10a.png)

![MEWcdpETHWithdrawFail-Detail](https://user-images.githubusercontent.com/25880798/68769418-41a86180-05f2-11ea-9aa0-a8682d95bb26.png)

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior? **When attempting to withdraw ETH I expect it to succeed.  No errors and EVM reversion**
  - What is the motivation / use case for changing the behavior?  **To achieve an actual working code path.**
  - Please tell us about your environment:
    - Operating system: **Fedora Linux 30**
    - Browser and version: **Google Chrome 77**
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc):
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by roncoejr** [comment]
I should also mention that I can move the CDP to another account and then use the MakerDAO's cdp portal directly.  That will allow me to withdraw the ETH from the CDP.

**Comment by kvhnuke** [comment]
@SteveMieskoski
