### ISSUE TITLE
failed hash

### ISSUE THREAD

**Issue by str8bubble** [MyEtherWallet/MyEtherWallet#1677]
- **I'm submitting a ...**

  - [ ] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required
  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

- **Bug Report**
  - What is the current behavior?
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior?
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
    - Browser and version
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by gamalielhere** [comment]
@str8bubble can you elaborate on the issue?

**Comment by str8bubble** [comment]
Dear Gamaliel,

I am not sure what happened, as this included me trying to send a payment
from MEW browser extension to DAPPER browser extension.

the result was ,,failed hash,, error message. However sending money from
software MEW worked swell.

Dne út 26. 11. 2019 2:11 uživatel gamalielhere <notifications@github.com>
napsal:

**Comment by kvhnuke** [comment]
can you let us know which version of the MEW CX you are using? and is this consistent or intermittent issue?
