### ISSUE TITLE
Adding Custom Token - Can only enter 'e' or 'E' under symbol

### ISSUE THREAD

**Issue by stephenmew** [MyEtherWallet/MyEtherWallet#168]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
When inputting the symbol value for a custom token, I can only enter the letter 'e' over and over. No other letters can be input.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Accessed wallet via Keystore I had just made
Tried to add a custom token for 'Empowr' token
Entered contract address and Decimal count
Went to enter symbol, only E could be entered.
Spammed all letters of the keyboard and only e's and E's could be added to the field.

  - What is the expected behavior?
All letters are equal.

  - What is the motivation / use case for changing the behavior?
Tokens are not all 'E' or 'eee'.

  - Please tell us about your environment:
    - Operating system
Window 10

    - Browser and version
Chrome 70.0.3538.110

**Comment by gamalielhere** [comment]
<img width="1440" alt="screen shot 2018-11-21 at 11 13 28 am" src="https://user-images.githubusercontent.com/16236741/48863607-c0bbde80-ed7e-11e8-8d6e-b0b2d70829c3.png">
<img width="1440" alt="screen shot 2018-11-21 at 11 13 36 am" src="https://user-images.githubusercontent.com/16236741/48863608-c0bbde80-ed7e-11e8-9afb-0014262f877b.png">

Seems like its working as is. Closing issue.
