### ISSUE TITLE
my myetherwallet haven't received my  ICO tokens for one day. Who can help?

### ISSUE THREAD

**Issue by ecojane** [MyEtherWallet/MyEtherWallet#179]
I have transfered 2285.5949  ICO tokens to myetherwallet yesterday noon. But myetherwallet hasn't received the ICO tokens now.

TXhash:   0x9ff8dfcec4780cbbb198e7137ad097e20bec03a9e63141feb143fb848eecdcb2

**Comment by tayvano** [comment]
That transaction cannot be found. 

Please email support@myetherwallet.com if you need more assistance. This repo is for developers to track and deal with issues pertaining to MEW v4.

Thank you
