### ISSUE TITLE
No tx hash provided at "Success" Screen

### ISSUE THREAD

**Issue by brnpope** [MyEtherWallet/MyEtherWallet#182]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  **- What is the current behavior?**
Upon completion of a transaction, a success drop down appears. No TX Hash appears.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior?
The "Success" drop down would provide the tx so as to easily monitor its status
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system - Windows
    - Browser and version - Chrome Version 70.0.3538.110 (Official Build) (64-bit)
  - Other information - Transactions performed with a Ledger Nano

**Comment by gamalielhere** [comment]
Closing this now in favor of the new notifications implementation
