### ISSUE TITLE
MyEtherWallet have api?

### ISSUE THREAD

**Issue by ex247365** [MyEtherWallet/MyEtherWallet#1838]
Hi.
MyEtherWallet have api?
Best regards.

**Comment by gamalielhere** [comment]
@ex247365 what type of API are you asking?

**Comment by ex247365** [comment]
Thank you for your respond.
Generate new address for receive ERC20 token and ETH.

**Comment by gamalielhere** [comment]
@ex247365 you can go through it here: https://www.myetherwallet.com/create-wallet

**Comment by ex247365** [comment]
Dear friend,
We need API to Generate new address.

**Comment by gamalielhere** [comment]
@ex247365 we unfortunately don't have an api that we can expose to generate a wallet. However, you can use this library by the Foundation: https://github.com/ethereumjs/ethereumjs-wallet
