### ISSUE TITLE
Redundant string conversion in RPCNode?

### ISSUE THREAD

**Issue by HenryNguyen5** [MyEtherWallet/MyEtherWallet#187]
https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/common/libs/nodes/rpc/index.js#L26
Is there a reason we're typecasting to string on the resulting JSON response?
I did a test on `getBalance` and the result is already a string

**Comment by dternyak** [comment]
I don't believe this issue is relevant anymore - let me know if I am incorrect @HenryNguyen5
