### ISSUE TITLE
Sending Custom NFT: Wrong To Address in Confirmation

### ISSUE THREAD

**Issue by sebastiantf** [MyEtherWallet/MyEtherWallet#1871]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - When trying to send a custom NFT token to another address, the `To Address` specified is not same as my input in the Send Token To Address field
  - To Reproduce:
    1. Add Custom NFT Token
    2. Select the newly added custom NFT Token
    3. In the **Send Token** portion, enter the desired `To Address`
    4. Click **Send** and let the confirmation modal pop up
    5. Check to see that the `To Address` in confirmation modal is not the same as what was entered in Step **`c`**.

**Note:** The To Address shown in the confirmation modal seems to be the token contract address of the custom token that was used to add the token

- **Expected Behaviour**
  - The `To Address` shown in confirmation modal is same as the address input in Step c.

- Environment:
    - macOS 10.14.5
    - Chrome 79.0.3945.117

- Where can this be found?: /interface/nft-manager

- **Screenshots:**

![nft1](https://user-images.githubusercontent.com/36922376/72558856-8c33ac00-38c9-11ea-9aa5-ee2ab36af83f.png)

![nft2](https://user-images.githubusercontent.com/36922376/72558858-8c33ac00-38c9-11ea-928b-a12cd3296d3d.png)

**Comment by sebastiantf** [comment]
Has anyone looked into this issue?

**Comment by gamalielhere** [comment]
@sebastiantf can you try it again, it should show the address you're sending to and the contract address you're interacting with.

**Comment by sebastiantf** [comment]
@gamalielhere I shall try again and report back.
