### ISSUE TITLE
Send / Modal Style Regressions

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#189]
This is probably my fault from the v3 style import, but the spacing is all janky now. This is just an issue to make sure I don't forget to fix this.

<img width="756" alt="screen shot 2017-09-12 at 2 44 01 pm" src="https://user-images.githubusercontent.com/649992/30342777-0383f296-97c9-11e7-9469-42aaeac48ea1.png">

<img width="804" alt="screen shot 2017-09-12 at 2 46 31 pm" src="https://user-images.githubusercontent.com/649992/30342837-3974e8ec-97c9-11e7-9fcb-77c5b0e5acb1.png">

<img width="640" alt="screen shot 2017-09-12 at 2 46 59 pm" src="https://user-images.githubusercontent.com/649992/30343011-d2896850-97c9-11e7-90da-a7e5600fb2d7.png">

**Comment by dternyak** [comment]
@wbobeirne Tablet sized screens have some additional spacing issues. I can get the exact resolution if you need. 
<img width="464" alt="screen shot 2017-10-06 at 2 54 04 pm" src="https://user-images.githubusercontent.com/7861465/31300011-4839af94-aaa6-11e7-8acb-7b812be36615.png">

**Comment by wbobeirne** [comment]
The very long copy there definitely doesn't help, but I guess the ideal behavior would be that each button becomes full-width with center aligned text. Not sure if there's a way to intuit when the buttons wrap, so we may just have to set some kind of breakpoint for that.
