### ISSUE TITLE
First time "Get a New Wallet" layout issue 

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#190]
- **I'm submitting a layout issue**

  - [x] Bug report

-![image](https://user-images.githubusercontent.com/31494364/49480466-a69cea00-f7db-11e8-95bf-0afeeeddb5a3.png)

![garlands](https://user-images.githubusercontent.com/31494364/50541249-4a1cb880-0b56-11e9-8ca0-2a982009bbc3.png)

 **Bug Report**
  - What is the current behavior?
Missing garlands PNG.
  - What is the expected behavior?
Add garlands

**Comment by hsurf22** [comment]
Jack will provide mock-up images for this later.

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/pull/632
Fixed
