### ISSUE TITLE
Font change color

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#192]
- **I'm submitting a bug**

  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49480978-ab629d80-f7dd-11e8-92b1-8c5142ecd259.png)

- **Bug Report**
  - What is the current behavior?
 At "Get a New Wallet" page, Tabs font are wrong color.
  - What is the expected behavior?
Unselected status font color change to #999999

**Comment by hsurf22** [comment]
Fixed

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/commit/09d41113a41f6cd4f4427fc4b21c7fda5d95f29a
