### ISSUE TITLE
Online / Offline Send State

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#193]
Button in top-right. 

IF the user is offline, the button reads "Go Online" with the red, offline icon.

If the user is online, the button reads "Go Offline" with the green, online icon.

### Offline State

- Shows Data and Nonce fields.

- Do not estimate gas. If sending ETH, gas limit = `21000`. If sending tokens, gas limit is `150000`.

- Gas price from slider like always

- Clicking "Generate Transaction" only generates the transaction. To send they need to be online. 

- Link a ( ? ) icon next to nonce field to knowledge base article on how to get nonce: https://myetherwallet.groovehq.com/knowledge_base/topics/what-is-nonce. (this will be updated / changed at some point)

- If offline, add sentence below the generated transaction:  "To broadcast this transaction, paste the above into myetherwallet.com/pushTx or etherscan.io/pushTx"

**Comment by dternyak** [comment]
I believe we should only provide the "Go Offline" Button the send detail view when the user is using private keys/keystores, as ledger/trezor/metamask may not allow you to provide them the nonce you would like them to sign with.
