### ISSUE TITLE
All disable button color change

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#193]
- **I'm submitting a bug**

  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49481105-27f57c00-f7de-11e8-9b9f-9b80ea60a018.png)

  - What is the current behavior?
Current button color is too light.
  - What is the expected behavior?
Change all disable button color to #999999

**Comment by SteveMieskoski** [comment]
believe this is fixed. Will reopen if this is still occurring
