### ISSUE TITLE
Footer issues

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#194]
- **I'm submitting a bug and feature request**

  - [x] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49481273-119bf000-f7df-11e8-9e4d-7acce2945ce6.png)

![image](https://user-images.githubusercontent.com/31494364/49481275-1496e080-f7df-11e8-8478-01e09f7ad7f1.png)

- **Bug Report**
  - What is the current behavior?
Spelling wrong and links do not work
  - What is the expected behavior?
     a.) Change "Others" to "MEW Github"
     b.) Tx Status link to https://etherscan.io/
     c.) Debugs / Extension / MEW Github can not be opened  
     c.) CoinMarketCap can not be linked to  https://coinmarketcap.com/

**Comment by gamalielhere** [comment]
Closing this. Updated one is on #230
