### ISSUE TITLE
"ethereum:" protocol handler

### ISSUE THREAD

**Issue by emilbayes** [MyEtherWallet/MyEtherWallet#1940]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement

Register a custom protocol handler to EIP681 ethereum URLs. IRCCloud registers one for `irc:` and `ircs:`, Trezor registers one for `bitcoin:` etc.

  - What are the current issues this feature will solve

Making pre-filling payments easier, kind of like the URL (legacy?) scheme works today with query string

  - Is this feature cross compatible with other ethereum networks

This seems pretty widely deployed, despite the EIP being a draft

  - Are you willing to help us with development support if required

Yes I can submit a PR. The required API is documented here: https://developer.mozilla.org/en-US/docs/Web/API/Navigator/registerProtocolHandler It is not too widely supported, however it's a great convenience when it does work, and will benefit a high percentage of users.

  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

I think `/interface/send-transaction`

**Comment by rfcid** [comment]
eth: 0x82614c37d48c0483DEb0623AA52E47EB30BfA955

btc: 1LY6ui1AgYZkEuZ9763uypG7c4C2LPEvvL
