### ISSUE TITLE
Top Nav-bar update

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#196]
- **I'm submitting a Feature request and bug report **

  - [x] Feature request
  - [x] Bug report

- **Feature Request**
![image](https://user-images.githubusercontent.com/31494364/49481563-583e1a00-f7e0-11e8-92b6-26753cfcd0c8.png)

![image](https://user-images.githubusercontent.com/31494364/49481793-4446e800-f7e1-11e8-8447-7c969efc552f.png)

  - Briefly explain the feature you would like us to implement
Add a button "Access" to let user access their wallet more user friendly.

- **Bug Report**
  - What is the current behavior?
a.) Missing a “Access” button.
b.) Flags GREEN SHADOW
c.) Flags are stretched
d.) Buttons name are too long

  - What is the expected behavior?
a.) Add a "Access" button.
b.) Delete flags GREEN SHADOW
c.) Do not stretch flags
d. Buttons name are changed to "New Wallet" and "Access"

**Comment by hsurf22** [comment]
Fixed
https://github.com/MyEtherWallet/MyEtherWallet/pull/326
