### ISSUE TITLE
Update contents

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#197]
- **I'm submitting a bug**

  - [x] Bug report

- **Bug Report**
![image](https://user-images.githubusercontent.com/31494364/49481881-b0295080-f7e1-11e8-8724-828d218320d0.png)

  - What is the current behavior?
Miss contents
  - What is the expected behavior?
Replace contents:
a.) MEW Wallet -
Access the Ethereum blockchain’s original and most-trusted wallet client, now with a host of new features all contained in an elegant, easy-to-use interface.
b.) Hardware Wallet Support -
MEW supports all major hardware wallets including Ledger, Trezor, Digital Bitbox, Secalot, and many more.
c.) Swap -
MEW has partnered with Bity, Kyber Network, and Simplex to allow users to swap fiat to crypto, ETH and BTC, ETH and ERC-20.
d.)MEWconnect -
MEW’s companion app brings hardware-wallet style security to your iOS or Android device, helping you to secure your funds as never before.

**Comment by gamalielhere** [comment]
This has been fixed on the develop branch
