### ISSUE TITLE
Connection error when sending ETH 

### ISSUE THREAD

**Issue by avaulasvirta** [MyEtherWallet/MyEtherWallet#1981]
- **I'm submitting a ...**

  - [ ] Feature request
  - [ x] Bug report

- **Feature Request**
Hello,

I'm trying to send ETH from my wallet to another. However, when I log in, add the wallet ID and send, it always says connection error: we were unable to send. I have triple checked the receiving address and it is correct.

**Comment by luuquocviet379** [comment]
luuquocviet
