### ISSUE TITLE
Footer font color of tutorial page needs to be changed

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#202]
- **I'm submitting a bug**

  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49484149-d0a9d880-f7ea-11e8-97ae-1c5373da6967.png)

- **Bug Report**
  - What is the current behavior?
Tutorial page footer font color is green
  - What is the expected behavior?
Font color change to  #96A8B6

**Comment by gamalielhere** [comment]
This doesn't seem to be the issue anymore.
