### ISSUE TITLE
Refactor SendTransaction tab

### ISSUE THREAD

**Issue by HenryNguyen5** [MyEtherWallet/MyEtherWallet#205]
Currently there's still a lot of transaction only functions inside the component itself that can be taken out, then re-used in other tabs like the ENS and Contracts tab

**Comment by dternyak** [comment]
Duplicate of https://github.com/MyEtherWallet/MyEtherWallet/issues/142

**Comment by dternyak** [comment]
I've assigned you to https://github.com/MyEtherWallet/MyEtherWallet/issues/142 instead :)
