### ISSUE TITLE
Access hardwareWallet object instance in InterfaceLayout.vue (for switchAddress())

### ISSUE THREAD

**Issue by Tomasvrba** [MyEtherWallet/MyEtherWallet#2052]
- **I'm submitting a ...**

  - [x] Feature request

- **Feature Request**

  - Briefly explain the feature you would like us to implement

Instead of re-creating the hww object in `switchAddress()`, be able to access the existing object in `InterfaceLayout.vue` with `this.hardwareWallet` like already possible in `NetworkAndAddressModal.vue` on the props:
```
  props: {
    hardwareWallet: {
      type: Object,
      default: function() {
        return {};
      }
    }
```

  - What are the current issues this feature will solve

The BitBoxBridge is able to detect when a connection closes, so I would like to provide it with the `clearWallet` action as a callback, to clear the MEW interface when the user unplugs the usb device. However, this causes an issue when switching addresses, as the entire hww object is re-created, a new connection is initialized, the old websocket closes and therefore `clearWallet` is called. When this happens, then `toggleNetworkAddrModal(walletInstance)` no longer has access to the necessary `$refs` after `clearWallet`. 

It would be great to just be able to call `this.hardwareWallet.init(selectedPath)` on the existing hww instance like in `NetworkAndAddressModal.vue`, then on the hww side, I can implement `init` to not close the websocket connection to the BitBoxBridge.

  - Is this feature cross compatible with other ethereum networks

Yes
  - Are you willing to help us with development support if required

Yes
  - Where can this be added?

`/interface`

**Comment by kvhnuke** [comment]
I believe this is a good idea @gamalielhere @SteveMieskoski thoughts?
