### ISSUE TITLE
Localhost MyEtherWallet etherscan.io API KEY

### ISSUE THREAD

**Issue by rudijs** [MyEtherWallet/MyEtherWallet#2069]
Hi,

When running the MEW release locally (localhost:8000) I need to use the etherscan.io network (or one of the other network options).

The myetherwallet.com network errors with failed HTTP CORS requests, as the client is running on localhost, not on myetherwallet.com.

Using etherscan.io's network was fine, until today I am seeing "Invalid API Key" errors from what I think is this from etherscan.io:

"Starting from February 15th, 2020, all developers are required to use a valid API key to access the API services provided by Etherscan"

Is there a way to set the API KEY for etherscan.io ?

So that I can run MEW on localhost and use the etherscan.io network.

The error looks like this:

![mew](https://user-images.githubusercontent.com/1711940/76162103-19caa400-6175-11ea-8345-db7f2c221208.png)

**Comment by rudijs** [comment]
The pokt.network appears to be the only one that works out-of-the-box from localhost.

infura.io 403 errors, etherscan.io wants and API Key, myetherwallet.com seems blocked by CORS requests not coming from myetherwallet.com.


![mew2](https://user-images.githubusercontent.com/1711940/76162185-fc4a0a00-6175-11ea-93e7-67502d521562.png)

**Comment by kvhnuke** [comment]
Can you run mew on https://localhost:8080 this is the only path allowed in our core. If you run it on 8080 you should be able to use MyEtherWallet nodes

**Comment by gamalielhere** [comment]
Fixed in the upcoming release
