### ISSUE TITLE
Convert Units input box issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#210]
- **I'm submitting a bug**

  - [x] Bug report

a.) ![image](https://user-images.githubusercontent.com/31494364/49544077-c4775700-f88e-11e8-9992-fa6bb0335950.png)

b.) ![image](https://user-images.githubusercontent.com/31494364/49544335-6eef7a00-f88f-11e8-9f0e-52cb9274bc20.png)

- **Bug Report**
  - What is the current behavior?
a.) Input box can be entered letter
b.) Drop down arrow is to closed right
  - What is the expected behavior?
a.) Input box can not be entered letter
b. ) Make sure the drop down margin right 16 px

**Comment by gamalielhere** [comment]
@jackhuangusa what page is this on?

**Comment by jackhuangusa** [comment]
@gamalielhere  Units, link on the footer
