### ISSUE TITLE
Error calling contract with address[] parameter

### ISSUE THREAD

**Issue by riartem** [MyEtherWallet/MyEtherWallet#211]
My contract can get array of "address" values as method parameter. But when I try to execute that method from MyEtherWallet (by pressing Write button), it fails with console errors.
![image](https://user-images.githubusercontent.com/987517/30597175-e7debe54-9d5e-11e7-86db-447882aca082.png)
Of course is "not a number" it's an address.

At the web interface this method displayed correctly:
![image](https://user-images.githubusercontent.com/987517/30597232-16224dc6-9d5f-11e7-944c-b5731b093084.png)

**Comment by wbobeirne** [comment]
It's poorly documented, but it looks like it just splits on commas. Could you try entering `0x...,0x...` instead?

**Comment by wbobeirne** [comment]
I also just realized that this is a v3 issue, as v4 doesn't have contracts fully implemented. If my suggestion didn't work, could you reopen this issue on https://github.com/kvhnuke/etherwallet?
