### ISSUE TITLE
Access by MEWconnect 

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#211]
- **I'm submitting a bug**

  - [x] Bug report

- **Feature Request**

Current layout
![image](https://user-images.githubusercontent.com/31494364/49545102-7e6fc280-f891-11e8-9d1b-1dac988f377a.png)

Design 
![image](https://user-images.githubusercontent.com/31494364/49545119-8e87a200-f891-11e8-8ae9-44611f26228d.png)

- **Bug Report**
  - What is the current behavior?
a.) Title "MEW connect" spelling wrong.
b.) Layout issue
c.) "Apple Store" and "Google Play" button are not clickable.
  - What is the expected behavior?
a.) Change "MEW connect" to "MEWconnect"
b.) Make current layout match as the design(Missing Google Play icon).
c.) Make sure Apple Store" and "Google Play" button are clickable.

**Comment by gamalielhere** [comment]
This looks like it's currently fixed in develop environment.
