### ISSUE TITLE
Scroll top arrow upside down

### ISSUE THREAD

**Issue by gamalielhere** [MyEtherWallet/MyEtherWallet#213]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
  ui issue, arrow should be facing up
![arrow-bug](https://user-images.githubusercontent.com/16236741/49550248-d1507680-f89f-11e8-9d1c-ab8f511e3b58.jpg)

**Comment by hsurf22** [comment]
This image will be replaced soon, but it looks okay on my screen.
