### ISSUE TITLE
gas limit and price missing for smart contract writes

### ISSUE THREAD

**Issue by SCBuergel** [MyEtherWallet/MyEtherWallet#2145]
- **I'm submitting a ...**
  - [x] Bug report

- **Bug Report**
When [writing to a smart contract](https://www.myetherwallet.com/interface/interact-with-contract), the UI does not allow me to manually set a gas price or gas limit. That makes that whole part of the interface fairly useless (tx fails). I suggest to add a textbox to enter gas limit and gas price to the UI in a similar fashion as for the simple `send tx` interface.

**Comment by kvhnuke** [comment]
GasPrice is set in settings, it is global for all actions in MEW. Gas limit is automatically estimated

**Comment by SCBuergel** [comment]
> GasPrice is set in settings, it is global for all actions in MEW. Gas limit is automatically estimated

Thanks, I didnt know the gas price was in the settings!

I think it's still a good idea to let users chose to manually adjust the gas limit - maybe as expert settings?
