### ISSUE TITLE
Address-only unlock

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#215]
Allow people to "unlock" their wallet by only providing the address, if they just want to send offline or view their wallet. At its best this may require a little restructuring of the wallets and components to check for a `readOnly` attribute on wallets. At its simplest, we could just extend the existing wallet class, but reject all of the promises for things like signing transactions.

**Comment by dternyak** [comment]
Duplicate of https://github.com/MyEtherWallet/MyEtherWallet/issues/215
