### ISSUE TITLE
where are the public keys of the releases?

### ISSUE THREAD

**Issue by hivemall** [MyEtherWallet/MyEtherWallet#2159]
i need trusted source to check the sig with gnupg, searching public key on your website is frenzy.
please what is trusted source to check sig MyEtherWallet-v5.4.3.zip.sig

https://github.com/MyEtherWallet/MyEtherWallet/releases

gpg --verify MyEtherWallet-v5.4.3.zip.sig MyEtherWallet-v5.4.3.zip
gpg: Signature made Wed 18 Mar 2020 06:58:00 PM CET
gpg:                using RSA key 7F059C0F7B9A12F0
gpg: Can't check signature: No public key

?

also: verified commit by : GPG key ID: 4AEE18F83AFDEB23
which is not the signing key. please enlightn

**Comment by eov** [comment]
I recently encountered this same problem and found the answer here:
https://www.reddit.com/r/MyEtherWallet/comments/bz03mr/verify_offline_version_mew/
https://github.com/MyEtherWallet/etherwallet/issues/1651#issuecomment-371345501
I think this should be clearly stated in the release notes.

$ ll MyEtherWallet-v5.6.5.zip*
-rw-r--r-- 1 tarok 21795262 Jun 15 21:13 MyEtherWallet-v5.6.5.zip
-rw-r--r-- 1 tarok      566 Jun 15 21:13 MyEtherWallet-v5.6.5.zip.sig
$ 
$ gpg --verify MyEtherWallet-v5.6.5.zip.sig
gpg: assuming signed data in 'MyEtherWallet-v5.6.5.zip'
gpg: Signature made Wed Jun 10 15:00:58 2020 PDT
gpg:                using RSA key 2FCA4A1E3AF4278F7AD3B7637F059C0F7B9A12F0
gpg: Can't check signature: No public key
$ gpg --keyserver keyserver.ubuntu.com --search-keys 2FCA4A1E3AF4278F7AD3B7637F059C0F7B9A12F0
gpg: data source: http://162.213.33.9:11371
(1)	MyEtherWallet Inc <support@myetherwallet.com>
	  4096 bit RSA key 7F059C0F7B9A12F0, created: 2018-03-07
Keys 1-1 of 1 for "2FCA4A1E3AF4278F7AD3B7637F059C0F7B9A12F0".  Enter number(s), N)ext, or Q)uit > 1
gpg: key 7F059C0F7B9A12F0: public key "MyEtherWallet Inc <support@myetherwallet.com>" imported
gpg: Total number processed: 1
gpg:               imported: 1
$ gpg --keyserver keyserver.ubuntu.com --receive-keys 2FCA4A1E3AF4278F7AD3B7637F059C0F7B9A12F0
gpg: key 7F059C0F7B9A12F0: "MyEtherWallet Inc <support@myetherwallet.com>" not changed
gpg: Total number processed: 1
gpg:              unchanged: 1
$ gpg --verify MyEtherWallet-v5.6.5.zip.sig
gpg: assuming signed data in 'MyEtherWallet-v5.6.5.zip'
gpg: Signature made Wed Jun 10 15:00:58 2020 PDT
gpg:                using RSA key 2FCA4A1E3AF4278F7AD3B7637F059C0F7B9A12F0
gpg: Good signature from "MyEtherWallet Inc <support@myetherwallet.com>" [unknown]
gpg: WARNING: This key is not certified with a trusted signature!
gpg:          There is no indication that the signature belongs to the owner.
Primary key fingerprint: 2FCA 4A1E 3AF4 278F 7AD3  B763 7F05 9C0F 7B9A 12F0
$
