### ISSUE TITLE
Improve UX of high n value keys

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#219]
From https://github.com/kvhnuke/etherwallet/issues/486, the browser locks up (especially on slower computers) so let's see if we can async this.

**Comment by tayvano** [comment]
This was sent to me via twitter maybe like 6 months ago as a "this is how it could be handled better but this lib isnt production ready" : https://github.com/ryancdotorg/scrypt-async-js

**Comment by HenryNguyen5** [comment]
Yeah, looks like they're doing the setTimeout trick
