### ISSUE TITLE
Support MetaMask / Mist / other web3 wallets

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#220]
More context for this can be found at https://github.com/kvhnuke/etherwallet/issues/238, but I think the gist of it is to check for `window.web3` and see if we can use that for a wallet.

Unlike that post though, I think we should provide that as an option amongst our other list, rather than use it immediately. I'm sure many folks (such as myself) have a metamask wallet _and_ a hardware or paper wallet that they want to access.

**Comment by dternyak** [comment]
Implementation for V3 can be found in https://github.com/kvhnuke/etherwallet/pull/814
