### ISSUE TITLE
A scenario which user skip the tutorial

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#221]
- **I'm submitting a feature request**

  - [x] Feature request

![image](https://user-images.githubusercontent.com/31494364/49612023-41bace80-f958-11e8-9de5-113c478b93b6.png)

![image](https://user-images.githubusercontent.com/31494364/49612075-6a42c880-f958-11e8-8b9f-74f62fe50aee.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
While user click the skip button, the tutorial popup will narrow to right bottom as a circle button.
  - What are the current issues this feature will solve
Add a button at the right bottom that can let user to continue the tutorial.

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/commit/34a78f8fb87e89269b9b7d2468af12ae8b04ed95

Security user reminder button added.

**Comment by hsurf22** [comment]
Steve or Yel will decide when to make this button active.

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/pull/282
