### ISSUE TITLE
page does not load in TOR browser

### ISSUE THREAD

**Issue by SCBuergel** [MyEtherWallet/MyEtherWallet#2242]
- **I'm submitting a ...**
  - [x] Bug report

- **Bug Report**
I am using the latest [TOR browser](https://www.torproject.org/) and navigating to myetherwallet.com. The page remains entirely blank, only the favicon and title in the browser window loads. I can reproduce this behavior in latest mac OS and tails OS with latest TOR browser.

**Comment by SCBuergel** [comment]
Potentially this is related: I just tried making a backup of the page on [Arweave](https://5ndcdznlbzec.arweave.net/ek3sytwYkOQ_by16ThNFhLoDgdBEMv-pZUJivvpsu-g) (something similar to IPFS but persistent) which is also just loading a blank page, even in non-TOR browsers. I would expect MEW to be a static page that just loads wherever I have the resources (on your webserver, on IPFS or alike).

**Comment by kvhnuke** [comment]
We have onion routing enabled, can you make sure you have JavaScript enabled in the browser. Also, do you get any errors in browser console
