### ISSUE TITLE
Buggy swap error message

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#226]
I'm on a pretty slow connection, so this might just be an issue that happens when you haven't loaded exchange rates. But putting a 1 into the left field (btc) prompted me with this:

<img width="710" alt="screen shot 2017-09-23 at 1 30 15 pm" src="https://user-images.githubusercontent.com/649992/30775530-7e22ce4e-a063-11e7-8119-8bd6040de3d6.png">

**Comment by dternyak** [comment]
Loading indicators while swap rates are being requested should fix this.

Additionally, error messages should be displayed within the form. Ex here: 
![2017-10-26 14 25 45](https://user-images.githubusercontent.com/7861465/32191285-beb7e210-bd6d-11e7-87ac-227c3c1cfd4a.gif)
