### ISSUE TITLE
Swap layout modification

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#227]
- **I'm submitting a ...**

  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49670846-d8e85a80-fa1a-11e8-99a3-a11ad4d993ab.png)

- **Bug Report**
  - What is the current behavior?
Providers layout is not user friendly
  - What is the expected behavior?
Modify providers layout as the design, and high light the Min/Max rate while the number out of range in the input box.

**Comment by hsurf22** [comment]
I'll fix this after the beta release.

**Comment by SteveMieskoski** [comment]
fixed in or before PR #537
