### ISSUE TITLE
Broken Links

### ISSUE THREAD

**Issue by gamalielhere** [MyEtherWallet/MyEtherWallet#230]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
 Some links go nowhere:
Feedback, TX status, Advanced tools, Extension, Customer Service

**Comment by kvhnuke** [comment]
Feedback : `https://github.com/MyEtherWallet/MyEtherWallet/issues`
TX status: `no longer needed`
Advanced:  `not implemented yet, Technically Units should be under advance including all the other tools from https://www.myetherwallet.com/helpers.html`
Extension: `https://chrome.google.com/webstore/detail/myetherwallet/nlbmnnijcnlegkjjpcfjclmcfggfefdm?hl=en`
customer service : `mailto:support@myetherwallet.com`
