### ISSUE TITLE
Replace Sagas with Simpler Side-Effect libraries

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#230]
## Why?
While subjective, the team agrees that we don't need the additional complexity/boilerplate that comes with sagas. We would like to add side-effect libraries with smaller learning curves and are better suited for our simpler use-cases.

Thunks and promise-middle-ware have much less abstraction in comparison to sagas, which gives simple and concise code flow for more basic side effects. Sagas can and will still be used for more complex flows where their extra added power can be used effectively

### Replacements
1. [ ] `Thunks`

2. [x]  `Redux-Promise-Middleware`
     1. Handles dispatched promise instead of dispatched functions
     2. Redux promise middleware comes with some extras that handles dispatching fail/succeeded actions based on the result of the resolution of the promise. 

You can use thunks in-tandem with `redux-promise-middleware` for chaining promise.

The standard I would like to settle on is for using `redux-promise-middleware` for basic network requests, `thunks` for most async-effects beyond simple network requests, and `redux-saga` when all else fails.

**Comment by skubakdj** [comment]
I have limited experience with both libraries, but choosing one depending on the complexity of the async sounds like a solid plan. Looking through the `redux-promise-middleware` docs & examples, this seems like the intended usage.
