### ISSUE TITLE
Replace React-router V3 with latest react-router + react-router-dom

### ISSUE THREAD

**Issue by HenryNguyen5** [MyEtherWallet/MyEtherWallet#231]
Part of the process of migrating to Typescript was also moving to the latest dependencies.
V3 did not actually follow the React paradigm where everything was a component. 
Switching over to V4/V5 will give us updated typing support from TS and real routing components

**Comment by james-prado** [comment]
Reducing the abstraction in the way the router is currently implemented will also be a benefit of switching over to v4. Currently `common/index.ts` renders Root from `common/components/Root`, which then renders Routing from `common/routing`. The routing can be simplified into 1 small component and be a bit more future proof thanks to react-router v4 and how it handles nesting routes.
