### ISSUE TITLE
Token (UBT) suddenly not appearing in SWAP list

### ISSUE THREAD

**Issue by re42** [MyEtherWallet/MyEtherWallet#2322]
![aaa](https://user-images.githubusercontent.com/57980549/80508640-978e7d00-8978-11ea-83dc-e5a2a4702024.png)
- **I'm submitting a ...**

  - [ ] Feature request
  - [x ] Bug report

Is there a reason after the update to 5.6.0 that suddenly UBT no longer shows in the drop down list for SWAP?
It seems to work on kyber.

**Comment by RokScott** [comment]
Same issue with RAE Token on KyberSwap not showing up through the Swap feature on MEW. It seems to be a KyberSwap specific error not showing tokens correctly.

**Comment by re42** [comment]
new version 5.6.1 seems to have UBT back in the swap list now.
@RokScott what about RAE?

**Comment by RokScott** [comment]
No, RAE is still not there, @re42. Does the MEW team have an ETA of when this will be fixed?
