### ISSUE TITLE
Need to remove legacy ETC nodes from MEW

### ISSUE THREAD

**Issue by YazzyYaz** [MyEtherWallet/MyEtherWallet#2331]
- **I'm submitting a ...**

  - [*] Bug report

- **Bug Report**
 One of the ETC nodes is bugging out because the URL has been discontinued. We would like to remove the following file as it's no longer in use: https://github.com/MyEtherWallet/MyEtherWallet/blob/master/src/networks/nodes/etc-ethereumclassiccooperative-parity-classic.js

If that's the only code change needed to move the default to the other ETC node: https://github.com/MyEtherWallet/MyEtherWallet/blob/master/src/networks/nodes/etc-ethereumclassiccooperative-parity.js
then I'm more than happy to submit a PR to delete `etc-ethereumclassiccooperative-parity-classic.js`.

Please let me know about the appropriate next steps and I'll submit a PR for your review.

Best wishes,

Yaz

**Comment by gamalielhere** [comment]
@YazzyYaz is there an announcement about this? Like an article or blogpost?

**Comment by YazzyYaz** [comment]
@gamalielhere None, sorry. It was an old one and there were issues with that node so we moved to Ethercluster: https://www.ethercluster.com

The ETC Cooperative controls both domains. Let me know if you have any more questions.
