### ISSUE TITLE
Phishing Warning

### ISSUE THREAD

**Issue by wmira** [MyEtherWallet/MyEtherWallet#237]
I see that scanner like ethscan tags an address as a phishing address. Is it possible for MEW to warn if an address is flagged in ethscan?.. could help prevent some of the eth getting sent out to scam wallets: https://etherscan.io/address/0x5Bc947356B9a75FdCB92f3eB550682941AcA376B

**Comment by tayvano** [comment]
We do this for ICO addresses. We do not do this for phishing addresses as phishers are not using MyEtherWallet.com to send transactions and people are not willfully sending all their funds to phishing addresses.
