### ISSUE TITLE
Requirement information have to be filled out

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#239]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49827144-773b2f80-fd3d-11e8-98b6-dd7f7ef0e222.png)

![image](https://user-images.githubusercontent.com/31494364/49827494-4ad3e300-fd3e-11e8-85c3-39f29c840988.png)

- **Bug Report**
  - What is the current behavior?
User can leave empty information to continue next step.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
User need to fill out all requirement information and then go to next step, if not, there will be a warning information under the box。

**Comment by hsurf22** [comment]
User can not proceed without providing proper information anyway.
This will be reviewed later.

**Comment by hsurf22** [comment]
Fixed
