### ISSUE TITLE
Delete Speed of Tx input box

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#240]
- **I'm submitting a ...**

  - [x] Feature request
  - [  ] Bug report

![image](https://user-images.githubusercontent.com/31494364/49828100-e1ed6a80-fd3f-11e8-9145-620dbbea3ed5.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Move Speed of Tx input box into "Settings"
  - What are the current issues this feature will solve
Remove the Speed of Tx input box here

**Comment by hsurf22** [comment]
TX speed is hidden for tablet and mobile.
