### ISSUE TITLE
EWT Network

### ISSUE THREAD

**Issue by KaamilW** [MyEtherWallet/MyEtherWallet#2402]
I'm submitting a **Feature request** - new network to be added.

Is it possible to add EWT network to the MEW? I would like to store EWT tokens on my MEW address. I think it should be possible to be implemented quite easily. (I hope).

Reference:
https://medium.com/@HSVGTS/energy-web-wallet-options-to-store-those-precious-ewt-db39adac56d4

**Comment by re42** [comment]
I concur, any ways to do this?  Or do we add the network ourselves?
