### ISSUE TITLE
Bug report: A default or custom token with this address already exists

### ISSUE THREAD

**Issue by zemse** [MyEtherWallet/MyEtherWallet#2407]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

When clicking on `+Custom Tokens` and adding Era Swap Token details:
```
    contract: 0xef1344bdf80bef3ff4428d8becec3eea4a2cf574
    symbol: ES
    decimals 18
```
We get an error: `A default or custom token with this address already exists` .

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Load wallet.
2. Select Custom Tokens
3. Enter contract `0xef1344bdf80bef3ff4428d8becec3eea4a2cf574`, symbol: `ES`, decimals: `18`.
4. Click on Save.

  - What is the expected behavior?
If the token already exists then it should be shown in the balance section. When searched, still it cannot be found. And when added custom token, it should get added regardless of it exists or not (if this looks ok).

  - What is the motivation / use case for changing the behavior?
Users are currently not able to send Era Swap Token from MyEtherWallet. Fixing this would solve the issue.
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
We added a PR to add the token, [MyEtherWallet/ethereum-lists/1491](https://github.com/MyEtherWallet/ethereum-lists/pull/1491). It has been almost a month that the PR merged and recently we got messages from community members regarding the issue. Though the PR checks passed, still if there was any issue in our PR, please let us know what to fix, we can create a new PR with the fix if necessary.

  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.
`/interface`

**Comment by gamalielhere** [comment]
@zemse Thanks for the detailed submission! That should be working now, the token icon will be included in our next release.

**Comment by zemse** [comment]
@gamalielhere Thanks for the fix!
