### ISSUE TITLE
Replace FAQ contents

### ISSUE THREAD

**Issue by gamalielhere** [MyEtherWallet/MyEtherWallet#241]
- **I'm submitting a ...**
  - [x] Devop

**Comment by kvhnuke** [comment]
### How do I create a new wallet?

- MyEtherWallet (MEW) offers three ways to create a new ETH wallet. These are via MEWconnect, Keystore file, or Mnemonic phrase. For more information, click [here](https://kb.myetherwallet.com/getting-started/creating-a-new-wallet-on-myetherwallet.html).

### What is MEWconnect?

- MEWconnect is our companion mobile app for MyEtherWallet. We call it a hardware wallet without all the hardware. Now available for all Android and iOS devices! Read more [here](https://kb.myetherwallet.com/mewconnect/mew-connect-user-guide.html).


### Can MEW work with other wallets?

- MEW supports many different wallet types including hardware wallets, such as the Ledger Nano S or Trezor, and third-party wallets like MetaMask. We are also open for anyone to use their Ethereum wallets with the appropriate information. Read more [here](https://kb.myetherwallet.com/getting-started/accessing-your-new-eth-wallet.html).


### How can I send a transaction?

- MEW lets anyone with a balance of ETH or ERC20 tokens send a transaction, without additional charges. Using the Ethereum blockchain takes gas, which is paid for in ETH, so we recommend having at least .01 ETH to cover around 2 - 3 transactions. Read more [here](https://kb.myetherwallet.com/transactions/how-to-send-transaction.html).

### I forgot my password/private key! What can I do?

- MEW does not offer support to recover or reset passwords/private keys. We always suggest writing down private keys and passwords on physical paper/notebooks for safekeeping. Maybe you saved it on your computer! For ideas on what to look for, read more [here](https://kb.myetherwallet.com/private-keys-passwords/lost-eth-private-key.html).
