### ISSUE TITLE
Smoke Test with Jest

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#245]
- Update enzyme to 3.0+ to support React 16
- Update Jest

The most basic coverage should be first tested, which would be to test if each one of the tabs even render

Along with this, a snapshot test can be done per-tab to make sure any visual changes are tracked: https://facebook.github.io/jest/docs/en/snapshot-testing.html

Afterwards, shallow DOM tests should be used with Enzyme to see that the correct components render

Then, we could test user interactions per-tab up to the generation of a transaction

Later stages can include automatic transaction broadcasting

**Comment by james-prado** [comment]
I'm currently stuck on this issue. I've updated enzyme and jest, configured ts-jest in `jest.config.json`, and written a simple snapshot test, but the tests still fail. 
```
import PNG from './png'
^^^^^^
SyntaxError: Unexpected token import
```
It seems like jest is having a problem with es6 imports, that __*should*__ be taken care of by ts-jest preprocessing typescript.
