### ISSUE TITLE
Navigation bar issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#247]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49834426-32b98f00-fd51-11e8-9400-7e01877d0733.png)
Wrong

![image](https://user-images.githubusercontent.com/31494364/49834651-cb500f00-fd51-11e8-9a43-401359297cef.png)
Right

- **Bug Report**
  - What is the current behavior?
Navigation bar should not display here

  - What is the expected behavior?
 Navigation bar will hide while any popup pop out

**Comment by hsurf22** [comment]
fixed
