### ISSUE TITLE
Customize Gwei  issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#248]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49835138-26cecc80-fd53-11e8-9111-11c10d2fbb41.png)
Wrong

![image](https://user-images.githubusercontent.com/31494364/49835026-de171380-fd52-11e8-80a3-797da0ecdcc4.png)
Right

- **Bug Report**
  - What is the current behavior?
1.) ETH price and US dollar are a fake numbers
2.) Customize input box can be entered letters, and it can be entered while it not be chosen.

  - What is the expected behavior?
1.) While customize Gwei number, ETH price and US dollar should be dynamic numbers.
2.) Customize input box can't be entered letters, and it can't be entered until it's been chosen.

**Comment by SteveMieskoski** [comment]
Closing as this seems resolved.
