### ISSUE TITLE
"Window Blocked" error

### ISSUE THREAD

**Issue by dskvr** [MyEtherWallet/MyEtherWallet#25]
This error has come up with a number of users using Hardware Wallets on contract functions. Upon search for this issue online, I found that the first occurrence of this error I could find online was around **June 14th** [here](https://blog.ethbits.com/2017/06/14/token-upgrade/). There's only a few people who have complained about it, and doesn't seem to have ever been solved. Additionally, it appears to be isolated to MEW, despite my conclusion that because this error message doesn't exist in the repo, it must be coming via RPC. 

Any ideas what this is related to?

**Comment by tayvano** [comment]
When you connect to your TREZOR, you have to allow popups in order to connect. I will update that error message.

**Comment by dskvr** [comment]
Awesome, thanks so much :)

**Comment by miquael** [comment]
i'm getting this issue.  i get a "window blocked" message in MEW.   what exactly i meant by TREZOR must allow popups ... how do i configure TREZOR to adapt?

**Comment by wbobeirne** [comment]
Hey miquael, that depends on which browser you're using. If you're on chrome, see [this article (Allow pop-ups from a site section)](https://support.google.com/chrome/answer/95472?co=GENIE.Platform%3DDesktop&hl=en). If you're on Firefox, see [this article](https://support.mozilla.org/en-US/kb/pop-blocker-settings-exceptions-troubleshooting). If you're not using one of those browsers, you could try to look it up yourself (Though I highly suggest using one of those 2!)
