### ISSUE TITLE
Miss a dropdown arrow

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#251]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49835985-e1f86500-fd55-11e8-8b32-603ee75de407.png)
Wrong

![image](https://user-images.githubusercontent.com/31494364/49836010-fb011600-fd55-11e8-9d85-cd76a012718a.png)
Right

- **Bug Report**
  - What is the current behavior?
User will not understand that icon is a dropdown menu.
 
  - What is the expected behavior?
Add a dropdown menu.

**Comment by hsurf22** [comment]
Fixed
