### ISSUE TITLE
Address input box issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#252]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/49836340-19b3dc80-fd57-11e8-8307-3e2245eab373.png)
Wrong

![image](https://user-images.githubusercontent.com/31494364/49836346-1e789080-fd57-11e8-8ebd-962881e7a294.png)
Right

- **Feature Request**

  - Briefly explain the feature you would like us to implement
1.) Unify address input box UI as a global component, it will easy to use and manage for both developers and users.
2.) Hide "Copy" button if there is a empty input box.

**Comment by hsurf22** [comment]
I'll fix this after the beta release.
