### ISSUE TITLE
User feedback popup

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#254]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/49836944-68fb0c80-fd59-11e8-9e4f-ba1e8f6dd0a0.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Add a small popup while user click"Copy" button, and it stays there for 1.2 second then disappear. 
  - What are the current issues this feature will solve
Improve user experience

**Comment by hsurf22** [comment]
I'll fix this later after merge is done.
