### ISSUE TITLE
MyEtherWallet has misleading/incomplete "print paper wallet" feature when using mnemonic

### ISSUE THREAD

**Issue by epheph** [MyEtherWallet/MyEtherWallet#2546]
- **I'm submitting a ...**

  - [ X] Bug report

- **Bug Report**
  - What is the current behavior?
**When using a mnemonic to access your wallet, going to to the print icon under "address" implies it is showing you a paper wallet that is important to keep safe and allows you to access funds later. In reality, the "private key" section is missing. Anyone relying on this paper wallet to access this address will be very disappointed in the future.**
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
**Use mnemonic to log in, address -> printer icon**
  - What is the expected behavior?
**The print out will have the private key of the address selected**
  - What is the motivation / use case for changing the behavior?
**MEW is implying it is giving you a paper wallet. It is not**
  - Please tell us about your environment:
    - Operating system
    - Browser and version
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.
**/interface**

There should be a "MY PRIVATE KEY" section

![Screen Shot 2020-08-18 at 1 26 34 PM](https://user-images.githubusercontent.com/361654/90562109-8ac7ac00-e156-11ea-9d30-56564d1fa7d8.png)

**Comment by epheph** [comment]
Bump

**Comment by JesseBusman** [comment]
Bump
