### ISSUE TITLE
Relocate a button's location (Send offline page)

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#256]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49838666-9b5c3800-fd60-11e8-9f0a-5a25a054e70a.png)

- **Bug Report**
  - What is the current behavior?
"Update JSON File" button in a wrong position 

  - What is the expected behavior?
Relocate this button to the left bottom.

**Comment by hsurf22** [comment]
I'll fix this after merge is done!

**Comment by hsurf22** [comment]
Upload JSON file button is located next to Clean button on the top.
Move it to the bottom.
