### ISSUE TITLE
Update input box(Send Offline Page) 

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#257]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49838919-b11e2d00-fd61-11e8-87ec-2f17e7d8ab0a.png)

- **Bug Report**
  - What is the current behavior?
This is an old input box
  - What is the expected behavior?
Change this component as a globe one, then we can reuse it in other pages

**Comment by hsurf22** [comment]
I recognize this issue.
Once beta service started, I'll create component for this type of inputs.
