### ISSUE TITLE
Button function are not working

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#259]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49839680-fa23b080-fd64-11e8-8b58-eaf51765a3c7.png)

- **Bug Report**
  - What is the current behavior?
Click those three buttons, and there is no respond
  - What is the expected behavior?
Should be functional buttons.

**Comment by gamalielhere** [comment]
@jackhuangusa print is still missing the design for how a printed address should look. We should probably talk about this with @kvhnuke

**Comment by jackhuangusa** [comment]
Oh, we have the paper wallet in Zeplin
