### ISSUE TITLE
Can't select custom HD Derivation Path

### ISSUE THREAD

**Issue by Drive4ik** [MyEtherWallet/MyEtherWallet#2611]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
I can't select custom HD Derivation Path when connect my BitBox02 Multi Edition.
When choosing a path, the "Network and Address" window closes and an error appears:

![Screenshot_1](https://user-images.githubusercontent.com/7843031/95073100-f53ba800-0714-11eb-9ba6-162efe2283bc.png)
![Screenshot_2](https://user-images.githubusercontent.com/7843031/95073106-f66cd500-0714-11eb-92d5-cddfb31fcbe3.png)

**Comment by vassilyvv** [comment]
I think my issue is close to this one. I would like to access all funds from all the wallets attached to my mnemonic seed. FOR E.g. I have funds on my 44'/60'/267 but to access them I must to manually create 267 addresses which are impossible
