### ISSUE TITLE
Dropdown menu UI display issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#263]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49842346-ffd2c380-fd6f-11e8-8545-86bec2844b75.png)

![image](https://user-images.githubusercontent.com/31494364/49842488-9acb9d80-fd70-11e8-8ee4-4dc9fd73e32e.png)

- **Bug Report**
  - What is the current behavior?
Dropdown menu UI display issue
  - What is the expected behavior?
Modify as design layout

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/tree/ui/interface-fix-notification
