### ISSUE TITLE
JSON file wallet transactions not getting broadcast to ROP network

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#265]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
    - When using a JSON wallet the transaction is not broadcast to the network.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
    - Open a JSON file wallet
    - Send a transaction 
  - What is the expected behavior?
    - The transaction is broadcast to the network and the transaction receipt is returned.

**Comment by kvhnuke** [comment]
re syncing `ropsten` with latest geth `1.8.20`

**Comment by SteveMieskoski** [comment]
closing as this no longer appears to be an issue.
