### ISSUE TITLE
Confirm send message popup layout issue

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#267]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49898420-db2d2900-fe0d-11e8-8c3c-28dc0c5df400.png)

- **Bug Report**
  - What is the current behavior?
Diffident layout with design 
  - What is the expected behavior?
Change layout as design

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/commit/b2d4c0beb21c07930f79a470e309fcfe0a87752e

fixed
