### ISSUE TITLE
Move speed of Tx to Settings

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#270]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/49907594-b0ea6400-fe2b-11e8-93e2-041f4be7a8d8.png)

- **Bug Report**
  - What is the current behavior?
In Deploy Contract page, speed of Tx should not be there
  - What is the expected behavior?
Move speed of Tx to Settings

**Comment by hsurf22** [comment]
This has been moved.
