### ISSUE TITLE
Little UI / CSS Issues

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#270]
- [x] 1. After clicking the "verify" button, the active state has the text white, meaning you can't read it:

![screen shot 2017-10-06 at 10 19 43 am](https://user-images.githubusercontent.com/7924827/31290070-076347b2-aa80-11e7-8da3-74a6c70570b8.jpg)

- [x] 2. When you send 2 transactions back to back, it's hard to tell which one is the new one. Perhaps fade out previous one `opacity: .8;` `opacity: .6; `... to differentiate

![screen shot 2017-10-06 at 10 24 14 am](https://user-images.githubusercontent.com/7924827/31290233-892d239e-aa80-11e7-9883-9a767159cb9e.jpg)

- [x] 3. When using Ledger, you press generate and a spinner shows up (YAY!). If possible, let's add a message that says "Please confirm transaction on your hardware wallet" next to it. Can be super small. 

![screen shot 2017-11-09 at 10 03 44 pm](https://user-images.githubusercontent.com/7924827/32645042-142b4ea6-c59a-11e7-8c0a-7865d2212ebb.jpg)

**Comment by james-prado** [comment]
I've made a branch [here](https://github.com/james-prado/MyEtherWallet/tree/css-issue) to fix the issue. I've added animations on notifications to make it clear to the user which notification is new and which is old. [React-transition-group](https://github.com/reactjs/react-transition-group) seems to be one of the better animation libraries to react, it makes animations before dismount very easy, however I've found and issue using it with redux so I've opened an issue [here](https://github.com/reactjs/react-transition-group/issues/231#issuecomment-337713443) and am awaiting a response.

This branch also fixes the white text issue.

**Comment by james-prado** [comment]
Ok, turns out using the notification array index as a key is VERY BAD and messes up react displays data.

**Comment by james-prado** [comment]
Closed by pr https://github.com/MyEtherWallet/MyEtherWallet/pull/305

**Comment by james-prado** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/pull/305 only solves 2/3 of the issues, re-opening to fix part 3.
