### ISSUE TITLE
Blank Page on Chromium-Browser

### ISSUE THREAD

**Issue by FomaFomitch** [MyEtherWallet/MyEtherWallet#2706]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[X] Bug report

* **Bug Report**
  * What is the current behavior?

**I'm trying to use MEW on a offline Raspberry Pi. I can open MEW until version 5.2.X, but since 5.3.0 I can't use it anymore. When I launch "index.html" on my chromium browser, all I got is blank white window, nothing.**

  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  * What is the expected behavior?
  * What is the motivation / use case for changing the behavior?
  * Please tell us about your environment:
    * Operating system
**Raspberry Pi.**
    * Browser and version
**Chromium Browser V58 and MyEtherWallet V5.3+**
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**If some dependency changed on MEW v5.3.0 is it possible to add them so I can the wallet ?
Also, is it possible to make a "minimalist" MEW wallet with only create-wallet + sign offline transaction ?**

**Comment by movraxrsp** [comment]
Hi, Foma. I am working on a "minimalist" MEW wallet with only create-wallet + sign offline transaction tool.
