### ISSUE TITLE
Audit Error Handling

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#272]
Determine all instances of unhandled errors, especially network requests.

Known:
 - RpcNode currently does not handle errors, and they can bubble up in unexpected ways. `rpc-network-catch` contains preliminary work on fixing these.

**Comment by dternyak** [comment]
Related to https://github.com/MyEtherWallet/MyEtherWallet/issues/160

**Comment by eddiewang** [comment]
Related to #302 and #226

**Comment by eddiewang** [comment]
#372
