### ISSUE TITLE
Chromium can't open the built application from the filesystem because Chromium refuses to confirm or deny subresource integrity hash correctness for files on the local filesystem

### ISSUE THREAD

**Issue by interfect** [MyEtherWallet/MyEtherWallet#2749]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[X] Bug report

* **Bug Report**
  * What is the current behavior?
  
The README says that "After this step succeeds, you can stop and use the offline version by opening the index file from the dist folder with your preferred browser.". This isn't true if that browser is Chromium; instead you get something like this in the console and a blank page:

```
Subresource Integrity: The resource 'file:///home/user/workspace/MyEtherWallet/dist/css/vendors.41684deb.css' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
index.html:1 Subresource Integrity: The resource 'file:///home/user/workspace/MyEtherWallet/dist/css/app.a228decc.css' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
index.html:1 Subresource Integrity: The resource 'file:///home/user/workspace/MyEtherWallet/dist/js/vendors.0c057a20.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
index.html:1 Subresource Integrity: The resource 'file:///home/user/workspace/MyEtherWallet/dist/js/app.d8ffdcf6.js' has an integrity attribute, but the resource requires the request to be CORS enabled to check the integrity, and it is not. The resource has been blocked because the integrity cannot be enforced.
```

Presumably Chromium doesn't want you to be able to poll all the possible hashes of a file via setting the subresource integrity and seeing if it loaded or not, if you can't just open it. But for `file://` you can't just open anything.

  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

1. Build MEW 79d730defff2d1dc6159fa6b9980b3e25b76a3e9 after fixing its outdated package.json dependencies and passing a higher Node memory limit to the build (`export NODE_OPTIONS=--max_old_space_size=8192`).
2. Open index.html it in Chromium 87.0.4280.88

  * What is the expected behavior?

MEW should load. Or, the documentation should say it won't work form the filesystem and you need to use `npm start` all the time.

  * What is the motivation / use case for changing the behavior?

The current behavior conflicts with the documentation.

  * Please tell us about your environment:
    * Operating system: Ubuntu 20.04
    * Browser and version: Chromium 87.0.4280.88
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc): See above for console log
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.: `index.html`

**Comment by interfect** [comment]
This may be related to https://github.com/MyEtherWallet/MyEtherWallet/issues/2706

**Comment by FomaFomitch** [comment]
Yes, starting at version MEW 5.3.0 I think.

**Comment by superclarkk** [comment]
Is this how the maintainers solve issues - automatically closing any that they've not been active on? What's the point of raising them, then?

Two and half years later, I'm stuck with this issue too. See #4562

npm ci doesn't work either.

**Comment by nicolasochem** [comment]
Worked for me on Linux with most recent version of MEW:

Open terminal. Go to download location, then do:

```
python3 -m http.server 8000
```

On your browser, navigate to http://localhost:8000
