### ISSUE TITLE
Blank page in some Safari browsers

### ISSUE THREAD

**Issue by happyastronaut** [MyEtherWallet/MyEtherWallet#2775]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[x] Bug report

* **Bug Report**
  * What is the current behavior?
  **If you try to open MEW in older Safari browsers like iOS 12, you will see a blank page. Same issue with MacOS version.**
  * Please tell us about your environment:
    * Operating system
     MacOS / iOS 12
    * Browser and version
    mobile Safari 12 (iOS 12)
MyEtherWallet v5.7.18

**Comment by gamalielhere** [comment]
This should be fixed now. Do reopen if the issue occurs.
