### ISSUE TITLE
I've tried on multiple offline browsers. Firefox doesn't load and Chrome will slugishly 

### ISSUE THREAD

**Issue by TinFury** [MyEtherWallet/MyEtherWallet#2777]
* **I'm submitting a bug**

Loading mew offline on linux I was not able to load mew with firefox. Connecting online and installing chrome the offline website comes up. I generate the keystore file and access the wallet offline. Trying to print the paper wallet keypair for cold storage generates this error.

'Failed to execute ToDataUrl'
on 'HTMLCanvasElement': Tainted canvases may not be exported.

It's hard to imagine that Etherium is popular at all when this is the only cold storage method on the internet and it doesn't work. Makes me think everything is just speculative.

WS

**Comment by okipol88** [comment]
On Linux offline (MEW v5.7.18 with:

Firefox Quantum (60) I cannot load the page with error:
`ReferenceError: BigInt is not defined` in vendors.ecbba207.js.484:57149.

Chromium 71 still blank page: `Uncaught DOMException: Failed to read 'localStorage' from Window Access is denied for this document.` in vendors.ecbba207.js:460.

Disappointing as  MEW v3.28 works ...

**Comment by okipol88** [comment]
Steps to reproduce:
Download Debian 9.5 from https://www.osboxes.org/debian/ and run on virtual machine.
Download MEW v5.7.18 release.
Run Debian 9.5 without network adapter/internet.

Outcome beneath:

![image](https://user-images.githubusercontent.com/8424432/105641287-6ac5b280-5e83-11eb-98cb-9c10f82234a7.png)

**Comment by okipol88** [comment]
@TinFury Just confirmed its working for MEW v5.2.0.

**Comment by TinFury** [comment]
@okipol88 Ok thanks man will try.

**Comment by zerocomrade** [comment]
Hi I'm getting similar issues with v5.7.19

I've tried multiple browsers and devices. Can anyone verify this?

**Comment by azagniotov** [comment]
Bump
