### ISSUE TITLE
Identify Optional Inputs & Advanced settings

### ISSUE THREAD

**Issue by james-prado** [MyEtherWallet/MyEtherWallet#281]
Currently the only way to identify optional inputs is through intuition. Optional inputs should be identified by their design. For example, refer to the optional and required text inputs in Google's material design guidelines https://material.io/guidelines/components/text-fields.html#text-fields-layout

Additionally, hiding / separating advanced settings from users might lead to less confusion when filling out complex forms. For example, defining custom nonces in transactions is an advanced setting 95% of users don't use, and can easily be moved under advanced settings.

The priority of this relative to v4 beta is low, just something to keep in mind for the future.

**Comment by dternyak** [comment]
Closing for now - issue is stale. The issues described are certainly true, however UX work in the pipeline should address this.
