### ISSUE TITLE
Nonce Failure, NaN when should be 0

### ISSUE THREAD

**Issue by 0x90909090** [MyEtherWallet/MyEtherWallet#2906]
* **I'm submitting a Bug report **
* **Bug Report**
  * What is the current behavior?
     During the offline transaction process, when the nonce is 0, the signature that is produced is incorrect. It produces NaN for the nonce value instead of 0.
  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
     Follow the steps outlined in the documentation with an account that has nonce 0. You will see the signature produces a NaN value for the nonce even though the JSON file has the key/value pair "nonce": "0x00".
  * What is the expected behavior?
     The signature should correspond to a transaction where the the nonce value is 0 not NaN.
  * What is the motivation / use case for changing the behavior?
     Transactions that are not risky to transmit with a nonce value of NaN when it should be 0.
  * Please tell us about your environment:
     Windows 10, latest updates. Latest version of Chrome.
   * Browser and version
      Chrome 89.0.4389.82
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
    I haven't tried to debug the code.
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.
     The JSON file generated for the signed transaction has the key/value pair "nonce": "0x00", but the offline helper on the online website interprets it as NaN not as the integer 0.

**Comment by 0x90909090** [comment]
anybody want to help with this?
when mew is running offline, where is the signature generated in the src?

in the zip file extraction, there's an event listener, i think, that i can break at line 847 in file vendors.1ae75784.js, but where does that correspond to this code base?

**Comment by 0x90909090** [comment]
Can someone please shed some light on this?
It is horrible that a transaction cannot be sent with a nonce 0 because the signature created corresponds to nonce NaN.

Just point me in the right direction.

I'll fix it.

But I am not familiar with this giant rather obfuscated code base in the zip file for the offline version of MEW.

**Comment by 0x90909090** [comment]
If you need more info, if I'm not being clear, then please let me know.

I want to fix this so that I can send an offline transaction with nonce 0.

**Comment by 0x90909090** [comment]
Is this related?
https://github.com/MyEtherWallet/MyEtherWallet/blob/b8556f33277fd28b75728bbfeaf6e1f6838a6c2d/src/layouts/SendOfflineHelper/SendOfflineHelper.vue#L650

**Comment by 0x90909090** [comment]
or this:

https://github.com/MyEtherWallet/MyEtherWallet/blob/b8556f33277fd28b75728bbfeaf6e1f6838a6c2d/src/layouts/SendOfflineHelper/SendOfflineHelper.vue#L590

**Comment by 0x90909090** [comment]
Could this return NaN?

https://github.com/MyEtherWallet/MyEtherWallet/blob/b8556f33277fd28b75728bbfeaf6e1f6838a6c2d/src/layouts/SendOfflineHelper/SendOfflineHelper.vue#L590

**Comment by 0x90909090** [comment]
Here's what the signed transaction from the offline MEW produces when it is uploaded to the online MEW.

I do not want to send a transaction with a NaN nonce value when it should be 0.

![image](https://user-images.githubusercontent.com/64245494/111229411-17c6cc80-85a3-11eb-85a8-35ab9e3ea14c.png)

**Comment by 0x90909090** [comment]
Let me know if you want to work on it with me.

Thanks!

**Comment by gamalielhere** [comment]
@0x90909090 can you try it out here? it should set it to 0 instead of NaN https://www.mewbuilds.com/build/1f4355a6c35e15d9ef0bf0f6052954541d7d5aef/index.html

**Comment by 0x90909090** [comment]
thanks, checking now

**Comment by 0x90909090** [comment]
Yes, the nonce is 0 now instead of NaN. Thank you.

**Comment by joachimts** [comment]
Today I am also heaving problems with a signed transaction json file loaded into the “offline helper” tool on my online computer. I am getting the following error: “number can only safely store up to 53 bits”.
The Ether value in the transaction details section is zero although on the offline computer I have set 1 Ether.
The version on my offline computer did not change.
Could my problem be related to this issue?

**Comment by gamalielhere** [comment]
@joachimts what version is your offline computer? also can you try using incognito for your online computer and see if that works?

**Comment by joachimts** [comment]
Thanks for you quick answer.
My offline computer uses Myetherwallet-v5.7.19-hotfix.1
I also tried v5.7.24 on the offline computer with the same result.

Unfortunately using icognito mode on the online computer also does not change anything.

Four days ago I did the last offline created Ether transaction which worked. Then I used v5.7.19-hotfix.1 on my offline computer.

**Comment by 0x90909090** [comment]
@gamalielhere
can you tell me where the fix was for the NaN/0 nonce problem?

And I'd like to contribute to this repo, for example, with making a better offline version that avoids timeouts and other errors caused by networking calls that are obviously going to fail.

Thanks again for the nonce fix.

**Comment by gamalielhere** [comment]
@joachimts can you contact our support team at support@myetherwallet.com they should be able to debug this for your further.

**Comment by gamalielhere** [comment]
@0x90909090 here's a direct link to the fix. I'm closing this issue as this is resolved. https://github.com/MyEtherWallet/MyEtherWallet/pull/2907/files#diff-495edf8f2f0632fc3a7b7d821b7d86f67ee47443ae088d031f24bb7478f25131R593

**Comment by 0x90909090** [comment]
@gamalielhere
thanks again

**Comment by 0x90909090** [comment]
@gamalielhere
so i was on the correct line
https://github.com/MyEtherWallet/MyEtherWallet/issues/2906#issuecomment-799789586

simple fix
i'll review the code base more
and hopefully have time to contribute fixes
