### ISSUE TITLE
Multi Problems after update with sending offline

### ISSUE THREAD

**Issue by btcking8080** [MyEtherWallet/MyEtherWallet#2913]
Unable to send offline after updating MEW... 

Problem one : No zero value integer ( eth value sent amount )  not sending any amount of eth even after entering the correct amount within offline helper

Problem two: keep getting error 53 bits when copying the signed transaction data from offline helper to online site...

browser Firefox

**Comment by btcking8080** [comment]
error 53 bits

**Comment by smiletracer** [comment]
Yes this is completely broken in the current release v5.7.24. I commented on the specific commit that broke things and hopefully they'll get that patched soon. In the meantime, download the previous release "MyEtherWallet v5.7.23-hotfix.1" which seems to work without giving the error "Number can only safely store up to 53 bits", and shows correct values in the transaction details.

**Comment by btcking8080** [comment]
Thanks for the update, I'm learning how to use web3 and geth to handle my
transactions myself. But there software used to work nice for off line
transactions. I'll try using the hotfix and see if that works and report
back asap

**Comment by gamalielhere** [comment]
Fixed as of 5.7.25
