### ISSUE TITLE
ETH Transaction Failed

### ISSUE THREAD

**Issue by wenny806** [MyEtherWallet/MyEtherWallet#2918]
Hi
My Eth-Transaction failed. 
I have no Transaction Hash 

"Your Transaction with hash failed with error: Error Returned error; kafka server; in the middle of a leadership election, there is currently no leader for...

 What is the problem?

Thanks

**Comment by abonec** [comment]
Same here. Is this project is still functioning?

**Comment by btcking8080** [comment]
I'm having troubles to since the last couple updates, is this project still alive? does anyone know of another offline wallet that works

**Comment by hollycrypto** [comment]
I also have problems with myetherwallet, I've contact info@myetherwallet.com and support@myetherwallet.com, I never get reply from them, 2 weeks passed.
Can someone tell me how to contact their support?

**Comment by smiletracer** [comment]
Yes this is completely broken in the current release  v5.7.24. I commented on the specific commit that broke things and hopefully they'll get that patched soon. In the meantime, download the previous release "MyEtherWallet v5.7.23-hotfix.1" which seems to work without giving the error "Number can only safely store up to 53 bits", and shows correct values in the transaction details.

**Comment by btcking8080** [comment]
Thanks for the update, I'm learning how to use web3 and geth to handle my
transactions myself. But there software used to work nice for off line
transactions. I'll try using the hotfix and see if that works and report
back asap

**Comment by gamalielhere** [comment]
@wenny806 this should be resolved now. Try sending your tx again. Closing this as fixed, but do reopen if it still persists
