### ISSUE TITLE
Wallet, balance and transaction view not available when I log in (logged in with Private key)

### ISSUE THREAD

**Issue by dumi909** [MyEtherWallet/MyEtherWallet#2936]
* **I'm submitting a ...**

  * \[ ] Bug report

* **Bug Report**
  * What is the current behavior? - I log in and all I see is the home screen that's present before I log in.
  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem - 
 
![MEW Screensot](https://user-images.githubusercontent.com/42893115/112682287-d1595380-8e67-11eb-9de0-ea17f7814dd3.png)

  * What is the expected behavior? I should be able to see my wallet/balance and be able to transact.
  
  * What is the motivation / use case for changing the behavior? - Looking to transact

  * Please tell us about your environment:
    * Operating system - Microsoft

    * Browser and version - Chrome

**Comment by gamalielhere** [comment]
@dumi909 can you open your browser console and see whether there's any error?
