### ISSUE TITLE
Custom data for "Send Offline" on BSC

### ISSUE THREAD

**Issue by domob1812** [MyEtherWallet/MyEtherWallet#2939]
* **I'm submitting a ...**

  * \[x] Feature request
  * \[ ] Bug report

* **Feature Request**

  * I'm using MEW in offline mode for my cold wallet
  * With the "Send Offline" feature, I can easily sign arbitrary transactions on mainnet, including contract calls (with custom "Data")
  * When I select BSC as network, the "Data" field is disabled, and I cannot use "Send Offline" for contract calls (on version v5.7.25)
  * Other sidechains (e.g. XDAI) seem to work
  * It would be very helpful (particularly with the current push for sidechains) to be able to use my offline wallet also to do contract calls with transaction data on BSC

**Comment by gamalielhere** [comment]
@domob1812 will be fixed on an upcoming release #2941

**Comment by domob1812** [comment]
Thanks for the fast response!  Looking forward to it.

**Comment by gamalielhere** [comment]
Closing as this has been released
