### ISSUE TITLE
csp headers not updated with release

### ISSUE THREAD

**Issue by aerth** [MyEtherWallet/MyEtherWallet#2958]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[x] Bug report

* **Bug Report**
  * What is the current behavior?
 
headers of /interface/dashboard
![image](https://user-images.githubusercontent.com/6263105/113247536-18808380-9270-11eb-9a1c-1d3d0d798e26.png)

CSP violation because the node is not in the allow list, prevents connecting to the node
![image](https://user-images.githubusercontent.com/6263105/113247970-e6235600-9270-11eb-843a-a9cda8b1df1f.png)

  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Run this command to view the header

`curl -si https://www.myetherwallet.com | grep content-s`

compare to `vueConfig/connections.js` ([this part here](https://github.com/MyEtherWallet/MyEtherWallet/blob/master/vueConfig/connections.js#L81-L84))

  * What is the expected behavior?
 connect to node and display current block number. 

 btw, running locally worked (because it uses the `vueConfig/connections.js` file ?)

  * What is the motivation / use case for changing the behavior?
  * Please tell us about your environment:
    * Operating system
    * Browser and version
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.
 response headers of /interface/dashboard

---------------------------

can close this if known

**Comment by gamalielhere** [comment]
Will be fixed today thanks for opening the issue @aerth
