### ISSUE TITLE
Chrome 89, CORS network error

### ISSUE THREAD

**Issue by llj098** [MyEtherWallet/MyEtherWallet#2971]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[X] Bug report

* **Bug Report**
  * What is the current behavior?
  
use bsc chain, always show 'network error', the block number, the balance cannot be loaded

  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

create a bsc wallet, in the index page, the page shows 'network error'..

  * What is the expected behavior?

all the data loads correctly.

  * Please tell us about your environment:
    * Operating system
macos X big sur

    * Browser and version

chrome 89

![photo_2021-04-02_09-03-33](https://user-images.githubusercontent.com/139195/113369206-4d392b80-9393-11eb-81b7-9189238eccec.jpg)
![photo_2021-04-02_09-03-36](https://user-images.githubusercontent.com/139195/113369208-51fddf80-9393-11eb-94d0-3df609166e7e.jpg)

**Comment by llj098** [comment]
firefox 86 has the same issue

**Comment by aerth** [comment]
This issue can be fixed on the bsc node's side by adding a `Access-Control-Allow-Origin` header (such as `*`)
