### ISSUE TITLE
Send + infra

### ISSUE THREAD

**Issue by crptm** [MyEtherWallet/MyEtherWallet#30]
#### Blockers 
- [x] To Address https://github.com/MyEtherWallet/MyEtherWallet/issues/93
- [x] node switcher https://github.com/MyEtherWallet/MyEtherWallet/issues/89
- [x] modals https://github.com/MyEtherWallet/MyEtherWallet/issues/85
#### Send infra
- [x] Query balances
- [x] BalanceDrtv
- [x] Estimate gas
- [x] Sign tx
- [x] resolve ens
- [ ] nonce/balance refresh
- [x] broadcast tx
- [ ] "Add custom token" should support ENS names in the address field
- [x] Amount
- [x] ETH vs Tokens
- [x] Gas Limit
- [x] Gas Price
- [x] Nonce
- [x] Data ((n/a for tokens))
- [x] "Send Entire Balance" - Calculates total balance - gas price and auto fills in amount (n/a for tokens)
- [x] Increase nonce by 1 manually after they send a transaction (not sure if still necessary?)

### Token Sale Infra
- [ ] Array / Object that allows us to set a pre-defined gas limit, data, and display message if a user enters a specific address

### Validations
- [x] Amount they are sending is positive number
- [x] Amount they are sending is < current balance
- [x] Data is valid hex
- [x] Gas price is positive number
- [x] (Low Priority) Show estimated TX fee in ETH?
- [ ] Contract wouldn't throw error (via estimate gas)
- [ ] If estimated gas > 4M, set gas to -1 and show error "This contract would use all available gas which means the contract is going to throw an error." or something. There should be an error there

### URI
- [x] Accept URI parameters to fill in fields
- [x] Show message if URI is present

**Comment by MIGUELWAXX** [comment]
cheers

**Comment by wbobeirne** [comment]
Much of this was done in #118 and #108. The main outstanding tasks are ENS and broadcasting. I feel like the more important of the 2 for the soft launch will be the broadcasting. @crptm is this something you might have time for pre-launch? It's not something I have a lot of experience with, so I wouldn't mind handing it off so that I can work on more of the styling changes before launch.

**Comment by wbobeirne** [comment]
Reassigning to dternyak as he's handling broadcasting of transactions.

**Comment by dternyak** [comment]
Closing, separate issues can handle the rest.
