### ISSUE TITLE
Replace temporary notice to check if hardware wallet is attached to a final version

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#300]
- **I'm submitting a ...**

  - [ ] Feature request
  - [X] Bug report

- **Bug Report**
  - What is the current behavior?
    - If hardware wallet is not attached the notice is a placeholder
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
    - attempt to use a hardware wallet without the wallet connected
  - What is the expected behavior?
    - the notice should be styled and use informative wording
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
Ubuntu 16.04
    - Browser and version
Chrome Version 70.0.3538.110

**Comment by gamalielhere** [comment]
fixed with #309, wording might be different
