### ISSUE TITLE
Avalanche login with Ledger isn't working

### ISSUE THREAD

**Issue by jpop32** [MyEtherWallet/MyEtherWallet#3019]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[ x] Bug report

* **Bug Report**

Trying to log into the Avalanche C-Chain network wallet, with Avalanche app v0.4.2 installed and running on the Ledger Nano S:

<img width="506" alt="Screenshot 2021-04-12 at 12 02 50" src="https://user-images.githubusercontent.com/6398640/114378071-9f463200-9b87-11eb-9959-f117a1b9a46e.png">

Instead of a successful login, there is an error message, and the login fails.

<img width="335" alt="Screenshot 2021-04-12 at 11 39 09" src="https://user-images.githubusercontent.com/6398640/114377920-7756ce80-9b87-11eb-859f-42282769b029.png">

Expected behavior is for the Ledger to ask for confirmation to provide the public key. Same functionality with same Avalanche app on Ledger works with Avalanche web wallet, Metamask or MyCrypto.com.

The problem is not in the network configuration, because if I try to log in using the passphrase, I get logged into the correct Avalanche wallet, see correct balances of AVAX and ERC-20s.

Furthermore, if I select Ethereum app on the same Ledger device (so it uses the same private keys, and Avlanche uses the same HD path and signing scheme) and try to log in to Avalanche network, it works and shows me the correct Avalanche wallet:

<img width="527" alt="Screenshot 2021-04-12 at 12 22 50" src="https://user-images.githubusercontent.com/6398640/114379994-d584b100-9b89-11eb-80b0-e43d45a172e5.png">

So I guess the problem is in expecting the wrong app on the Ledger.

Tried and saw the same behavior on Chrome running on MacOS, and Chrome running on Windows 10, both with latest versions on Chrome.

**Comment by gamalielhere** [comment]
should be fixed as of v5.7.28

**Comment by jpop32** [comment]
I can confirm, it works now, thanks.
