### ISSUE TITLE
notification "insufficient funds" while sufficient funds available 

### ISSUE THREAD

**Issue by IsaBerenos** [MyEtherWallet/MyEtherWallet#3020]
hello i would like some assistance because i want to sell my 0.2991 ETH to my broker and cash in, but I keep getting the notification "insufficient funds" while I believe I have enough funds?
And I dont really understand "github"
I hope to receive news on how to fix this 
thankyou very much in advance
(i am sending from my ether wallet and to a broker)

**Comment by gamalielhere** [comment]
@IsaBerenos please contact our support team at support@myetherwallet.com
