### ISSUE TITLE
EIP-681 QR Scanning leads to lost funds - funds are sent to the contract address

### ISSUE THREAD

**Issue by juscamarena** [MyEtherWallet/MyEtherWallet#3056]
* **I'm submitting a ...**
=
  * \[x] Bug report

* **Feature Request**

* **Bug Report**
  * What is the current behavior?
  
  Scan a EIP-618 QR codes, MEW scans and doesn't correctly handle contract interactions, an example being erc20 transfer.
  Example: ethereum:pay-0xdAC17F958D2ee523a2206206994597C13D831ec7@1/transfer?address=0x07B63eC1EceEd4f6407C6E5deE518FEd78368DAf&uint256=2e7&gasPrice=93
  
  * What is the expected behavior?
 
  Correctly, following EIP-618 as other wallets do.
  
  Correctly supporting the standard, not just partially leading to users losing funds.
  * What is the motivation / use case for changing the behavior?
Prevent fund loss.

**Comment by ClementRouquier** [comment]
4 years later..... still an issue!
