### ISSUE TITLE
@/_generated/partners/dependencies not found

### ISSUE THREAD

**Issue by ottpeter** [MyEtherWallet/MyEtherWallet#3066]
* **I'm submitting a ...**

  * \[ ] Bug report

When I run "npm run start:ci" I get this error:
'''
 ERROR  Failed to compile with 3 errors                                                       8:00:39 PM

These dependencies were not found:

* @/_generated/partners/EthereumTokens.json in ./src/partners/partnersConfig/index.js
* @/_generated/partners/OtherCoins.json in ./src/partners/partnersConfig/index.js
* @/_generated/partners/currencies.json in ./src/partners/changelly/config/index.js

To install them, you can run: npm install --save @/_generated/partners/EthereumTokens.json @/_generated/partners/OtherCoins.json @/_generated/partners/currencies.json
'''

node -v
v10.24.1
npm -v
6.14.12

**Comment by brandnewx** [comment]
I'm having the same issue.

**Comment by brandnewx** [comment]
Here's the temporary workaround:

In compileBaseSwapOptions.js file, comment out the following lines:

```
      // const tokenList = await this.get(
      //   'https://www.coingecko.com/tokens_list/uniswap/defi_100/v_0_0_0.json'
      // );
```

**Comment by kvhnuke** [comment]
please try again with the new codebase
