### ISSUE TITLE
Convert ABI to HTML interface

### ISSUE THREAD

**Issue by Macha-orange** [MyEtherWallet/MyEtherWallet#3099]
Hello,

Is there a way to get the code from "INTERACT WITH CONTRACT" when we paste ABI and get HTML code with button and arguments ?

I found something similar like this https://abi.hashex.org/ but would like to implement it to my project but I don't know how to get code from here.

**Comment by gamalielhere** [comment]
@Macha-orange what do you mean get the html code button and arguments?

**Comment by Macha-orange** [comment]
Hello @gamalielhere 

I mean what JS code can :
- Take an ABI contract as INPUT
- Then read into this ABI data and construct a user interface for each functions.

Example like this website : https://abi.hashex.org/

If you put an ABI from a smart contract inside and create an interface.
For a "function call" there will be no input, only read button.
For a function with input 1 "address" and input 2 "uint32" it will create an HTML interface with two input etc.

MyEtherWallet has this feature on pannel "DELPLOY A CONTRACT" and "INTERACT WITH CONTRACT" when you paste contract address/ABI.

But I can't find this code even if it's open source!

**Comment by gamalielhere** [comment]
Here's the source for Interact with contract: https://github.com/MyEtherWallet/MyEtherWallet/blob/master/src/layouts/InterfaceLayout/containers/InteractWithContractContainer/InteractWithContractContainer.vue

Here's the source for Deploy contract: https://github.com/MyEtherWallet/MyEtherWallet/blob/master/src/layouts/InterfaceLayout/containers/DeployContractContainer/DeployContractContainer.vue

Let me know if you have questions

**Comment by Macha-orange** [comment]
Thank you ! I don't know VUE.JS yet but will look forward to it.
