### ISSUE TITLE
Build fails on ubuntu 18.04, issue with node-sass compatibility

### ISSUE THREAD

**Issue by Toporin** [MyEtherWallet/MyEtherWallet#3117]
* **I'm submitting a ...**
  * \[x] Bug report

* **Bug Report**
  * What is the current behavior?
Build fails. The issue may be related to module incompatibilities

  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  
node -v
v10.18.1
npm -v
6.13.4

npm i
npm run build

returns following errors:
`
ERROR: Update luxon from 1.26.0 to 1.27.0. Released: 2021-05-14T04:06:23.480Z
ERROR: Update walletlink from 2.1.0 to 2.1.3. Released: 2021-05-12T21:28:45.525Z
ERROR: Update node-sass from 5.0.0 to 6.0.0. Released: 2021-05-08T15:34:55.950Z
ERROR: Update prettier from 2.2.1 to 2.3.0. Released: 2021-05-09T21:01:40.825Z
ERROR: Update trezor-connect from 8.1.26 to 8.1.27. Released: 2021-05-13T10:44:01.706Z
`
After updating the modules with their recommended version, I get a very long list of errors such as:
`
error  in ./src/components/StandardDropdown/StandardDropdown.vue?vue&type=style&index=0&id=1b964ec6&lang=scss&scoped=true&

Module build failed (from ./node_modules/mini-css-extract-plugin/dist/loader.js):
ModuleError: Module Error (from ./node_modules/sass-loader/dist/cjs.js):
Node Sass version 6.0.0 is incompatible with ^4.0.0 || ^5.0.0.
`
**So it appears that node-sass 5.0.0 is outdated but v6.0.0 is incompatible with many modules.**

  * What is the expected behavior?
MEW should build without error

  * Please tell us about your environment:
    * Operating system => Ubuntu 18.04.5 LTS
    * Browser and version => N/A
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by kvhnuke** [comment]
you have to change the package.json version and npm install
