### ISSUE TITLE
Different language missing translation contents

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#314]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/50524022-39057600-0a88-11e9-8c95-309e5c6de2cd.png)

- **Bug Report**
  - What is the current behavior?
Different language missing translation contents

**Comment by gamalielhere** [comment]
You need to approve them on crowdin
