### ISSUE TITLE
Chain ID of MATIC network is set incorrectly in network settings.

### ISSUE THREAD

**Issue by ilkerdeniz** [MyEtherWallet/MyEtherWallet#3149]
* **I'm submitting a ...**

  * \[X] Bug report

* **Bug Report**
  * What is the current behavior?
  In the network settings the chainID of MATIC network is set as 42. This is the chainID of Kovan testnet.

  * What is the expected behavior?
  Correct chainID for MATIC network is 137, as seen from their official docs;
 https://docs.matic.network/docs/develop/network-details/network/

**Comment by kvhnuke** [comment]
will be fixed with v6 release
