### ISSUE TITLE
Update Ledger Help Links around site (search "groove")

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#321]
**On the Ledger Wallet connection page these two links are wrong**

How to use MyEtherWallet with your Nano S 

How to secure your tokens with your Nano S 

**Please replace them with**

https://ledger.zendesk.com/hc/en-us/articles/115005200009-How-to-use-MyEtherWallet-with-Ledger

https://ledger.zendesk.com/hc/en-us/articles/115005161945-How-to-secure-your-ETH-tokens-Augur-REP-with-your-Nano-S

**Comment by dternyak** [comment]
No longer an issue.
