### ISSUE TITLE
npm run build fails with Aborted (core dumped)

### ISSUE THREAD

**Issue by raphattack** [MyEtherWallet/MyEtherWallet#3247]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[x] Bug report

* **Bug Report**
  * What is the current behavior? `npm run build` fails
  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  * What is the expected behavior? `npm run build` succeeds
  * What is the motivation / use case for changing the behavior?
  * Please tell us about your environment:
    * Operating system: `Ubuntu 18.04.5 LTS`
    * Browser and version
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**npm version:** 6.14.13
**node version:** v14.17.2

**Full terminal output:**
```
$ sudo npm run build

> myetherwallet@6.0.0 build
> npm run update && vue-cli-service build


> myetherwallet@6.0.0 update
> npm run update:packages && npm run update:lists


> myetherwallet@6.0.0 update:packages
> node package-test.js


> myetherwallet@6.0.0 update:lists
> node fetchLists/index.js

Writing contract for the network: akroma
Writing contract for the network: ath
Writing contract for the network: bsc
Writing contract for the network: clo
Writing contract for the network: egem
Writing contract for the network: ella
Writing contract for the network: ere
Writing contract for the network: esn
Writing contract for the network: etc
Writing contract for the network: eth
Writing contract for the network: etho
Writing contract for the network: etsc
Writing contract for the network: ewt
Writing contract for the network: exp
Writing contract for the network: ftm
Writing contract for the network: go
Writing contract for the network: goerli
Writing contract for the network: iolite
Writing contract for the network: kov
Writing contract for the network: mintme
Writing contract for the network: mix
Writing contract for the network: music
Writing contract for the network: pirl
Writing contract for the network: poa
Writing contract for the network: reosc
Writing contract for the network: rin
Writing contract for the network: rop
Writing contract for the network: rsk-test
Writing contract for the network: rsk
Writing contract for the network: tomo
Writing contract for the network: tt
Writing contract for the network: ubq
Writing tokens for the network: bsc
Writing tokens for the network: ella
Writing tokens for the network: esn
Writing tokens for the network: etc
Writing tokens for the network: eth
Writing tokens for the network: goerli
Writing tokens for the network: kov
Writing tokens for the network: matic
Writing tokens for the network: rin
Writing tokens for the network: rop
Writing tokens for the network: rsk
Writing tokens for the network: rsk-test
Writing tokens for the network: tomo
Writing tokens for the network: ubq
Writing tokens for the network: wtc
Writing masterfile
Done

⠧  Building for production...node: ../src/coroutine.cc:134: void* find_thread_id_key(void*): Assertion `thread_id_key != 0x7777' failed.
Aborted (core dumped)
```

**Comment by mhfowler** [comment]
I ran into the same issue 

node version: v16.6.1
npm version: 7.20.3

running on Debian 10

also get this same error when running 'npm start'

**Comment by ches** [comment]
I've found this is due to project dependencies being incompatible with current versions of Node.js, which you're likely to try building with.

The project has a `.devcontainer.json`, if you use VS Code you can run it in the dev container to get around this problem.

If you prefer not to use VS Code / a dev container, you could try using a Node version matching the Dockerfile with the help of `nvm` or the like—as I write this the Dockerfile is based on `node:12-stretch`, so try Node v12.
