### ISSUE TITLE
BitBox01 support removed, but BitBox01 users still need it

### ISSUE THREAD

**Issue by benma** [MyEtherWallet/MyEtherWallet#3255]
Hi

We just noticed that BitBox01 support has disappeared without notice with v6. This is problematic, as BitBox01 users rely on MyEtherWallet to access their Ether and tokens.

Why was it removed?

Could you please restore support as soon as possible?

Thank you.

**Comment by My1** [comment]
at least for now you can try v5.

**Comment by benma** [comment]
> at least for now you can try v5.

Yes, though it warns you with "The version you are on currently (V5) will be removed eventually,".

**Comment by benma** [comment]
This PR, if merged and deployed at https://v5.myetherwallet.com, would greatly help existing BitBox01 users.

**Comment by My1** [comment]
maybe you guys could whip up something similar for mew v6 which makes it easier for them to keep the bb01

**Comment by benma** [comment]
Thanks for reminding me of this issue @My1, it can actually be closed now that it is deployed at v5.

We discussed with the MEW team and decided that the effort to port BB01 to v6 is not worth it if there is access via v5, considering the fact that the BB01 is EOL: https://guides.shiftcrypto.ch/bitbox01/eol-faqs/

**Comment by My1** [comment]
> Thanks for reminding me of this issue @My1, it can actually be closed now that it is deployed at v5.

I have mentioned the BB01 being on v5 and that's what you said back then:

> Yes, though it warns you with "The version you are on currently (V5) will be removed eventually,".
