### ISSUE TITLE
npm run build Ubuntu 20.04 环境下一直过去不

### ISSUE THREAD

**Issue by cheyue** [MyEtherWallet/MyEtherWallet#3278]
npm run build    

> myetherwallet@6.0.1 build /opt/MyEtherWallet
> npm run update && vue-cli-service build

> myetherwallet@6.0.1 update /opt/MyEtherWallet
> npm run update:packages && npm run update:lists

> myetherwallet@6.0.1 update:packages /opt/MyEtherWallet
> node package-test.js

Invalid character ~ or ^ found in package.json version string, only fixed versions are allowed.
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@6.0.1 update:packages: `node package-test.js`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@6.0.1 update:packages script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-14T09_25_24_620Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@6.0.1 update: `npm run update:packages && npm run update:lists`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@6.0.1 update script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-14T09_25_24_636Z-debug.log
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! myetherwallet@6.0.1 build: `npm run update && vue-cli-service build`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the myetherwallet@6.0.1 build script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2021-07-14T09_25_24_650Z-debug.log

**Comment by duzhi5368** [comment]
same error.
