### ISSUE TITLE
Send Offline Helper tool has seemingly disappeared from the MEW website

### ISSUE THREAD

**Issue by albydeca** [MyEtherWallet/MyEtherWallet#3283]
* **I'm submitting a ...**

  * \[x] Feature request
  * \[ ] Bug report

* **Feature Request**

Prior to the recent website update I used to make frequent use of the Send Offline Helper tool which I accessed via the footer. Now I cannot find it any longer. Please let me know whether this tool still exists and where I can find it, thanks.

**Comment by re2005** [comment]
Any update on this ?

**Comment by movraxrsp** [comment]
wondering about this too...

**Comment by re2005** [comment]
The tool is on the old website:

https://v5.myetherwallet.com/send-offline-helper

**Comment by albydeca** [comment]
Amazing, thanks! Closing but would be great to see this ported to the new website very soon
