### ISSUE TITLE
Tokens for new networks (not ETH, BSC or MATIC)

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#3284]
* **I'm submitting a ...**

  * \[x] Feature request
  * \[ ] Bug report

We are trying to integrate RSK to v6 and we found that the tokens are queried from `https://tokenbalance.mewapi.io`. How do you suggest dealing with networks that are not integrated to that API?

Thanks

**Comment by uj** [comment]
Node switcher in the upper right, then choose custom.
