### ISSUE TITLE
Offline transsactions, v.6

### ISSUE THREAD

**Issue by LLKoder** [MyEtherWallet/MyEtherWallet#3349]
Hello,

I'm not sure I right undestand but how can I work with offline transsactions in v6.
Send Offline Helper disappeared from footer's v6. 
KB wasn't updated till v6. (https://kb.myetherwallet.com/en/offline/using-mew-offline/)

I'm very interesting in v6, not v5.
Please help.

Thanks.

**Comment by movraxrsp** [comment]
Yes, I would also like to see offline transactions available in version 6.
I know they are supported in version 5.
If they will not be supported in the future, please let us know.

**Comment by LLKoder** [comment]
I have found the answer. It's [here](https://www.reddit.com/r/MyEtherWallet/comments/p29me5/send_offline_helper_tool_has_seemingly/).

**Comment by trentlo** [comment]
> I have found the answer. It's [here](https://www.reddit.com/r/MyEtherWallet/comments/p29me5/send_offline_helper_tool_has_seemingly/) and [here](https://www.reddit.com/r/MyEtherWallet/comments/p7jt8l/how_can_i_sign_transaction_offline_with_the_new/).

Thanks for the pointers. I was also confused by why I can’t find the offline transaction feature in v6.
