### ISSUE TITLE
I can not access my tokens (dashboard) from MEW

### ISSUE THREAD

**Issue by sbolat1980** [MyEtherWallet/MyEtherWallet#3375]
* What is the current behavior?
  I can not access my tokens in my wallet. I am using mew chrome extension and private key to access mew.
  Note: I can see my tokens when I check "ethplorer.io"

  Environment:
    * Operating system : Mac OS Big Sur
    * Browser and version: Chrome Version 92.0.4515.131 (Official Build) (x86_64)

![Screen Shot 2021-08-07 at 18 54 51](https://user-images.githubusercontent.com/88589939/128606323-03637043-bb1f-4ac3-8b6c-d7a505fb9e4e.png)

![Screen Shot 2021-08-07 at 18 56 53](https://user-images.githubusercontent.com/88589939/128606202-17d2eb0e-63ff-431a-b609-839e6861a9e2.png)

![Screen Shot 2021-08-07 at 18 56 53](https://user-images.githubusercontent.com/88589939/128606193-b104884c-821a-4e8a-96b7-9ee114229a70.png)

Also, there exists an error message (putting below) when I opened the mew.

{
  "exception": {
    "values": [
      {
        "type": "TypeError",
        "value": "Cannot read property 'map' of undefined",
        "stacktrace": {
          "frames": [
            {
              "colno": 22597,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "?",
              "in_app": true,
              "lineno": 378
            },
            {
              "colno": 29979,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "e.broadcastQueries",
              "in_app": true,
              "lineno": 378
            },
            {
              "filename": "<anonymous>",
              "function": "Map.forEach",
              "in_app": true
            },
            {
              "colno": 30029,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "?",
              "in_app": true,
              "lineno": 378
            },
            {
              "filename": "<anonymous>",
              "function": "Set.forEach",
              "in_app": true
            },
            {
              "colno": 30053,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "?",
              "in_app": true,
              "lineno": 378
            },
            {
              "colno": 23956,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "?",
              "in_app": true,
              "lineno": 378
            },
            {
              "colno": 23444,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "n",
              "in_app": true,
              "lineno": 378
            },
            {
              "colno": 9171,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "Object.n [as error]",
              "in_app": true,
              "lineno": 378
            },
            {
              "colno": 10091,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "E",
              "in_app": true,
              "lineno": 378
            },
            {
              "filename": "<anonymous>",
              "function": "Array.forEach",
              "in_app": true
            },
            {
              "colno": 10123,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~2a42e354.07680ebc.js",
              "function": "?",
              "in_app": true,
              "lineno": 378
            },
            {
              "colno": 128941,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~ec8c427e.81df3038.js",
              "function": "t.value",
              "in_app": true,
              "lineno": 50
            },
            {
              "colno": 128324,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~ec8c427e.81df3038.js",
              "function": "M",
              "in_app": true,
              "lineno": 50
            },
            {
              "colno": 128005,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~ec8c427e.81df3038.js",
              "function": "w",
              "in_app": true,
              "lineno": 50
            },
            {
              "colno": 301083,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~ec8c427e.81df3038.js",
              "function": "r.value",
              "in_app": true,
              "lineno": 15
            },
            {
              "colno": 300799,
              "filename": "https://www.myetherwallet.com/js/chunk-vendors~ec8c427e.81df3038.js",
              "function": "r.value",
              "in_app": true,
              "lineno": 15
            },
            {
              "colno": 631721,
              "filename": "https://www.myetherwallet.com/js/app~748942c6.99b25f13.js",
              "function": "s.result",
              "in_app": true,
              "lineno": 1
            },
            {
              "colno": 632119,
              "filename": "https://www.myetherwallet.com/js/app~748942c6.99b25f13.js",
              "function": "s._parseResult",
              "in_app": true,
              "lineno": 1
            }
          ]
        },
        "mechanism": {
          "handled": true,
          "type": "instrument",
          "data": {
            "function": "setTimeout"
          }
        }
      }
    ]
  },
  "level": "error",
  "event_id": "e20eae58c746464e8167d1f59f669be8",
  "platform": "javascript",
  "timestamp": 1628351375.87,
  "environment": "web",
  "release": "6.0.4",
  "sdk": {
    "integrations": [
      "InboundFilters",
      "FunctionToString",
      "TryCatch",
      "Breadcrumbs",
      "GlobalHandlers",
      "LinkedErrors",
      "Dedupe",
      "UserAgent",
      "BrowserTracing"
    ]
  },
  "request": {
    "url": "https://www.myetherwallet.com/wallet/",
    "headers": {
      "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/92.0.4515.131 Safari/537.36"
    }
  },
  "extra": {
    "arguments": []
  },
  "tags": {
    "network": "ETH",
    "service": "myetherwallet.com-ws",
    "walletType": "web3Wallet"
  }
}

**Comment by cryptobug77** [comment]
You can download the older version of MEW from here: https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v5.8.5

You can run index.html to open the older version, it should resolve your problem
