### ISSUE TITLE
Amount field is constantly throwing an error in send transaction page

### ISSUE THREAD

**Issue by andshin** [MyEtherWallet/MyEtherWallet#3411]
* **I'm submitting a ...**

  * \[ ] Feature request
  * \[x] Bug report

![image](https://user-images.githubusercontent.com/27360891/130613899-a70bee2d-29cd-4f57-806d-41ed814db793.png)

On Windows 10 using Chrome.

Remix and smart contract with MEW to **Send Transaction**. 

The amount field is constantly throwing an error as shown in the screenshot despite having enough for fees in the account. I vary the amount input field but it's always some error.

**Comment by benma** [comment]
I also see the same problem. For me the error disappears after a few tries / after a while.

**Comment by andshin** [comment]
Tagging devs for attention @gesseekur @rsteubs @andrewdahn
