### ISSUE TITLE
Confirmation page does not indicate token transfer

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#343]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
    - when doing a token transfer the confirmation modal displays the eth value of the transaction and not the change in token values.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
   - Make a token transaction/transfer and check the icons and the values shown
  - What is the expected behavior?
    - that the modal would display the change in balances that will occur.
  - What is the motivation / use case for changing the behavior?
    - More accurately display the value transfer operation.
  - Please tell us about your environment:
    - Operating system
       ubuntu 16.04
     - Browser and version 
        Chrome Version 70.0.3538.110

**Comment by kvhnuke** [comment]
Fixed
