### ISSUE TITLE
WebSocket RPC Connection error

### ISSUE THREAD

**Issue by clehner** [MyEtherWallet/MyEtherWallet#3462]
When running locally, connections to the hard-coded RPC server are rejected:

`Firefox can’t establish a connection to the server at wss://nodes.mewapi.io/ws/eth.`

Network log shows the following request and response:
```
GET /ws/eth HTTP/1.1
Host: nodes.mewapi.io
User-Agent: Mozilla/5.0 (X11; Linux x86_64; rv:78.0) Gecko/20100101 Firefox/78.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate, br
Sec-WebSocket-Version: 13
Origin: http://localhost:8080
Sec-WebSocket-Extensions: permessage-deflate
Sec-WebSocket-Key: u4P3bjhEXSilHUqO/cFeQQ==
DNT: 1
Connection: keep-alive, Upgrade
Pragma: no-cache
Cache-Control: no-cache
Upgrade: websocket
```
```
HTTP/1.1 403 Forbidden
Date: Sun, 19 Sep 2021 14:35:14 GMT
Content-Type: text/plain;charset=UTF-8
Content-Length: 14
Connection: keep-alive
Expect-CT: max-age=604800, report-uri="https://report-uri.cloudflare.com/cdn-cgi/beacon/expect-ct"
Vary: Accept-Encoding
Strict-Transport-Security: max-age=15552000; includeSubDomains; preload
X-Content-Type-Options: nosniff
Server: cloudflare
CF-RAY: 69138a18ae2a1841-EWR
```
This is with Firefox or Chromium on Debian Testing amd64. I tried hosting it on various origins: `localhost`, `localhost:8080`, `127.0.0.*`, and a HTTPS domain. [MyEtherWallet v6.0.6 release](https://github.com/myetherwallet/MyEtherWallet/releases/tag/v6.0.6). 
On the main website (https://www.myetherwallet.com/), the RPC connection appears to be accepted.

Screenshot:
![2021-09-19-103726_1918x1058_scrot](https://user-images.githubusercontent.com/95347/133931614-5591fbf4-77ed-4c52-9bb2-8bf15b46c543.png)
The lack of connection causes subsequent operations to fail:
![2021-09-19-153315_1080x884_scrot](https://user-images.githubusercontent.com/95347/133940570-48547fba-1832-4043-83c6-ab04f2cfcbf1.png)

**Comment by ddarville** [comment]
Hi, please take a look over this issue:
https://github.com/MyEtherWallet/MyEtherWallet/issues/3578
