### ISSUE TITLE
Add a background color

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#349]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/50660181-c39c1880-0f53-11e9-962f-3ef74c0894c6.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
At landing page "Join MEW Community" section, please add a background color, in order to separate "FAQs" and "Join MEW Community" 

Color code: #F9F9F9
Height: 246px

**Comment by SteveMieskoski** [comment]
fixed on or before beta.3
