### ISSUE TITLE
Transaction failed (Swapping ETH for BONE)

### ISSUE THREAD

**Issue by Retsam-crypto** [MyEtherWallet/MyEtherWallet#3500]
* <b>I'm submitting a ...</b>

  * \[ ] Feature request
  * \[ *] Bug report

* <b>Bug Report</b>
  * What is the current behavior?
  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
 Using Chrome MEW wallet, swapping Swap 0.03 ETH for 60 BONE tokens.

  * What is the expected behavior?
Transaction should not be rejected or rejection should not be considered as a wallet bug.

  * What is the motivation / use case for changing the behavior?
There is following message to the wallet: "Transaction was not mined within 50 blocks, please make sure your transaction was properly sent. Be aware that it might still be mined!" So possibly it is not a bug and wallet should not prompt me for writing a bug report.

  * Please tell us about your environment:
    * Operating system
Windows 10

    * Browser and version
Chrome Version 94.0.4606.81 (Official Build) (64-bit)

  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by Mewsupportz** [comment]
> 

Hi

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
