### ISSUE TITLE
Cant access old wallet

### ISSUE THREAD

**Issue by Richyktm** [MyEtherWallet/MyEtherWallet#3519]
Can someone please help. After a face id login issue I cant access my old wallet containing several coins. Ive verified coins on etherscan and have the mnemonics. Ive tried to add tokens but coin values dont appear
Email support not been helpful over many months !!!
Regards

Richard

* <b>I'm submitting a ...</b>

  * \[ ] Feature request
  * \[x] Bug report

* <b>Feature Request</b>

  * Briefly explain the feature you would like us to implement
  * What are the current issues this feature will solve
  * Is this feature cross compatible with other ethereum networks
  * Are you willing to help us with development support if required
  * Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

* <b>Bug Report</b>
  * What is the current behavior?
  * If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  * What is the expected behavior?
  * What is the motivation / use case for changing the behavior?
  * Please tell us about your environment:
    * Operating system
    * Browser and version
  * Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  * Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
