### ISSUE TITLE
Unable to setup MyEtherWallet in local

### ISSUE THREAD

**Issue by subhasisbanik** [MyEtherWallet/MyEtherWallet#3520]
* <b>I'm submitting an issue</b>
I am trying to set up a MyEtherWallet with the commands provided in the github but  am facing the below error while running npm run build:
![image](https://user-images.githubusercontent.com/25420904/138697940-8eb826d6-1a42-4ed4-870f-2030338bfa7d.png)
I am having the configuration below:
OS: Ubuntu 20.04
Node version: 12.22.7
Npm version: 6.14.15

Please help me here.

**Comment by alven-io** [comment]
Sample problem here

**Comment by subhasisbanik** [comment]
any update in this thread?

**Comment by hmdadou** [comment]
same problem
