### ISSUE TITLE
Sending issues

### ISSUE THREAD

**Issue by lmorse59** [MyEtherWallet/MyEtherWallet#3540]
* I submitting a request as I cannot send any funds out of my wallet. I always get the same message and it doesn't matter what I am trying to send 
* err: max fee per gas less than block base fee: address ( ), maxFeePerGas: 121591107157 baseFee: 123897208008 (supplied gas 6339724)

I currently have a lot of Eth on the wallet so can someone tell me a work around please

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
