### ISSUE TITLE
BitBox02 stuck, 'too much recursion' error

### ISSUE THREAD

**Issue by benma** [MyEtherWallet/MyEtherWallet#3560]
###### Info

- **Version**: v6.4.0-hotfix.1
- **Browser**: FireFox and Chrome
- **OS**: All

###### Steps to reproduce

Unlock a BitBox02. After unlocking and potentially confirming the pairing code, the screen freezes at "Select Network and Address" with the following error in console:

![image](https://user-images.githubusercontent.com/1225267/141642833-21656704-bb61-40e3-961c-db2765026d09.png)

It seems to be a regression unrelated to the BitBox02 or BitBox02 libraries. The bug was introduced recently, as everything used to work up until now.

**Comment by benma** [comment]
@gamalielhere does the linked PR address this issue? Is there an ETA?

Please let me know - we can also lend a hand in debugging this problem if needed.

**Comment by gamalielhere** [comment]
@benma planning to release it this Thursday

**Comment by iamfj** [comment]
It seems that the update has been released. I tried to connect my BitBox02 yesterday and got the "too much recursion" error again.

Have you tried it yet @benma ?

**Comment by benma** [comment]
@gamalielhere when clicking unlock at the bitbox02 screen, the BitBox02 goes into action but the component is not updated anymore: the unlock animation gif and the pairing code are not shown anymore.

The last commits touching this code seems to be https://github.com/MyEtherWallet/MyEtherWallet/commit/46d31dc7c84794d04c92d92cec4852a0269828db. I tried to figure out the regression but no luck so far. Maybe it's quick for you to see the issue?

**Comment by gamalielhere** [comment]
@benma thanks for letting me know, i'll take a look at it

**Comment by iamfj** [comment]
> @iamfj what does the version say at the bottom of the page?
> 
> It works for me now, except for the pairing code. The pairing code is not shown anymore on MEW. If confirmed on the device, MEW hangs, but it will work when connected a second time.
> 
> I'll look into this issue, the pairing code confirmation used to work, so there is some sort of regression.

Thanks for the hint @benma . I have just tried it again. Now it works for me too, thanks for the quick fix @gamalielhere .

**Comment by benma** [comment]
@gamalielhere any progress? BitBox02 users are pretty confused right now, and we send them to v5 for the time being.

**Comment by gamalielhere** [comment]
@benma here's a PR for it. #3595 let me know once you can test it out

**Comment by benma** [comment]
> @benma here's a PR for it. #3595 let me know once you test it out

@gamalielhere it works nicely for me, thank you!

**Comment by Mewsupportz** [comment]
> It seems that the update has been released. I tried to connect my BitBox02 yesterday and got the "too much recursion" error again.
> 
> Have you tried it yet @benma ?

Hi, explain your problem in details for assistance

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
