### ISSUE TITLE
When deploying the app to cloud, dashboard can't fetch balance from https://tokenbalance.mewapi.io 

### ISSUE THREAD

**Issue by arsmyrnov** [MyEtherWallet/MyEtherWallet#3578]
###### Info

- **Version**: 6.4.1
- **Browser**: Chrome
- **OS**: Linux
- **Page Url**: https://myetherwallet.com/wallet/dashboard

###### Steps to reproduce
clone repo
deploy app to aws

###### What do you expect to happen?

see current balance

###### What happens instead?
When deploying the app to cloud, dashboard can't fetch balance from https://tokenbalance.mewapi.io with the following error:

Access to fetch at 'https://tokenbalance.mewapi.io/eth?address=[ADDRESS]' from origin 'aws hosting' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.

As I understand mewapi only accepts myetherwallet and localhost origins. Is there a way to whitelist additional address locally or replace mewapi with some other api to get balance?

**Comment by arsmyrnov** [comment]
@gamalielhere can you please help?

**Comment by ddarville** [comment]
@arsmyrnov
Be careful with this project. One of the node_module files incluyes a troyan malware. I will recommend not using MyEtherWallet.
If you are looking into starting a small project i will recommend you to look into better repositories.

Lastly, they probably will never answer.

Horrible organization. Stay away from this, and do not trust node_modules to production enviroment.

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
