### ISSUE TITLE
canceling ens details print or clicking reject to sign metamask transaction should not continue to next step

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#358]
- **I'm submitting a ...**

  - [ ] Bug report

- **Bug Report**
  - What is the current behavior?
    - When using metamask, canceling an ens when asked to print, should not prompt the user to continue.  If the user rejects/cancels the transaction in metamask, the success modal is shown, but no modal should be shown.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
   - When using metamask, canceling an ens at the details stage pops up an un-formatted image for print, and canceling should not prompt the user to continue.  If the user rejects/cancels the transaction in metamask, the success modal is shown, but no modal should be shown
  - What is the expected behavior?
    - Canceling save the details print pop-up should not prompt the user to continue.  If the user rejects/cancels the transaction in metamask, no modal should be shown
  - What is the motivation / use case for changing the behavior?
    - Improve ux

**Comment by gamalielhere** [comment]
I agree with not showing a success modal, but I don't agree not showing a modal at all. Currently, the modal just serves the purpose of informing the user to proceed with metamask's transaction modal. Changing the text and sign should fix this.

Also, there is no way to detect whether the user cancelled or printed the file.
