### ISSUE TITLE
Gas limit for ERC-20 transaction resets when tab is not active for a longer time

### ISSUE THREAD

**Issue by queequeq** [MyEtherWallet/MyEtherWallet#3591]
###### Info

- **Version**: 6.4.2
- **Browser**: Firefox
- **OS**: Linux
- **Page Url**: Offline usage, MyEtherWallet-v6.4.2/index.html#/wallet/send-tx

###### Steps to reproduce

I download the latest version of MEW as a zip file, open index.html, access my wallet through a keystore file and open the _Send Transaction_ menu. I select an ERC-20 token to send, hit _MAX_ for the amount and enter a receiving address. The gas fee at the moment is too high for me, so I decide to wait while I do something else in my browser and check the tab now and then to see if I can get the tx through for a lower fee.

###### What do you expect to happen?

When I revisit the tab after an arbitrary amount of time, MEW should show the current transaction fee that is needed for a successful transaction.

###### What happens instead?

If I wait long enough (roughly upwards of 15 minutes), a very low transaction fee is shown. This is because the _Gas Limit_ field has been reset in the meantime. However, this field is under _Advanced_, so as a beginner user I don't see it and simply hit _Next_ and then _Confirm & Send_ as fast as possible because I want to make sure my transaction is executed for the super low gas fee. The transaction gets sent but fails because it runs out of gas.

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
