### ISSUE TITLE
How Can I activate this project on public domain?

### ISSUE THREAD

**Issue by alirf81** [MyEtherWallet/MyEtherWallet#3592]
I want to run this project on my public domain.
I connected my domain to the server and installed nginx on it which proxies the request to localhost:8080.
Now I can access the website through the domain but it still makes some xhr requests to localhost:8080.
I guess it is related to WebSocket.
Would you kindly guide me how I can run this on public IP or domain?

**Comment by Mewsupportz** [comment]
Hi, explain your problem in details for assistance
