### ISSUE TITLE
Code Pages

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#36]
##### Create Page Designs
- [ ] FAQ
- [ ] Help
- [ ] Tx Warning

##### Update Page Designs
- [ ] Success Modal

**Comment by SteveMieskoski** [comment]
@hsurf22  Feel free to update this to better describe the particular pages/tasks

**Comment by gamalielhere** [comment]
@stevemieskoski closing this since it seems done.
