### ISSUE TITLE
ENS details print page is not formatted

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#360]
- **I'm submitting a ...**

  - [ ] Bug report

- **Bug Report**
  - What is the current behavior?
    - Continuing an ens at the details stage pops up an un-formatted image for print.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
    - Proceed to register ens, enter ens, and continuing until the print details page pops-up.  The presented page is un-formatted.
  - What is the expected behavior?
    - A formatted image should be presented for printing.
  - What is the motivation / use case for changing the behavior?
    - Improve ux

**Comment by gamalielhere** [comment]
@jackhuangusa can we get a design for this?

**Comment by jackhuangusa** [comment]
Yeah, @gamalielhere 
![image](https://user-images.githubusercontent.com/31494364/50712791-a20c6100-1027-11e9-97d7-658edfe11529.png)
1.) When you click "Cancel" print , it should not link to this page

![image](https://user-images.githubusercontent.com/31494364/50712802-af295000-1027-11e9-9253-c9321360f1e3.png)

2. When you click Reject, it should not popup "Success"
![image](https://user-images.githubusercontent.com/31494364/50712842-d849e080-1027-11e9-9c1c-bef42586efc8.png)

**Comment by gamalielhere** [comment]
@jackhuangusa  that's issue #358
