### ISSUE TITLE
Please bump bitbox02 package to v0.12.0 to fix WebHID access on Chrome

### ISSUE THREAD

**Issue by benma** [MyEtherWallet/MyEtherWallet#3618]
@gamalielhere could you please bump this to 0.12.0: https://github.com/MyEtherWallet/MyEtherWallet/blob/91780bed6f9603b4200990c4ecb60bdbf22971a1/package.json#L67

WebHID access to the BitBox02 stopped working as of Chrome version
97 due to incorrect vendor/product filter names. See also:
digitalbitbox/bitbox02-api-js#62

Simply upgrading the package solves the problem.

Would be great to have this deployed alongside https://github.com/MyEtherWallet/MyEtherWallet/pull/3611 soon, so BitBox02 users can use v6 without a hitch again.

Let me know if I can be of any assistance.

Thank you.

**Comment by gamalielhere** [comment]
@benma are there changes we need to do on our end or just the package update?

**Comment by benma** [comment]
@gamalielhere just updating is enough.

**Comment by benma** [comment]
Great, thanks!
