### ISSUE TITLE
Arrow display a wrong direction

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#363]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

![image](https://user-images.githubusercontent.com/31494364/50709791-d549f280-101d-11e9-9771-fc124d21e44f.png)

- **Bug Report**
  - What is the current behavior?
Tokens Expend Arrow display a wrong direction

  - What is the expected behavior?
Change Expend Arrow to opposite direction.

**Comment by gamalielhere** [comment]
@jackhuangusa was this in develop?

**Comment by jackhuangusa** [comment]
@gamalielhere I am not sure. This bug is just need to turned arrow direction.

**Comment by gamalielhere** [comment]
I can't replicate it on develop atm. Will revisit

**Comment by gamalielhere** [comment]
Closing this since beta shows it to be correct.
