### ISSUE TITLE
Can't use a custom derivation path with a Ledger device

### ISSUE THREAD

**Issue by staguigue-ledger** [MyEtherWallet/MyEtherWallet#3631]
###### Info

- **Version**: MyEtherWallet version 6
- **Browser**: Chrome
- **OS**: Windows
- **Page Url**: https://www.myetherwallet.com/wallet/access/hardware

###### Steps to reproduce

1- Go on https://www.myetherwallet.com/wallet/access and choose Hardware Wallets
![image](https://user-images.githubusercontent.com/89529968/150297610-0e18660c-63ce-48ed-9aa2-29b41bb122cf.png)

2- Open your ETH/ETC/ETH recovery app on your Ledger device and establish the connection

3- Click on the Ethereum derivation path to open the small window that allow users to add a custom derivation path
![image](https://user-images.githubusercontent.com/89529968/150298669-d86233ab-47d1-4e5b-85d4-9a2b125c87c6.png)

4- Add the ETC derivation path _m/44'/61'/0'/0_ (or any other derivation path), add an Alias and click on Add Path
![image](https://user-images.githubusercontent.com/89529968/150298952-667db601-5d6f-477d-958e-a63ae83b34bc.png)

###### What do you expect to happen?

I expect to be able to access the addresses derived with the ETC path.

###### What happens instead?

I face the error message "Cannot read properties of undefined (reading 'then')"

###### Screenshot

![image](https://user-images.githubusercontent.com/89529968/150299078-c9f1f096-3637-4d06-9cec-38ff35a33c62.png)

This issue prevents Ledger users from using a custom derivation path to recover funds (for instance if they mistakenly sent some ETH to their ETC account in Ledger Live).

**Comment by steve77r** [comment]
Facing same issue "Cannot read properties of undefined (reading 'then')" is this error been worked on?
