### ISSUE TITLE
Bitbox02 on Safari

### ISSUE THREAD

**Issue by My1** [MyEtherWallet/MyEtherWallet#3636]
it might be useful to drop a warning for Safari users as it apparently doesnt seem to have a mixed content exception for localhost anymore and therefore straight up blocks any attempts to access the Bridge.

If there are HW Wallets that act similarly, those obviously should have something similar but I am not well-versed enough for that.

![image](https://user-images.githubusercontent.com/6696524/150677277-e9723e3e-2d9e-47bc-ada8-bfca192d1287.png)

**Comment by benma** [comment]
That issue should maybe be in https://github.com/digitalbitbox/bitbox02-api-js/ so that all wallets using it get the same warning.

**Comment by My1** [comment]
> That issue should maybe be in https://github.com/digitalbitbox/bitbox02-api-js/ so that all wallets using it get the same warning.

I was thinking between that and here I thought here was best since I didnt know if the js could produce visible warnings that actually fit the wallet design and all and dont look extremely weird
