### ISSUE TITLE
Align content 

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#365]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

1.) 
![image](https://user-images.githubusercontent.com/31494364/50710114-efd09b80-101e-11e9-9866-2362e0dbb9bf.png)

2.) 
![image](https://user-images.githubusercontent.com/31494364/50710121-f5c67c80-101e-11e9-904f-9e15fa56c60c.png)

3.)
![image](https://user-images.githubusercontent.com/31494364/50711629-adf62400-1023-11e9-9789-1b137bcd44b3.png)

- **Bug Report**
  - What is the current behavior?
Dose not align as a line. 
  
  - What is the expected behavior?
1.) In Swap page. Icon, arrow and text should center align.
2.) In side Nav-bar, Icon and text should left align.
3.) Center align icon and margin right 20px; Magnify icon 80%

**Comment by hsurf22** [comment]
I fixed all these issues.
I'll wait until everything merged and uploaded to develop and check these issues again.
Please don't close this.

**Comment by hsurf22** [comment]
Fixed
