### ISSUE TITLE
Change on hover color

### ISSUE THREAD

**Issue by olgakup** [MyEtherWallet/MyEtherWallet#378]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
  On hoover the Software option is highlighted green:
<img width="1103" alt="screen shot 2019-01-04 at 4 23 09 pm" src="https://user-images.githubusercontent.com/16910687/50717569-0e458f80-103d-11e9-8a4b-ff736c70671d.png">

  - What is the expected behavior?
  Please change color to red
![image](https://user-images.githubusercontent.com/16910687/50717576-17cef780-103d-11e9-8188-e7ab2bf9d06b.png)

**Comment by gamalielhere** [comment]
@olgakup same color as the recommend text before hover?

**Comment by kvhnuke** [comment]
I prefer green! @jackhuangusa

**Comment by kvhnuke** [comment]
@gamalielhere I think change the color only on Software, as it is not safe.

**Comment by jackhuangusa** [comment]
Yes, it is. The red color is only for Software hover
