### ISSUE TITLE
Transfer bitcoin

### ISSUE THREAD

**Issue by majka22** [MyEtherWallet/MyEtherWallet#379]
- **I'm submitting a ...**

  - [ ] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required

- **Bug Report**
  - What is the current behavior?
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior?
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
    - Browser and version
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)

**Comment by gamalielhere** [comment]
Please update information as necessary
