### ISSUE TITLE
Where is the repo for the Android App?

### ISSUE THREAD

**Issue by crypto-nerd-88** [MyEtherWallet/MyEtherWallet#3800]
I would like to build the android app completely from source, but maybe I just don't understand how the repos here interoperate. I see this repo as well as [mewwalletkit](https://github.com/MyEtherWallet/mew-wallet-android-kit/tree/master/mewwalletkit/src/main/java/com/myetherwallet/mewwalletkit), but I cannot figure out how the Android app is pieced together. Can someone please point me in the right direction?

**Comment by gamalielhere** [comment]
@crypto-nerd-88 it's currently under transition, you can look at this repo here: https://github.com/mewwallet
