### ISSUE TITLE
Keep text in one line

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#381]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
![image](https://user-images.githubusercontent.com/31494364/50788560-a4143100-126e-11e9-8ab5-47603c3b326a.png)
  - What is the current behavior?
Text in two lines.

![image](https://user-images.githubusercontent.com/31494364/50788741-1edd4c00-126f-11e9-91ab-11f434d608c2.png)
  - What is the expected behavior?
Please keep text in one line.

**Comment by SteveMieskoski** [comment]
fixed on or before PR #537
