### ISSUE TITLE
WalletConnect: share chainId with wallet

### ISSUE THREAD

**Issue by Toporin** [MyEtherWallet/MyEtherWallet#3848]
###### Info

With WalletConnect, the Dapp (MEW in this case) and the wallet client (the signing device) negociate the network (chainId) during session request. The process is roughly the following (see also https://docs.walletconnect.com/tech-spec#session-request):

* After scanning the QR code, the client wallet recover the MyEtherWallet peerId and  suscribes to initiate the connection.

* MEW then reply with a RPC request such as:
`{"id":1653070343497318,"jsonrpc":"2.0","method":"wc_sessionRequest","params":[{"peerId":"85a62a23-6834-4646-a7cf-fd7c63ac8511","peerMeta":{"description":"MyEtherWallet (MEW) is a free, open-source, client-side interface for generating Ethereum wallets & more. Interact with the Ethereum blockchain easily & securely.","url":"https://www.myetherwallet.com","icons":["https://www.myetherwallet.com/icons/icon192.png","https://www.myetherwallet.com/favicon.png","https://www.myetherwallet.com/img/icons/favicon-32x32.png","https://www.myetherwallet.com/img/icons/favicon-16x16.png","https://www.myetherwallet.com/img/icons/apple-touch-icon-152x152.png","https://www.myetherwallet.com/img/icons/safari-pinned-tab.svg"],"name":"MyEtherWallet.com: Your Key to Ethereum"},"chainId":null}]}`

Here we can see that **chainId is null**, so MEW does not provide information the the client wallet on which network should be activated.

* After that, the wallet client replies by providing a list of accounts (addresses managed by the wallet) and the chainId that it wants to use:
`{"result": {"approved": true, "chainId": 3, "accounts": ["0xdb8109a158ef6db939c9cfe16fff01779121e187"], "peerId": "41849101-10f9-4875-8b46-734472964619", "peerMeta": {"name": "Satochip-Bridge", "url": "https://satochip.io", "description": "Satochip - the open-source and affordable hardware wallet!", "icons": []}}, "jsonrpc": "2.0", "id": 1653070343497318}`

Here, **the client provide chainId 3**, corresponding to the Ropsten network. MyEtherWallet then open a session with the correct address, but on the Ethereum network by default (instead of Ropsten). Consequently, MEW is working on the Ethereum network while the wallet client thinks it is on Ropsten. If a transaction is sent to the client for signing, the WalletConnect protocol removes the chainId (if any), so the client has no way to know on which network it is supposed to operate. **If the user is not careful, he may approve a transaction thinking it is on one network while it is actually on another network!**

- **Version**: v6.0.4 (current version)
- **Browser**: Chrome
- **OS**: Linux (Ubuntu)
- **Page Url**: https://www.myetherwallet.com/wallet/access/mobile?type=overview

###### Steps to reproduce

The issue has been tested on [trust wallet](https://trustwallet.com/):
* Download the app and create a new multi-coin wallet
* Connect to MEW via walletConnect (settings => WalletConnect) and Scan the QR-code
* Before clicking on the 'connect' button, user can select the network on clicking on the address. Default is Ethereum but Binance Smart Chain can be selected instead.
* Click on connect
=> MEW displays the selected account, but on the Ethereum network

The issue is also present with Metamask mobile for Android.

###### What do you expect to happen?

Show MEW homepage on the network selected via WalletConnect using the chainId provided by the client wallet during session initialization.

###### What happens instead?

MEW displays the selected account on the Ethereum network instead

**Comment by gamalielhere** [comment]
Closing as this doesn't seem to be the case as of trustwallet 7.2.1
