### ISSUE TITLE
npm run build is not working.

### ISSUE THREAD

**Issue by YASH1730** [MyEtherWallet/MyEtherWallet#3862]
###### Info

- **Version**: MyEtherWallet v6.5.4-hotfix.1
- **Browser**: (Chrome/Firefox/Opera/etc..)
- **OS**: (Windows/Linux/Mac)
- **Page Url**: (ie https://myetherwallet.com/wallet/dashboard)

Hey, There My name is Yashwant Sahu. I have installed the myetherumwallet for development purposes.  But after the successful execution of the "npm ci" command. I run the command for the build "npm run build". But I got an error Screen Shot below.

please Help

###### Steps to reproduce
npm run build 

###### Screenshot
<img src = 'https://user-images.githubusercontent.com/77061466/170302229-d6d296e3-fa91-44d3-b69b-08639f589f00.png' />
```
If you have some screenshots, please include them in the report
![Screenshot from 2022-05-25 21-09-38](https://user-images.githubusercontent.com/77061466/170302229-d6d296e3-fa91-44d3-b69b-08639f589f00.png)

```

**Comment by gamalielhere** [comment]
@YASH1730 you don't have to run `npm run build` if you're developing. just run `npm install && npm run juststart`;
