### ISSUE TITLE
My staking count in Dapps ETH 2.0 become 0!

### ISSUE THREAD

**Issue by holynn-q** [MyEtherWallet/MyEtherWallet#3915]
###### Info

- **Version**: 6.5.6
- **Browser**: Chrome
- **OS**: Windows
- **Page Url**: https://myetherwallet.com/wallet/dashboard)](https://www.myetherwallet.com/wallet/dapps/staked/staked-1)

###### Steps to reproduce

log in mew, click the dapps , stake, eth is shows
Earned < 0.000001 ETH · Average APR < -10,000%

###### What do you expect to happen?

I staked 32 eth with mew on Dec-24-2020 11:18:47 PM
beaconsacn url is https://beaconscan.com/validator/0xb39cafdbef629a153a2ef2985b74937e191daf4f0c1b1346517071a39be35f81a6f7fb8ae485eee906ddf39bf0629eb7
So I knew my eth2 stake stats before, it is 32eth

###### What happens instead?

My staked count become 0!
I got my eth2 public key is 0x930ba92409c4d7da8e3c31b7be2921fd12ef488bcffc3da63dfd1aca8036fcaeb4ff51d60976b086936d689465aa1de8

But it can't be found on beaconsan
the eth2 address link (https://www.myetherwallet.com/wallet/dapps/staked/staked-1
shows my eth2 publickey is 0xb39cafdbef629a153a2ef2985b74937e191daf4f0c1b1346517071a39be35f81a6f7fb8ae485eee906ddf39bf0629eb7
so which is my true eth2 publickey?
if 2nd is not my publickey, it means I lost 32 eth!
###### Screenshot
![123](https://user-images.githubusercontent.com/4759316/173197236-aad33855-4362-47e5-a162-76840e5d2458.png)

**Comment by holynn-q** [comment]
I got my eth2 publickey from mew android app.
![mew](https://user-images.githubusercontent.com/4759316/173197351-8a7740b5-45c7-4db6-b518-e2cbf0802ece.jpg)

**Comment by gamalielhere** [comment]
Closing as this looks to be resolved now. Please feel free to reopen if you're still having issues, or contact our support team at support@myetherwallet.com

![Screen Shot 2022-10-27 at 3 48 33 PM](https://user-images.githubusercontent.com/16236741/198412250-f176226b-3525-4492-8d8e-7073c7008ad0.png)
