### ISSUE TITLE
Rates animation should be: slide from left to right

### ISSUE THREAD

**Issue by olgakup** [MyEtherWallet/MyEtherWallet#396]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
 _What is the current behavior?_
 
Rates on access you wallet page  are sliding from bottom to top
<img width="1605" alt="screen shot 2019-01-09 at 11 37 44 am" src="https://user-images.githubusercontent.com/16910687/50923990-20d81400-1403-11e9-835a-4eb92eb20404.png">

  - What is the expected behavior?
Rates should be sliding from left to right

**Comment by gamalielhere** [comment]
Discuss with @jackhuangusa. Issue: https://github.com/MyEtherWallet/MyEtherWallet/issues/329

**Comment by gamalielhere** [comment]
Fixed with the recent release
