### ISSUE TITLE
Transmitting offline generated transaction with no open wallet

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#397]
- **I'm submitting a ...**

  - [X] Feature request

- **Feature Request**

  - Briefly explain the feature you would like us to implement
    - A sub site where a user can broadcast an transaction generated offline.
  - What are the current issues this feature will solve
    - A user must still unlock a wallet to send a transaction generated offline.
  - Is this feature cross compatible with other ethereum networks
    - yes

**Comment by kvhnuke** [comment]
We should seperate first tab and second tab to a different page
![image](https://user-images.githubusercontent.com/10602065/50928333-41a66680-140f-11e9-9c61-c29b8c8b7955.png)
currently it doesnt make sense to do it this way

**Comment by kvhnuke** [comment]
yea we have to just have offline tab in the current design then put Online 1 and Online2 in a seperate page

**Comment by hsurf22** [comment]
Done
