### ISSUE TITLE
Apply checksum according network

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#405]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Based in EIP55, EIP155 and [EIP1191](https://eips.ethereum.org/EIPS/eip-1191), apply checksum considering `chainId`. This allows to show RSK addresses with its right checksum and respect the actual ETH checksum.

**Comment by kvhnuke** [comment]
closing as this is solved in #461
