### ISSUE TITLE
Integrating new hardware wallet

### ISSUE THREAD

**Issue by northmz** [MyEtherWallet/MyEtherWallet#4062]
Hello, According to Readme on main repository, hardware wallets should contact by email for integration:

![image](https://user-images.githubusercontent.com/45390177/182075053-7ea10d08-b663-4675-9553-29a099b5176c.png)

We have integrated our Prokey Optimum (a secure, open-source and easy to use hardware wallet) with MEW but no one doesn't respond my emails to integrations@myetherwallet.com. would you please let me know who I should contact with?

**Comment by gamalielhere** [comment]
@northmz you can also make a PR on this repo with the integration, if you want us to do it for you, we'll have to get a couple of the hardware wallets and the documentation for integrating said wallets.
