### ISSUE TITLE
add wallet using keystore, different error message

### ISSUE THREAD

**Issue by SteadyAction** [MyEtherWallet/MyEtherWallet#411]
I am trying to add wallet using keystore file.
The keystore is not from MEW.

When I try to import wallet with the keystorefile with correct password, it shows:
**(error_07) Please enter a valid password. Error: unable to decrypt data**

When I intentionally put wrong password, it shows:
**(error_07) Please enter a valid password. Error: Key derivation failed - possibly wrong passphrase**

What is wrong with my keystore?
This is my keystore contents.

{"version":3,"id":"7388d5f2-de74-4414-a041-3cec8c3531ea","crypto":{"ciphertext":"a1f6916bfef0071060854f538025ab162001d801cb8ab60024014f866fdb944b","cipherparams":{"iv":"8c620a20457dd68fb345de3dfd93d0e7"},"kdf":"scrypt","kdfparams":{"r":6,"p":1,"n":4096,"dklen":32,"salt":"7aed5bef9047f0be506d79ec6b1808c70e1544238d6d82f4158f487468057c58"},"mac":"25dfce9806e6fd102ed18079144deb89fbf7efa7d6cce02b5857b70914433f91","cipher":"aes-128-cbc"},"address":"0x8993480f71abaf4760a8e5253f591c9e06fb5e50"}

And its password is **happy1234**

Please help me...

**Comment by kvhnuke** [comment]
We'll look into it and get back to you, since your wallet is public please refrain from using it.

**Comment by kvhnuke** [comment]
I took a look at the wallet file, This file is not properly encrypted.
if you change `aes-128-cbc` to `aes-128-ctr` it will decrypt however, it wont derive the proper private key for your address. I tried to decrypt it with geth as well with no luck. How did you generate this file?

**Comment by SteadyAction** [comment]
@kvhnuke can we solve this problem together?

https://github.com/BANKEX/web3swift/issues/279

**Comment by gamalielhere** [comment]
Bump

**Comment by gamalielhere** [comment]
Looks like this has been fixed. closing
