### ISSUE TITLE
"Tips" warning slide cut off on smaller screen

### ISSUE THREAD

**Issue by KatyaMik** [MyEtherWallet/MyEtherWallet#417]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
slide cut off on top in the default browser zoom setting

<img width="1278" alt="screen shot 2019-01-10 at 2 19 35 pm" src="https://user-images.githubusercontent.com/46572881/51000995-7d126500-14e3-11e9-9ede-170a918d3681.png">

  - What is the expected behavior?
entire slide should be visible with header

**Comment by hsurf22** [comment]
Fixed
e204a48ac69aaa302dfe4146d8a3c4080e95ad42
