### ISSUE TITLE
`npm run build` refuses to continue

### ISSUE THREAD

**Issue by lucrus73** [MyEtherWallet/MyEtherWallet#4174]
###### Info

I'm running npm version 8.2.0 on node 16.13.1.
I have node and everything installed only for my user via:

    export NPM_CONFIG_PREFIX=~/npm-global
    export PATH=$NPM_CONFIG_PREFIX/bin:~/node/bin:$PATH

in my `.bashrc`
I'm on Debian sid.

###### Steps to reproduce

I cloned the repo with `git clone https://github.com/MyEtherWallet/MyEtherWallet.git`, then ran `npm ci`. Please note that the README.md file tells to clone the repo with `git clone git@github.com:MyEtherWallet/MyEtherWallet.git` instead (likely replacing `git@` with `lucrus73@`), but that requires to have my public key configured, which I haven't, so I assume cloning the repo via HTTPS should work the same. 

Then I ran `npm run build`, but that resulted in the following error messages:

    ERROR: Update highcharts from 10.2.0 to 10.2.1. Released: 2022-08-29T13:33:57.642Z
    ERROR: Update @commitlint/config-conventional from 17.0.3 to 17.1.0. Released: 2022-08-27T06:25:42.193Z
    ERROR: Update commitlint from 17.0.3 to 17.1.2. Released: 2022-08-29T07:53:19.453Z

    REFUSING TO CONTINUE because above packages are TOO FAR OUT OF DATE!
    In order to build MyEtherWallet, you must edit package.json.
    Update the versions for the packages above to their current versions.
    Then run `npm update`.

I dutily edited the version numbers in the package.json file and then ran `npm update`.

###### What do you expect to happen?

I expect npm to update the deps and then to be able to run `npm run build`.

###### What happens instead?

`npm update` resulted in 

    npm ERR! code ERESOLVE
    npm ERR! ERESOLVE unable to resolve dependency tree
    npm ERR! 
    npm ERR! While resolving: myetherwallet@6.6.5
    npm ERR! Found: graphql@16.6.0
    npm ERR! node_modules/graphql
    npm ERR!   graphql@"16.6.0" from the root project
 
and I'm stuck.

**Comment by saisumit** [comment]
+1

**Comment by gamalielhere** [comment]
@saisumit did you run `npm install` after updating the package.json and then running `npm run update`? `npm update` relates to npm itself. Not our repo.
