### ISSUE TITLE
Custom node with EIP-155 Support

### ISSUE THREAD

**Issue by jtelo88** [MyEtherWallet/MyEtherWallet#4204]
Hi,

I perfectly understand that you dont add the ETHW fork immediately for safety purposes, but I the custom node and EIP-155 support should be available like long time ago to everyone who use your platform and know what are doing.

I want to know how I can do to gte the custom node and EIP-155 without need to wait until MEW implement it completely. 

Thanks

**Comment by gamalielhere** [comment]
@jtelo88 due to safety concerns, we manually review and whitelist nodes, which is why we disabled custom nodes as it won't be viable for us to screen every node out there. If you have a node you are interested in adding, please create a PR for a websocket supported node.
