### ISSUE TITLE
Flashing "Balance isn't available offline"

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#421]
I'm not sure what determines this, but I see "Balance isn't available offline" flashing while balances are loading in the mnemonic wallet. We should probably have a better way of determining if the user is offline than what's currently in place.

<img width="611" alt="screen shot 2017-11-17 at 4 34 56 pm" src="https://user-images.githubusercontent.com/649992/32973603-97cb93e4-cbb5-11e7-9028-aecbf75dafc5.png">

**Comment by HenryNguyen5** [comment]
Related to #379

**Comment by james-prado** [comment]
Issue occurs with hardware wallets too

![gif](https://user-images.githubusercontent.com/13836920/33287340-68d9d590-d386-11e7-851c-0fbdece62dc2.gif)
