### ISSUE TITLE
Transaction fails to send to chain after verification on physical keepkey

### ISSUE THREAD

**Issue by simpledefi** [MyEtherWallet/MyEtherWallet#4242]
###### Info

- **Version**: Current
- **Browser**:  Chrome, or Firefox
- **OS**: Linux
- **Page Url**: https://www.myetherwallet.com/wallet/swap

###### Steps to reproduce
Initiate any activity

A detailed list of reproduction steps.
Connect wallet, enter pin, select account and chain (BSC), swap, select BNB->USDC, enter amount, verify swap on keepkey, error message.

This happens on the final step of ANY transaction on BSC.

###### What do you expect to happen?
After verifying on Keepkey, transaction should be sent to chain:

...

###### What happens instead?
{
  "message": "Incompatible EIP155-based V 147 and chain id 1. See the Common parameter of the Transaction constructor to set the chain id.",
  "exception": {
    "values": [
      {
        "value": "Incompatible EIP155-based V 147 and chain id 1. See the Common parameter of the Transaction constructor to set the chain id.",
        "type": "Error",
        "mechanism": {
          "type": "generic",
          "handled": true,
          "synthetic": true
        }
      }
    ]
  },
  "level": "error",
  "event_id": "ff809880d1b34d9a9c677c963aa58d19",
  "platform": "javascript",
  "timestamp": 1664508124.182,
  "environment": "web",
  "release": "6.6.6",
  "sdk": {
    "integrations": [
      "InboundFilters",
      "FunctionToString",
      "TryCatch",
      "Breadcrumbs",
      "GlobalHandlers",
      "LinkedErrors",
      "Dedupe",
      "HttpContext",
      "BrowserTracing"
    ]
  },
  "sdkProcessingMetadata": {},
  "request": {
    "url": "https://www.myetherwallet.com/wallet/swap",
    "headers": {
      "Referer": "https://www.google.com/",
      "User-Agent": "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/105.0.0.0 Safari/537.36"
    }
  },
  "tags": {
    "network": "BSC",
    "service": "myetherwallet.com-ws",
    "walletType": "keepkey"
  }
}
...

###### Screenshot
![image](https://user-images.githubusercontent.com/96835250/193267485-528f2547-5f6d-4273-8ad1-12496fd97b4a.png)

```
If you have some screenshots, please include them to the report
```

**Comment by gamalielhere** [comment]
@simpledefi this is intentional as our KeepKey integration only supports ETH transactions.
