### ISSUE TITLE
Custom Nodes -- Final Touches

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#427]
- Custom networks. It was already a pain to fix up all of the code that was selecting the node from the NODES object, the same would have to be done for NETWORKS. This seemed like a lower-priority use case, for now. Should be very doable.
- Handling custom node collisions. The "id" of the custom node is url:port, so if you tried to add two of the same, you'd have a problem. I'll be sure to handle this.
- Fix `any` typing: https://github.com/MyEtherWallet/MyEtherWallet/pull/322#discussion_r151832414

**Comment by Blazetechlectronics** [comment]
Ok thanks for letting me know about be this thing

**Comment by wbobeirne** [comment]
@dternyak WRT to the `any` typing, it looks like all of the requests are doing that. @HenryNguyen5 can you provide any insight on if this is fixable? Looks like the `any`s were setup as a part of the typescript migration.

But for the time being, I think if we want to fix this one instance we should fix them all.
