### ISSUE TITLE
Add tooltips and hints to swap page

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#428]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
   - Add tooltips and information about the changelly refund address, and other semi-intuitive aspects of the swap page.
  - What are the current issues this feature will solve
    - Confusion regarding what something does or the reason for something.

**Comment by gamalielhere** [comment]
bump
