### ISSUE TITLE
Interact with contract: field name cut off on smaller screen

### ISSUE THREAD

**Issue by KatyaMik** [MyEtherWallet/MyEtherWallet#429]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
 "Contract address" field name cut off when viewing at default browser zoom setting on smaller screen

<img width="1273" alt="screen shot 2019-01-10 at 3 02 00 pm" src="https://user-images.githubusercontent.com/46572881/51005326-32004e00-14f3-11e9-8828-7e21e60fbbd2.png">

  - What is the expected behavior?
full field name visible

**Comment by hsurf22** [comment]
Fixed

**Comment by hsurf22** [comment]
Fixed
