### ISSUE TITLE
Nodes list looks uneven and missing icons/logos

### ISSUE THREAD

**Issue by KatyaMik** [MyEtherWallet/MyEtherWallet#431]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
nodes list not aligned, missing icons

<img width="580" alt="screen shot 2019-01-10 at 3 02 57 pm" src="https://user-images.githubusercontent.com/46572881/51005520-016ce400-14f4-11e9-8704-fc19fca5f7ba.png">
<img width="596" alt="screen shot 2019-01-10 at 3 03 07 pm" src="https://user-images.githubusercontent.com/46572881/51005525-05006b00-14f4-11e9-91ef-1644f57e9326.png">

  - What is the expected behavior?

**Comment by hsurf22** [comment]
Fixed
35c9db1335e1331dd96c5d3fc5de99b704cd01af

**Comment by hsurf22** [comment]
35c9db1335e1331dd96c5d3fc5de99b704cd01af
