### ISSUE TITLE
Integrated MEW into the custom application, connection with Ethereum chain stops working regardless BSC and Polygon chain still connects 

### ISSUE THREAD

**Issue by sobi983** [MyEtherWallet/MyEtherWallet#4334]
Have anyone worked with MyEtherWallet( MEW ) integration to the mobile application?

I did the integration the MEW into the custom mobile application. It has been working fine for years but now it has stopped working for the Ethereum network, other networks are working fine( BSC, Polygon).

The problem I am facing is a connection error while connecting through the application to my DAPP.
![Screenshot 2022-10-21 180014](https://user-images.githubusercontent.com/71635873/198578695-5393b3ea-553a-4e81-b302-fa6c20fb5823.png)

**Comment by gamalielhere** [comment]
We have removed support for MEWConnect. Please use WalletConnect V2 instead.
