### ISSUE TITLE
Access via BitBox01 is needed. MEW v5?

### ISSUE THREAD

**Issue by Tatz884** [MyEtherWallet/MyEtherWallet#4374]
I need to access MEW via BitBox01.

MEW v6 has ended the BitBox01 support. MEW v5 seems to allow access via BitBox01 (#3340 #3255), but v5 seems to have been removed.

Could someone deploy v5 again?

I stored a considerable amount of ETH, and I want to recover it.

Big thank you.

**Comment by gamalielhere** [comment]
you can pull the repo and use v5/master to try and get out your ETH, although you may need to change the nodes for it to work
