### ISSUE TITLE
Hardware wallet Network and Derivation Path re-sizing issue

### ISSUE THREAD

**Issue by stephenmew** [MyEtherWallet/MyEtherWallet#441]
- **I'm submitting a ...**

  - [ ] Feature request
  - [X] Bug report

- **Bug Report**
  - What is the current behavior?

On Trezor access wallet screen, after connecting the Trezor, Network and Derivation path categories look fine on full screen. But when you make the browser window smaller, both categories turn from the deep blue we know and love to a very bright, obnoxious blue and look glitch-y.

Before: 
![screenshot 89](https://user-images.githubusercontent.com/37165338/51055229-2022b780-1594-11e9-9508-e138c2b3ee8e.png)

After:
![screenshot 90](https://user-images.githubusercontent.com/37165338/51055234-244ed500-1594-11e9-8187-a68bcfe7a019.png)

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Make the browser window thinner.

  - What is the expected behavior?

The categories stay the same, or change in a more intuitive way.

  - What is the motivation / use case for changing the behavior?

The categories as-is do not make much sense, and look as if they don't work.

  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

https://beta.myetherwallet.com/access-my-wallet under the Trezor option

I don't know if it's the same for Ledger/other hardware wallets. But I only saw it on Trezor thus far.

**Comment by stephenmew** [comment]
@hsurf22

**Comment by kvhnuke** [comment]
@hsurf22 ping!

**Comment by hsurf22** [comment]
Fixed
