### ISSUE TITLE
Separate "Send Offline" as one step

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#442]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/51055502-e0100480-1594-11e9-9e0f-b552afeb9229.png)
- **Feature Request**
  - Briefly explain the feature you would like us to implement
Keep just one step in "Send Offline"

**Comment by kvhnuke** [comment]
I believe @hsurf22 already working on this!

**Comment by kvhnuke** [comment]
completed in #570
