### ISSUE TITLE
BitBox02 unable to connect to MEW

### ISSUE THREAD

**Issue by jadzeidan** [MyEtherWallet/MyEtherWallet#4423]
###### Info

- **Version**: v6.6.11-hotfix.2
- **Browser**: Chrome/Firefox etc.
- **OS**: Windows
- **Page Url**: https://www.myetherwallet.com/wallet/access/hardware?type=overview

###### Overview

BitBox02 users have recently started reporting they are unable to connect to MEW. I have tested myself, I was able to connect like normal the first time but after trying again I am no longer able to connect. This also happens even if there is no other connection to the BitBox02 happening at the same time, which is usually the issue when not being able to connect to MEW. But now that doesn't seem to be the case. I have not been able to find a work around either.

###### Steps to reproduce

- Click "BitBox02"
- Prompted with following screen:
![image](https://user-images.githubusercontent.com/42831937/207167836-feb1591c-947b-49c8-bf79-f3340d5595ef.png)
- Clicking "Unlock BitBox02" results in following error:
![image](https://user-images.githubusercontent.com/42831937/207168013-af564ff0-03f9-4974-ae58-fceb5a34726d.png)

###### What do you expect to happen?

It is expected the BitBox02 will prompt you to enter the password and then log in to MEW like normal.

###### What happens instead?

Get an error instead. BitBox02 doesn't prompt

###### Screenshot

Here is the error in the console:
![image](https://user-images.githubusercontent.com/42831937/207168744-66fbf82e-1ab3-4696-bc6e-17bcd9fb8743.png)

**Comment by jcreyesb** [comment]
Version: v6.6.11-hotfix.2
Browser: Chrome/Firefox etc.
OS: Linux Debian
Page Url: https://www.myetherwallet.com/wallet/access/hardware?type=overview

I got same error.

**Comment by gamalielhere** [comment]
@jadzeidan @jcreyesb this will be fixed in the next release, you can currently try it out at https://develop.mewbuilds.com/wallet/access
