### ISSUE TITLE
Can MEW be used without browser extensions?

### ISSUE THREAD

**Issue by zilveer** [MyEtherWallet/MyEtherWallet#4453]
Hi,
My main question is if My Ether Wallet can be used without browser extensions?

Can I just download the repo and open index.html file and run it locally ?

Edit:
I want to run this locally without installing anything. I would like to open a html file and run it basically,  is this possible?

Regards Zilveer

**Comment by Akshay-sachu** [comment]
did u opened the file with extension?

**Comment by gamalielhere** [comment]
@zilveer yes, you can download the offline version and do that
