### ISSUE TITLE
Hide unsuitable menu options

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#451]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Some features are not available or suitable for certain networks. So, it would be useful to hide those features by configuration in order to avoid usability problems.

**Comment by hsurf22** [comment]
Fixed

**Comment by alepc253** [comment]
@hsurf22 where can I find this fix?
