### ISSUE TITLE
Tie all modals into one global container

### ISSUE THREAD

**Issue by gamalielhere** [MyEtherWallet/MyEtherWallet#453]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
    Place all modals into one container to avoid repetition of instantiating modals.
  - What are the current issues this feature will solve
     avoids repetition of instantiating modals that are reused.

Note: This probably should also tie in to using the eventHub to call all these modals.

**Comment by kvhnuke** [comment]
Also, we have to standadize the data we pass between modals
for example if it is tx it should be an instance `ethereumjs-tx`
if it  is a number it should be an instance of `bignumber.js` ..etc
