### ISSUE TITLE
can't install package

### ISSUE THREAD

**Issue by FatNerdPeng** [MyEtherWallet/MyEtherWallet#4555]
###### Info

- **Version**: 
-      node: 14.21.3
-      npm: 6.14.18
                      
- **OS**: Windows 11

###### Steps to reproduce

1.I pulled project:
      ```git clone ...```
2.Then I try to install the package according to the readme.md:
    ```npm ci```
    then encountered a problem:
   
![image](https://user-images.githubusercontent.com/33616855/224207266-d13b2bf3-1403-448d-8bc6-19cf3f212959.png)

3.I searched for ways to solve the error,it is said that it should be implemented first ```npm install``` so I did and then I have encountered a new problem:
![image](https://user-images.githubusercontent.com/33616855/224208271-7eec23f5-ed44-4522-bdbe-44f2173ec899.png)
It is said that I cannot open a project with vs code so I opened the project by git-bash and try again,and then I have encountered a new problem:
![image](https://user-images.githubusercontent.com/33616855/224211076-13468e20-01c5-452e-aca3-c24ba82c2370.png)
This error seems to be the lack of some building tools,but my computer has python and visual studio,So I don't know where the problem is and what to do

###### What do you expect to happen?

install the package and run the project

Thanks!

**Comment by FatNerdPeng** [comment]
After a month of experience, I finally successfully ran this project locally. Below, I will share my footstep records, which may be helpful to others. Due to stepping on too many pits, I narrated them in chapters using the style of a novel.

Chapter 1 Install Package - Section 1：

After you clone this project and execute the ```npm ci``` command, the following error you may encounter:
![image](https://user-images.githubusercontent.com/33616855/230869294-017db626-3322-4573-b963-7dd5383a43f1.png)
or
![image](https://user-images.githubusercontent.com/33616855/230869928-e78c7d38-417a-487b-8859-58aa42048b70.png)
I guess the reason for this issue is that some libraries in your package. json and package lock. json do not match, so you need to update your package lock. json,next.

**Comment by ItsLuized** [comment]
Any comment on how you fixed it?

**Comment by FatNerdPeng** [comment]
I recorded my process of solving this problem to help those in need

1.
Firstly, you need to use node v12 or v14. I forgot which version I used successfully. It's been some time since this issue passed, so you can try everything. After you modify your node version, you need to change the corresponding NPM version. There are no specific requirements for the NPM version, which can be adapted to your node version.

2.
After changing the node version, the first possible issue you may encounter is as shown in the above figure. You cannot execute the ```npm ci``` command, which will prompt that your package lock.json file and the library used in package. json need to be the same version. Therefore, you need to first execute the ```npm update --save-dev``` command to update your package. json. It should be noted here that because devDependencies are useful in package.json, many of the library versions are very old (such as babel), which can cause various strange problems. Therefore, you need to execute ```npm update -- save-dev``` instead of ```npm update``` to update the libraries in devDependencies

**Comment by FatNerdPeng** [comment]
3. 
When you execute the ```npm update --save-dev```command, you may encounter the problem shown in the second image above, which is that you cannot execute the npm command in VS code. At this point, you need to use git bash to open your project instead of using vs code

**Comment by FatNerdPeng** [comment]
Supplement: 
Regarding 2, the option 'resolutions' is available in package.json, which locks the versions of the libraries in it. These libraries are also very old and the ```npm update --save-dev``` command will not update them. When I was about to run this project, the version of the library in resolutions caused me to fail, so you need to delete this option. 

By the way, because my country has a firewall and is not very friendly in accessing Github's servers, when installing Github's repository instead of NPM's repository, the problem shown in the following figure always appears,such as:
![image](https://user-images.githubusercontent.com/33616855/233955609-32646a2e-2146-4938-ada4-285659a3daa3.png)
the following issues will always appear:
![image](https://user-images.githubusercontent.com/33616855/233955781-b6463d6f-2243-4ed8-9af0-9a355a67bbd2.png)
![image](https://user-images.githubusercontent.com/33616855/233956043-bc37a3b4-f073-4c9b-b922-20876df09a22.png)
I won't give any examples of other libraries installed from Github, but the solution is the same: download from NPM instead of Github:
![image](https://user-images.githubusercontent.com/33616855/233958405-e233a4fd-178e-412b-952e-4765e0bacd14.png)
If your country has good access to Github's services, ignore this issue.

Another issue with package.json is that you may encounter problems with Babel when working due to many library updates that have transitioned from CommonJS to ESM. Solving ESM issues requires Babel v7 or higher, and this library is no longer called Babel core but renamed @ Babel/core with many associated libraries such as @ Babel/cli. You need to change all of them to this
![image](https://user-images.githubusercontent.com/33616855/233957332-1eb01b38-e0bd-4f0f-b493-1f264753e78b.png)

In short, you need to modify many aspects of package.json. I will showcase my successful package.json here for your reference:

{
  "name": "myetherwallet",
  "version": "6.6.16-hotfix.1",
  "description": "Client side ethereum wallet",
  "scripts": {
    "build": "npm run update && vue-cli-service build",
    "test:e2e": "vue-cli-service test:e2e --skiptags offline",
    "test:e2e-offline": "BUILD=offline vue-cli-service test:e2e --tag offline",
    "lint": "npm run lint:code && npm run lint:md",
    "apollo": "apollo",
    "apollo:aave": "apollo service:download -c=apolloAave.config.js src/dapps/aave-dapp/apollo/schemas/api.json && apollo client:codegen -c=apolloAave.config.js src/dapps/aave-dapp/apollo/global/globalTypes.json --target=json",
    "apollo:codegen": "npm run apollo:schema && apollo client:codegen src/apollo/global/globalTypes.json --target=json",
    "apollo:schema": "apollo service:download src/apollo/schemas/api.json",
    "build:hash": "ROUTER_MODE=hash npm run build",
    "build:history": "ROUTER_MODE=history npm run build",
    "build:history:sourcemaps": "ROUTER_MODE=history FULL_SOURCEMAPS=true npm run build",
    "build:offline": "WEBPACK_INTEGRITY=false BUILD=offline npm run build:hash",
    "codecov": "npm run test && codecov",
    "dev": "npm run update && npm run juststart",
    "juststart": "vue-cli-service serve --watch",
    "juststart:offline": "ROUTER_MODE=hash BUILD=offline vue-cli-service serve --watch",
    "lint:code": "vue-cli-service lint --fix",
    "lint:md": "remark . -o",
    "lint:styles": "prettier --write 'src/**/*.{scss,css}' && stylelint 'src/**/*.{scss,css}' --fix",
    "lint:tests": "eslint --fix tests/",
    "preinstall": "find node_modules -name \".git\" -exec rm -rf {} \\; || true && bash ./scripts/checklockconflicts.sh && npx npm-force-resolutions",
    "start": "npm run update:mainlists && npm run dev",
    "start:history": "npm run update:mainlists && ROUTER_MODE=history npm run dev",
    "start:offline": "npm run update:mainlists && ROUTER_MODE=hash BUILD=offline npm run dev",
    "test": "npm run update:lists && jest --clearCache && npm run test:unit",
    "update": "npm run update:packages && npm run update:lists",
    "update:lists": "node fetchLists/index.js",
    "update:mainlists": "node fetchLists/fetchMainLists.js",
    "update:packages": "node package-test.js"
  },
  "dependencies": {
    "@aave/contract-helpers": "1.7.0",
    "@aave/math-utils": "1.7.0",
    "@aave/protocol-js": "4.3.0",
    "@actions/github": "5.1.1",
    "@coolwallet/bsc": "1.1.6",
    "@coolwallet/core": "1.1.16",
    "@coolwallet/eth": "1.1.12",
    "@coolwallet/transport-web-ble": "1.1.3",
    "@coolwallets/eth": "0.2.0-beta.1",
    "@coolwallets/transport-web-ble": "0.1.0",
    "@coolwallets/wallet": "0.2.0-beta.1",
    "@ensdomains/address-encoder": "0.2.20",
    "@ensdomains/ens-contracts": "0.0.17",
    "@ensdomains/ensjs": "2.1.0",
    "@ethereumjs/common": "2.6.5",
    "@ethereumjs/tx": "3.5.2",
    "@formatjs/intl-numberformat": "8.3.5",
    "@kleros/address-tags-sdk": "0.2.0",
    "@lokalise/node-api": "8.0.1",
    "@mathieustan/vue-intercom": "0.0.9",
    "@myetherwallet/eth2-keystore": "0.3.0",
    "@myetherwallet/mew-components": "1.4.5",
    "@openzeppelin/contracts": "4.8.2",
    "@sentry/browser": "7.28.1",
    "@sentry/tracing": "7.28.1",
    "@sentry/vue": "7.28.1",
    "@unstoppabledomains/resolution": "8.3.3",
    "@walletconnect/client": "1.8.0",
    "@walletconnect/qrcode-modal": "1.8.0",
    "animejs": "3.2.1",
    "apollo-cache-inmemory": "1.6.6",
    "apollo-client": "2.6.10",
    "apollo-link": "1.2.14",
    "apollo-link-error": "1.1.13",
    "apollo-link-http": "1.5.17",
    "apollo-link-rest": "0.9.0",
    "apollo-link-ws": "1.0.20",
    "apollo-utilities": "1.3.4",
    "axios": "1.3.4",
    "bitbox02-api": "0.15.0",
    "bl": "6.0.1",
    "buffer": "6.0.3",
    "clipboard-copy": "4.0.1",
    "cryptiles": "4.1.3",
    "crypto": "1.0.1",
    "crypto-browserify": "3.12.0",
    "diff": "5.1.0",
    "dns-packet": "5.5.0",
    "ejs": "3.1.9",
    "elliptic": "6.5.4",
    "engine.io": "6.4.1",
    "ethereum-block-by-date": "1.4.6",
    "ethers": "5.7.2",
    "follow-redirects": "1.15.2",
    "glob-parent": "6.0.2",
    "graphql": "15.5.3",
    "graphql-tag": "2.12.6",
    "handlebars": "4.7.7",
    "highcharts": "10.3.3",
    "highcharts-vue": "1.4.0",
    "hmac-drbg": "1.0.1",
    "json5": "2.2.3",
    "keccak": "3.0.3",
    "keccak256": "1.0.6",
    "lodash": "4.17.21",
    "lottie-web": "5.10.2",
    "minimalistic-crypto-utils": "1.0.1",
    "minimatch": "8.0.3",
    "moment": "2.29.4",
    "node-forge": "1.3.1",
    "node-polyfill-webpack-plugin": "2.0.1",
    "normalize-url": "8.0.0",
    "os-browserify": "0.3.0",
    "package-json": "7.0.0",
    "parse-path": "7.0.0",
    "parse-url": "8.1.0",
    "patch-package": "6.5.1",
    "platform": "1.3.6",
    "qrcode-with-logos": "1.0.3",
    "register-service-worker": "1.7.2",
    "scrypt.js": "0.3.0",
    "shelljs": "0.8.5",
    "simple-get": "4.0.1",
    "socket.io-parser": "4.2.2",
    "stream": "0.0.2",
    "subscriptions-transport-ws": "0.11.0",
    "terser": "5.16.8",
    "trim-newlines": "5.0.0",
    "url-parse": "1.5.10",
    "vue": "2.6.14",
    "vue-apollo": "3.1.0",
    "vue-lazyload": "1.3.4",
    "vue-router": "3.5.3",
    "vue-social-sharing": "3.0.9",
    "vuedraggable": "2.24.3",
    "vuex": "3.6.2",
    "walletlink": "2.5.0",
    "xmlhttprequest-ssl": "2.1.0",
    "y18n": "5.0.8"
  },
  "devDependencies": {
    "@babel/cli": "7.21.0",
    "@babel/core": "7.21.4",
    "@babel/eslint-parser": "7.21.3",
    "@babel/preset-env": "7.21.4",
    "@commitlint/config-conventional": "17.4.3",
    "@ledgerhq/hw-app-eth": "6.30.0",
    "@ledgerhq/hw-transport-web-ble": "6.27.1",
    "@ledgerhq/hw-transport-webusb": "6.27.1",
    "@ledgerhq/live-common": "27.7.0",
    "@mdi/font": "7.2.96",
    "@shapeshiftoss/hdwallet-core": "1.46.1",
    "@shapeshiftoss/hdwallet-keepkey": "1.46.1",
    "@shapeshiftoss/hdwallet-keepkey-webusb": "1.46.1",
    "@vue/babel-preset-app": "5.0.8",
    "@vue/cli-plugin-babel": "5.0.8",
    "@vue/cli-plugin-e2e-nightwatch": "5.0.6",
    "@vue/cli-plugin-eslint": "5.0.8",
    "@vue/cli-plugin-pwa": "5.0.8",
    "@vue/cli-plugin-unit-jest": "5.0.8",
    "@vue/cli-service": "5.0.8",
    "@vue/eslint-config-prettier": "7.1.0",
    "@vue/test-utils": "1.3.0",
    "apollo": "2.34.0",
    "axios": "0.27.2",
    "babel-eslint": "10.1.0",
    "babel-jest": "29.4.3",
    "bc-vault-js": "2.1.1",
    "bignumber.js": "9.1.1",
    "bip39": "3.0.4",
    "chromedriver": "104.0.0",
    "codecov": "3.8.3",
    "commitlint": "17.4.3",
    "copy-webpack-plugin": "11.0.0",
    "eslint": "7.32.0",
    "eslint-plugin-prettier": "4.2.1",
    "eslint-plugin-security": "1.7.1",
    "eslint-plugin-vue": "9.0.1",
    "ethereumjs-util": "7.1.5",
    "ethereumjs-wallet": "1.0.2",
    "geckodriver": "3.2.0",
    "hdkey": "2.1.0",
    "husky": "5.0.9",
    "imagemin-mozjpeg": "9.0.0",
    "imagemin-webpack-plugin": "2.4.2",
    "is-ipfs": "6.0.2",
    "jest-skipped-reporter": "0.0.5",
    "minizlib": "2.1.2",
    "multicoin-address-validator": "0.5.12",
    "node-fetch": "2.6.7",
    "node-sass": "7.0.3",
    "postcss": "8.4.21",
    "postcss-cli": "10.1.0",
    "postcss-import": "12.0.1",
    "postcss-url": "8.0.0",
    "prettier": "2.8.0",
    "protobufjs": "7.2.3",
    "raw-loader": "4.0.2",
    "remark-cli": "10.0.0",
    "remark-preset-lint-recommended": "6.1.2",
    "sass": "1.34.1",
    "sass-loader": "10.1.1",
    "simple-get": "4.0.1",
    "store": "2.0.12",
    "stylelint": "14.8.2",
    "stylelint-config-prettier": "9.0.4",
    "stylelint-config-standard": "25.0.0",
    "trezor-connect": "8.2.12",
    "u2f-api": "1.2.1",
    "uglify-es": "3.3.9",
    "uuid": "9.0.0",
    "vue-cli-plugin-vuetify": "2.5.8",
    "vue-i18n": "8.27.0",
    "vue-matomo": "4.2.0",
    "vue-template-compiler": "2.6.14",
    "vuetify": "2.5.9",
    "web3": "1.5.0",
    "web3-core-helpers": "1.5.0",
    "web3-core-method": "1.5.0",
    "web3-core-requestmanager": "1.5.0",
    "web3-eth-contract": "1.5.0",
    "web3-utils": "1.5.0",
    "webpack": "5.76.3",
    "webpack-bundle-analyzer": "4.8.0",
    "xss": "1.0.14"
  },
  "engines": {
    "node": ">= 10.0.0 < 12.3.0",
    "npm": ">= 6.0.0"
  },
  "license": "MIT",
  "repository": "https://github.com/myetherwallet/myetherwallet"
}

**Comment by FatNerdPeng** [comment]
4
Okay, now let's continue. When you execute the ```npm update --save-dev``` command, you may encounter the problem with the third image I showed at the top. Here's an explanation. The general meaning of this issue is that your Windows system lacks C++building tools or Visual Studio, or other necessary tools for this project. That is to say, if you are not using a Windows system, you may not have this problem. If you are using a Windows system and have successfully encountered this issue, then continue to read on.

Firstly, you need to execute ```npm install --global --production windows-build-tools```. Executing this command generally does not lead to a smooth installation, and you may encounter various strange problems. However, Google or ChatGPT can search for solutions to these problems, so I won't mention them here. Here I want to say that you need to install the version of Visual Studio 2017:
![image](https://user-images.githubusercontent.com/33616855/233963814-d12578fd-c0a6-40f1-af98-0d09c4d0eb58.png)
Other versions may have issues, such as the Visual Studio 15 version I tried, which will report this error:
![image](https://user-images.githubusercontent.com/33616855/233963967-730c2cc3-2a52-4efd-b949-2f1b52d2c991.png)

**Comment by FatNerdPeng** [comment]
6
Now that we have successfully installed the dependency, I did not execute the ```npm run build``` because I do not need to package at the moment. I executed the ```npm start``` command and reported an error. I did not find a screenshot of the error here to roughly explain, because the ```npm start``` command executed this:
![image](https://user-images.githubusercontent.com/33616855/233975562-e6e61495-3af3-430d-8527-df3eef8c3264.png)
The problem lies in this index.js file, as it contains a lot of code to pull requests from github:
![image](https://user-images.githubusercontent.com/33616855/233975795-b46b923f-31c6-496e-8702-7f22b2189815.png)
That's how I solved it. I annotate the code related to the request, then access the request address from the browser to obtain the corresponding JSON files, save these files in the project, and modify the corresponding import code where these files are used.Okay, that's it.

**Comment by FatNerdPeng** [comment]
@ItsLuized After resolving these issues, I successfully ran this project. I hope my records will be helpful to you.

**Comment by 7-Qin** [comment]
> @ItsLuized After resolving these issues, I successfully ran this project. I hope my records will be helpful to you.

大佬好厉害呀！我还是在有npm run dev不成功的问题，可以微信上继续请教您嘛？
可以有偿的。加一下我的微信吧：ChuciQin
谢谢大佬！！！

**Comment by FatNerdPeng** [comment]
> > @ItsLuized After resolving these issues, I successfully ran this project. I hope my records will be helpful to you.
> 
> 大佬好厉害呀！我还是在有npm run dev不成功的问题，可以微信上继续请教您嘛？ 可以有偿的。加一下我的微信吧：ChuciQin 谢谢大佬！！！

我不加VX，你有问题直接在这里提出来，如果我看到了会抽空回答的。但你不要太抱期待，因为这个问题有点难搞定，每个人情况不一样。
