### ISSUE TITLE
BitBox doesn't connect, Can't get past 'Enter password' screen.

### ISSUE THREAD

**Issue by stephenmew** [MyEtherWallet/MyEtherWallet#456]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

Digital BitBox won't connect on Beta, works fine on current MEW V3. 

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Connect BitBox -> Access My Wallet -> Hardware -> BitBox

Enter incorrect password, nothing happens. 
Enter correct password, nothing happens. 

Cannot get past the password step.

  - What is the expected behavior?

Should connect to BitBox and show a list of ETH addresses, like other hardware wallets.

  - What is the motivation / use case for changing the behavior?

To use BitBox.

  - Please tell us about your environment:
    - Operating system

Windows 7

    - Browser and version

Chrome

**Comment by kvhnuke** [comment]
closing since this will work in production domain `www.myetherwallet.com`
