### ISSUE TITLE
Get HMR working

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#46]
Right now any change to a component forces a reload from HMR, apparently not knowing how to update. Looks like we're on react-hot-loader v3 (beta) which says that the hot loading API is no longer handled automatically, and that we need to manually hook it up: https://github.com/gaearon/react-hot-loader/tree/master/docs#migration-to-30. See the notes about `<AppContainer/>` and `module.hot.accept`.

I was unable to get this working by specifically specifying dependencies in `common/index.js`, i.e.

```diff
if (module.hot) {
+  module.hot.accept('components', () => renderRoot(Root));

  module.hot.accept('reducers/index', () =>
    store.replaceReducer(require('reducers/index').default)
  );
}
```

however I _was_ able to get it working by simply doing a blanket accept, and letting `<AppContainer/>` do its thing. However, this seemed potentially dangerous, as I don't really know what this is doing WRT the redux store or component state:

```diff
if (module.hot) {
+  module.hot.accept();

  module.hot.accept('reducers/index', () =>
    store.replaceReducer(require('reducers/index').default)
  );
}
```

**Comment by crptm** [comment]
``` 
module.hot.accept('./routing', () => {
    const Routing = require('./routing').Routing;
    renderRoot(Root, Routing);
  });
```

sorta works for me

**Comment by wbobeirne** [comment]
Ah I wondered if there was something weird about Routing being a pure render function. I might play with making it a proper React class to see if that can work. Thanks for the tip.

**Comment by crptm** [comment]
Problem is Root isnt requiring updated modules, so you have to listen/re-require ./routing
