### ISSUE TITLE
/interface/dapps/register-domain/auction page issue

### ISSUE THREAD

**Issue by hsurf22** [MyEtherWallet/MyEtherWallet#460]
- **Bug Report**
  - What is the current behavior?
     On the /interface/dapps/register-domain/auction page, after user refresh the page, they should be re directed to the /interface/dapps/ this page since domain name has been deleted.

i added these codes and keep getting error message while I'm doing commit to github.

![screenshot from 2019-01-14 20-35-25](https://user-images.githubusercontent.com/9893774/51159066-0dcaa700-183c-11e9-92e9-75afa135e561.png)

![screenshot from 2019-01-14 20-35-41](https://user-images.githubusercontent.com/9893774/51159069-17540f00-183c-11e9-90b4-129aef3a67e9.png)

**Comment by hsurf22** [comment]
This code is in
EnsBidContainer.vue

**Comment by gamalielhere** [comment]
you commented out the tested code. this isn't a github issue.
