### ISSUE TITLE
Add Indication of the connection state for MEWconnect

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#467]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
    - There is no indication of the connection state with regards to MEWconnect
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
   - Connect with MEWconnect and then disconnect via the mobile app.
  - What is the expected behavior?
    - The site indicates whether a connection to the MEWconnect app exists.
  - What is the motivation / use case for changing the behavior?
    - Better UI

**Comment by jackhuangusa** [comment]
![image](https://user-images.githubusercontent.com/31494364/51221354-f77d2380-18ed-11e9-876f-57702649cfe6.png)

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/pull/635
Done
