### ISSUE TITLE
Gas Price Discrepancy in MEW Offline Transaction

### ISSUE THREAD

**Issue by booletic** [MyEtherWallet/MyEtherWallet#4681]
###### Info

- **Version**: MyEtherWallet v6.7.5
- **Browser**: Firefox
- **OS**: Linux
- **Page Url**: N/A

###### Steps to reproduce

1. Initiated an offline transaction through MyEtherWallet (MEW).
2. Manually set the gas price to 22 Gwei during the transaction.
3. Generated the transaction.

###### What do you expect to happen?

I expect the generated transaction to reflect the manually set gas price of 22 Gwei accurately.

###### What happens instead?

The generated transaction displays a gas price of 22000000000, which is significantly higher than the intended 22 Gwei, raising concerns about its accuracy and potential overpayment.

###### Screenshot

![unnamed](https://github.com/MyEtherWallet/MyEtherWallet/assets/8014935/6cc34acd-f9c9-4422-b231-107e3614ad9c)

**Comment by gamalielhere** [comment]
@booletic raw transaction displays gas price in wei instead of gwei. you can verify that on our convertion tool: https://www.myetherwallet.com/tools?tool=convert
