### ISSUE TITLE
Why is the mobile app not open source?

### ISSUE THREAD

**Issue by jcw1tjjrdhv3** [MyEtherWallet/MyEtherWallet#4687]
In the project's readme it says in bold: **Open source & auditable**.  And just below that there are two links to the closed source mobile app without any warnings. The app is also heavily advertised on the website. Please publish the source code for the mobile app or add a huge warning for users (on the website and in the project's readme) saying that the app shouldn't be used to deal with any significant amounts of money because the source code is not available yet (you do plan to publish it, right?).

TBH, this discovery is a huge red flag for me and it looks like you're trying to hide something. I don't plan to use a mobile app anyway, but I'm now not sure if I should trust the project at all.

Please don't close this issue until it's resolved.

**Comment by gamalielhere** [comment]
The project that is open source is the Web App. The mobile app is a separate product.

**Comment by jcw1tjjrdhv3** [comment]
I guess that means that there are no plans to make the mobile app open source. It's advertised as "the official MyEtherWallet app" on the MyEtherWallet website, so both the mobile and web apps are parts of the same project. There are two reasons to make a proprietary cryptocurrency wallet: either people making it are incompetent, or they have malicious intents. In any case that means that this whole project cannot be trusted.
