### ISSUE TITLE
WalletConnect V2 Registry Universal link fails due to expired SSL

### ISSUE THREAD

**Issue by PaulUD** [MyEtherWallet/MyEtherWallet#4713]
###### Info

- **Version**: 2.3.7
- **Browser**: Safari
- **OS**: iOS
- **Page Url**: https://mewetherwallet.com/wc

###### Steps to reproduce

Screenshot of expired SSL when using the MEW WalletConnect V2 Registry Universal link (shown as Page URL above)
Even when we add the www. prefix (which does have SSL) we still get the same error.

###### What do you expect to happen?

Universal link to have valid SSL

###### What happens instead?

See screenshot

###### Screenshot
![image](https://github.com/MyEtherWallet/MyEtherWallet/assets/60640581/5c56a0f0-8497-48af-9d5c-68830a131e62)

```

**Comment by gamalielhere** [comment]
this has been fixed.
