### ISSUE TITLE
Offline mode doesn't work

### ISSUE THREAD

**Issue by safonik** [MyEtherWallet/MyEtherWallet#4744]
###### Info

- **Version**: 6.7.8-Offline
- **Browser**: Chrome, Firefox
- **OS**: Any

###### Steps to reproduce
1. Open index.html
2. Click on the button "Keystore files, Mnemonic phrase, Private key"
3. Nothing happens and get an error in console: this.$amplitude is undefined

**Comment by Abinash018** [comment]
**hy , please asign me i want to contribute to your  project**

**Comment by jm9151821** [comment]
> ###### Info
> * **Version**: 6.7.8-Offline
> * **Browser**: Chrome, Firefox
> * **OS**: Any
> 
> ###### Steps to reproduce
> 1. Open index.html
> 2. Click on the button "Keystore files, Mnemonic phrase, Private key"
> 3. Nothing happens and get an error in console: this.$amplitude is undefined

They mention MEW offline is only available in version 5 
![image](https://github.com/MyEtherWallet/MyEtherWallet/assets/32444279/1b84a07c-9d15-44e7-a171-74eadb6821a7)
https://help.myetherwallet.com/en/collections/3043288-mew-offline
