### ISSUE TITLE
Offline mode click is invalid

### ISSUE THREAD

**Issue by CoxxA** [MyEtherWallet/MyEtherWallet#4800]
Info
* Version: [MyEtherWallet-v6.8.1-Offline.zip
* Browser: Chrome, Firefox
* OS: Any
Steps to reproduce
1. Open index.html
2. Click on the button "Keystore files, Mnemonic phrase, Private key"
3. Nothing happens and get an error in console: this.$amplitude is undefined

**Comment by NukeManDan** [comment]
Same here, sadly.
![image](https://github.com/MyEtherWallet/MyEtherWallet/assets/35669742/7e8aa5f8-101b-4986-8428-05640ed53bd2)
