### ISSUE TITLE
Offline mode doesn't work

### ISSUE THREAD

**Issue by jt-aztech** [MyEtherWallet/MyEtherWallet#4830]
###### Info

- **Version**:MyEtherWallet v6.9.1
- **Browser**: firefox
- **OS**: Linux

###### Steps to reproduce

In Qubes OS and in a VM which doesn't have a network configured(offline VM) open index.html in firefox, this produces a blank page.

Furthermore, when I do this in a VM which has a network configured it does work. Even if 'n kill the internet connection for a VM with networking it still works even though there is no internet connection. It only doesn't work when the VM has no networking configured.

I've tested this on another ubuntu machine and it works even if there is no network but, on ubuntu ofcourse I cannot just remove my network card completely, so this only validates the second part of the above statement.

**Comment by JHGrove3** [comment]
I am having this problem, too.

I've spent the past 2-3 hours trying to fix it. Now I see it's not my fault at all.

I assumed somebody would have tested the Offline version in offline mode before distributing it.

**Comment by rlocke96** [comment]
Issue is tied to the use of fonts.googleapis.com. chunk-7b2afc50.9decabf5.css and chunk-41b7090a.c44ec400.css have the line
@import url(https://fonts.googleapis.com/css2?family=DM+Sans:ital,opsz,wght@0,9..40,200;0,9..40,300;0,9..40,400;0,9..40,500;0,9..40,600;0,9..40,700;0,9..40,800;0,9..40,900;1,9..40,400;1,9..40,500;1,9..40,600&display=swap);

If the machine is offline it fails to import which is causing the blank UI. Removing that line from those two files solved it for me.
