### ISSUE TITLE
Prevent network requests and handle UI for all components that won't work offline

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#484]
Some components require the network to work correctly. While they all may have error messages, it would be nice if we simply didn't request, and presented an offline UI instead. These components are:

* [ ] Swap (Currently spins infinitely)
* [ ] Equivalent values (Currently shows a generic "Failed to request rates" message)
* [ ] Broadcast Transaction (Currently functions as usual, "Failed to fetch" when you confirm)

All of these components should check against `state.config.offline` and render something else instead. Feel free to add any other places you find to the list above.

**Comment by dternyak** [comment]
As part of this implementation, we would likely want to check for online status as soon as possible instead of waiting for the user to navigate to the send tab.

**Comment by dternyak** [comment]
@wbobeirne Can this be closed? The new offline ux improvements should have this covered

**Comment by wbobeirne** [comment]
👍
