### ISSUE TITLE
App has analytics?!

### ISSUE THREAD

**Issue by nandlab** [MyEtherWallet/MyEtherWallet#4850]
The readme says:

> Private: No tracking!!! No emails. No ads. No demographics. We don't even know how many wallets have been generated, let alone who / what / where you are.

This is the [Exodus report](https://reports.exodus-privacy.eu.org/en/reports/com.myetherwallet.mewwallet/latest/) for the app:

![Exodus_MEW_trackers](https://github.com/MyEtherWallet/MyEtherWallet/assets/81931312/e8c3a1e2-5228-40e0-a44f-dee1e2ac41ae)

How do you explain this?!

**Comment by gamalielhere** [comment]
@nandlab you can read our privacy policy for this. None of our tracking stores any user identifying data.

**Comment by surfaceflinger** [comment]
@gamalielhere sure, but would it be possible to build the app without ANY trackers, no matter what type of data it collects?

**Comment by gamalielhere** [comment]
@surfaceflinger our offline build doesnt have tracking. Otherwise, you can clone the repo and create a build without the tracking at the moment.

**Comment by nandlab** [comment]
Why are you lying in the Readme?

**Comment by surfaceflinger** [comment]
> Why are you lying in the Readme?

> We use the analytics platform Amplitude to track visitor usage. Participation in usage tracking is optional and[...]

Check https://www.myetherwallet.com/ from incognito tab, you can see that the data collection is off by default at the bottom.

There's also sentry which I would prefer to avoid https://github.com/search?q=repo%3AMyEtherWallet%2FMyEtherWallet+sentry&type=code
but still, sentry is sane enough and isn't tracking, just errors collection, and I assume that it indeed just collects anonymized JS errors.

You can make an offline build and additionally setup CSP to whitelist which hosts your browser can connect to.

**Comment by surfaceflinger** [comment]
even better: https://github.com/MyEtherWallet/MyEtherWallet/blob/81241f84fd89cb1c242404beae88c5a192db4d54/builds/defaultConfig.js#L27-L29
you can just remove whatever you dont like from https://github.com/MyEtherWallet/MyEtherWallet/blob/81241f84fd89cb1c242404beae88c5a192db4d54/connections.js

**Comment by surfaceflinger** [comment]
Would be nice though if MEW could provide something like schizo.myetherwallet.com that would have literally everything that isn't interacting with ethereum/walletconnect completely blocked with no option to toggle it on
