### ISSUE TITLE
Fix the position of buttons 

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#487]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
![image](https://user-images.githubusercontent.com/31494364/51411131-9a66b500-1b1b-11e9-997c-b4f1f9d34e06.png)
"New Wallet" and "Access" buttons' position are too far away, and buttons are not the same size

  - What is the expected behavior?
![image](https://user-images.githubusercontent.com/31494364/51411236-f5001100-1b1b-11e9-9fdf-1c2ff6e53a8a.png)
Make these two buttons closer(6px), and adjust buttons as the same size.

**Comment by hsurf22** [comment]
Fixed
https://github.com/MyEtherWallet/MyEtherWallet/pull/496
