### ISSUE TITLE
MEW Card is broken offline

### ISSUE THREAD

**Issue by zer0cee** [MyEtherWallet/MyEtherWallet#4872]
###### Info

- **Version**: 6.9.4 and 6.9.3
- **Browser**: Firefox, Chrome, Edge
- **OS**: Windows, Mac
- **Page Url**: /wallet

###### Steps to reproduce
Download MEW 6.9.4
Go offline
Open offline account
Your MEW Card on the top left is broken
More importantly, when clicking the balanceCardQR button, the card that is displayed is totally broken

###### What do you expect to happen?

Expect to see the correct information about the loaded wallet

###### What happens instead?

Wallet info is not readable

###### Screenshot

![gfx](https://github.com/MyEtherWallet/MyEtherWallet/assets/75437411/0f79b8cc-eacc-47c0-ba8b-ec5671b3e027)
![gx2](https://github.com/MyEtherWallet/MyEtherWallet/assets/75437411/2ddb3926-dc06-4a0b-b534-512085612870)

**Comment by zer777** [comment]
I created a PR for this. Would be great if it were checked and released soon. @gamalielhere
