### ISSUE TITLE
RSK name resolution service integration 

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#489]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - RSK has **RNS**, it's own name service and first implementation of RIF protocols. Would be really good to have this feature integrated in MEW.

**Comment by kvhnuke** [comment]
Feature added https://github.com/MyEtherWallet/MyEtherWallet/commit/a80dbe49e34bfc4242143a8f84646d7ae94f4084
