### ISSUE TITLE
Spoofed notifications allowed from config import

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#492]
I'm reposting this from Hacker One. The Hacker One team screened it as not a relevant security issue, but I still feel it should _probably_ be fixed, but is safe to post in an open manner.

---

### Description

The configuration import file allows for notifications to be imported as well. This means that someone could upload a configuration file (potentially posing as an easy way to import useful tokens, networks, etc.) and include a notification that contained a malicious message. It has an especially sneaky effect of only showing up on subsequent visits to the page, since the notification isn't rendered immediately, making it seem a little more authentic.

My suggestion would be to either remove notification imports, or to disallow arbitrary content to be rendered in them (e.g. use a limited dictionary of error message of which the notification includes a key to.)

### Impact

Displaying an arbitrary message to the user that could be believed to come from MyEtherWallet.

### Steps To Reproduce

1.  Create a config file using the JSON in this gist: https://gist.github.com/wbobeirne/37ec71abee1c1383ee22fe863cc793e7
2.  Import the configuration file
3.  Refresh the page and unlock your wallet again, noting the new notification
4.  Open the notification and expand it, see the phishing message

### Supporting Material/References

See a screenshot of the notification here:

![](https://i.imgur.com/a7sr4v1.png)

---

After having it rejected and asked to state my case for why I thought it was a vulnerability, I added this description of using it as an attack vector:

> I defer to the MEW team (or your pre-screen) as to whether or not this is an issue worth fixing. The provided example in my original description is a way to get the interface to display a message to the user with an unclear understanding that the action the user performed (the configuration import) caused the notification, which I think could be used for phishing attempts.
>
> As an example, if I posted a guide that explained how to use add a custom token or network to MyEtherWallet, and my guide said to download and import a config file that secretly embedded one of these notifications, someone may follow the guide and later on be shown the spoofed notification.

**Comment by kvhnuke** [comment]
@wbobeirne thank you for the report. I am with you, this definitely should be fixed.
