### ISSUE TITLE
Add wallet using keystore, Error

### ISSUE THREAD

**Issue by Liquid00000000000** [MyEtherWallet/MyEtherWallet#4924]
I am trying to access my wallet using keystore file. The keystore is not from MEW.
it is from 2016 it was created by the geth ethereum wallet
when i put in the password it says - 

Key derivation failed - possibly wrong passphrase

Please help

**Comment by Admin661** [comment]
Is the issue resolved yet? You'll have to rectify with the mew loptimal weblink and try it again.

**Comment by gamalielhere** [comment]
@Liquid00000000000 that means the password you're inputting is wrong fro the keystore.
