### ISSUE TITLE
token digits doesn't show properly.

### ISSUE THREAD

**Issue by amukunn** [MyEtherWallet/MyEtherWallet#493]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**

Hi, we recently added {symbol:"CPT", name:"Contents Protocol Token"} to Ethereum-lists(https://github.com/MyEtherWallet/ethereum-lists/pull/915), and checked it's merged to master and released to MEW.
But on https://www.myetherwallet.com site, 
the token balance on MEW shows up 1000000000 times higher than the actual amount. Likewise, we need to add ten additional zeros when sending the token from MEW to other wallet to show the correct balance.
( We've set digit 18. )

How can I fix this?

**Comment by gamalielhere** [comment]
Closing this as this is the wrong repo. Here's the correct repo: https://github.com/kvhnuke/etherwallet/issues. But I'll be including this change for the new release.
