### ISSUE TITLE
Token Redesign

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#494]
- Flag will be set for each account address that is initially unlocked (flag will be the hash of the account address in local storage to protect info leakage via local storage).
- When flag is not present, request all default token balances and provide a UI for the user to choose which tokens he would like to monitor in the sidebar (default to all).
- When user enters token-choosing UI post-initial configuration and select additional token options, request balance for each token.
- User can activate token-choosing configurator to re-request all token balances to auto-discover all non-zero balances with helper button.

Notes:
- should significantly reduce backend load due to only requested "selected" tokens stored in LS after user configures which tokens they would like to monitor.

**Comment by dternyak** [comment]
@wbobeirne These mockups look great to me!

**Comment by wbobeirne** [comment]
This is merged into `transaction-refactor`, so I'm marking this closed, though it's not in develop yet.
