### ISSUE TITLE
Offline wallet generation does not work

### ISSUE THREAD

**Issue by AlxHnr** [MyEtherWallet/MyEtherWallet#4940]
###### Info

- **Version**: v6.9.8
- **Browser**: Firefox 126.0.1
- **OS**: Alpine Linux 3.20.0
- **Page Url**: index.html#/wallet/create

Also tested:

- **Browser**: Tor Browser 13.0.15
- **OS**: Tails 6.3
- **Page Url**: index.html#/wallet/create

###### Steps to reproduce

1. Download and unzip the offline release from https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.9.8
2. Start Firefox on a machine which is not connected to the internet
3. Navigate to your unzipped directory and open `index.html`
4. Click on the _"Create Wallet"_ link at the top

###### What do you expect to happen?

I get offered the option to create a software wallet like it is described in the help article under _"How to create a paper wallet using MEW offline"_ (scroll down): https://help.myetherwallet.com/en/articles/6167899-how-to-create-a-cold-wallet-a-k-a-paper-wallet

![Screenshot 2023-05-23 at 17 28 42](https://github.com/MyEtherWallet/MyEtherWallet/assets/8235638/ed9e63b5-0d8e-4fd7-9077-70f8bfe8ac03)

###### What happens instead?

There is no option to create a software wallet:

![Screenshot from 2024-06-13 04-55-01](https://github.com/MyEtherWallet/MyEtherWallet/assets/8235638/7acdbbde-5892-42a2-9593-4eee244dda8d)

###### Screenshot

-/-

###### Additional notes

Other features, like offline transaction signing, work just fine. But if wallets can't be generated offline, the idea of having an offline version makes no sense.

**Comment by kolAflash** [comment]
In [v6.9.7-hotfix.1](https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.9.7-hotfix.1) the `Create Wallet` feature was working fine.

In [v6.9.10](https://github.com/MyEtherWallet/MyEtherWallet/releases/tag/v6.9.10) the feature is still broken.

**Comment by AlxHnr** [comment]
I just tested v6.9.11-hotfix.1, both on Firefox/Alpine and Tor Browser/Tails. Works!
