### ISSUE TITLE
Sidebar acting funky

### ISSUE THREAD

**Issue by kvhnuke** [MyEtherWallet/MyEtherWallet#495]
- **I'm submitting a ...**
  - [x] Bug report

![chrome-capture](https://user-images.githubusercontent.com/10602065/51503618-c5a60a00-1d90-11e9-9aa5-3a7198c121d8.gif)

**Comment by gamalielhere** [comment]
Lmao. Literally fixed it this morning #494

**Comment by SteveMieskoski** [comment]
Fixed in PR #494
