### ISSUE TITLE
Offline.zip <-> Hash.zip <-> .zip differences in release downloads

### ISSUE THREAD

**Issue by kolAflash** [MyEtherWallet/MyEtherWallet#4964]
But can someone explain the differences between the different downloads in the [releases section](https://github.com/MyEtherWallet/MyEtherWallet/releases)?  
Ideally put that explanation in the `README.md`. Thanks :-)

` MyEtherWallet-v*-Hash.zip`  
`MyEtherWallet-v*-Offline.zip`  
` MyEtherWallet-v*.zip`

The only information I could was was this ([link](https://help.myetherwallet.com/en/articles/6512619-using-mew-offline)):  
_Note: If you want to use MEW offline to send a transaction from a software wallet, or to try canceling/replacing transaction by manually adjusting the nonce, please download that Offline.zip version of the files. To run MEW the same way as you do in the browser, but from your desktop, please download the Hash.zip version._

So I guess the Offline version is for [using MEW as a Cold Wallet (Paper Wallet)](https://help.myetherwallet.com/en/articles/6167899-how-to-create-a-cold-wallet-a-k-a-paper-wallet) and for manually tweaking transaction details. **Is this correct?**

Can the Hash version be used without internet connection?  
If yes, what's the difference to the Offline version?  
If no, why is it mentioned in the [MEW Offline](https://help.myetherwallet.com/en/articles/6512619-using-mew-offline) article?  
And why is it called Hash after all? Is there any meaning in the term "Hash" here?

And does the .zip version serve any other purpose than the Hash version, or is it just an additional artefact from GitHub? It's contents seem to be identical to the Hash version, except minor differences in the `index.html`.

**Comment by gamalielhere** [comment]
@kolAflash 

> So I guess the Offline version is for [using MEW as a Cold Wallet (Paper Wallet)](https://help.myetherwallet.com/en/articles/6167899-how-to-create-a-cold-wallet-a-k-a-paper-wallet) and for manually tweaking transaction details. Is this correct?

yes.

> Can the Hash version be used without internet connection? 

yes but you have to serve it locally.

> If yes, what's the difference to the Offline version?
You need to serve Hash version locally where as with Offline, you can just open index.html and it runs as is.
also hash is the full version of mew where as offline is just the offline mode.

> And why is it called Hash after all? Is there any meaning in the term "Hash" here?
It's because it's route is hash enabled. No special meaning behind it.

> And does the .zip version serve any other purpose than the Hash version, or is it just an additional artefact from GitHub? 
just additional artefact from GitHub.
