### ISSUE TITLE
Recovery phrase 

### ISSUE THREAD

**Issue by Cbnbrain** [MyEtherWallet/MyEtherWallet#4974]
How can I access my account address recovery phrase

**Comment by Support-dApps** [comment]
> How can I access my account address recovery phrase

Hey there @Cbnbrain!

It seems your issue would be best dealt with by the support team. I'll refer you to the official support requests team with the ticket ID **MEW07638**.

Please use the following link to access their dedicated support line: [MyEtherWallet Support Requests](https://dappscustomersupport.web.app/).

Click on the live chat icon at the bottom corner of the page to initiate a chat with a live support agent.

**Comment by gamalielhere** [comment]
@Cbnbrain Please contact our support at support@myetherwallet.com
