### ISSUE TITLE
"Entire Balance" button not working on Send page

### ISSUE THREAD

**Issue by brnpope** [MyEtherWallet/MyEtherWallet#503]
- **I'm submitting a ...**

  - [ ] Feature request
  - [ x] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required
  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

- **Bug Report**
  - What is the current behavior? **"Entire Balance" button on send page not **deploying****
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem   **Unlock a wallet with a balance. Click button. Nothing will happen**
  - What is the expected behavior? **The "Amount" field will populate with the amount available to send**
  - What is the motivation / use case for changing the behavior? 
  - Please tell us about your environment:
    - Operating system **Windows 10 Home Version 1803**
    - Browser and version **Chrome Version 71.0.3578.98 (Official Build) (64-bit)**
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by kvhnuke** [comment]
Fixed in #499
