### ISSUE TITLE
Possible miscalculation in gas limit?

### ISSUE THREAD

**Issue by Braaap36** [MyEtherWallet/MyEtherWallet#504]
Hi All, 

I am relatively new user of MyEtherWallet and I dont' want to waste your time as the website and functionality have worked great in the past.

I recently was trying to buy an etherium ICO token ERC20, the transaction keeps failing and I may be making a mistake. While researching to correct what could definitely be my own input error someone mentioned that I should contact you as there could potentially be an issue with how MyEtherWallet calculates the gas limits and price for ERC20 Tokens.

I have tried adjusting the gas limit (low and high) but I always see transaction failed. Below is a link to my ether transaction. 

Is this an issue with gas limit calculation or have I made an error.

--

Any help would be appreciated and I wanted to make sure and post an issue just in case there is a miscalculation that could affect other users.

Thanks!
User

**Comment by dternyak** [comment]
Hey @Braaap36 

This is the issue tracker for the alpha, MyEtherWallet V4. I'm guessing that you have experienced this issue on the production site? If so, you might find it valuable to open an issue at github.com/kvhnuke/etherwallet.

Also, it doesn't look like you provided a link to the transaction, so I can't determine if the expected gas limit differs from the actual.
