### ISSUE TITLE
Confirm tx modal

### ISSUE THREAD

**Issue by crptm** [MyEtherWallet/MyEtherWallet#51]
Okay so I put this somewhere but basically for the confirmation modals it should always parse the signed TX and display:

- From address + addressicon
- Amount
- Coin Type
- To address + addressicon
- Gas Limit
- Gas Price 
- TX Fee in ETH + USD (USD situation is optional for now)
- Data
- Title / Message (e.g. "You are about to send a transaction" or "you are about to resolve your ENS name" or whatever is passed to it)
- Current chain (ETH vs ETC)
- Who node is provided by

I think what you've built here is great for that and love the table. 

This gives us a really reusable modal and acts as a final check for the user. One of the things I really don't like is, for example, the current contract page modal doesn't give you anything. No address, no idea how much its going to cost to deploy, etc.

---

**Current issues with current conf modals**

- People dont read them (had someone the other day literally tell me we need a confirmation for the confirmation....)

- Too easy to miss the *coin* you are sending (e.g. ETH vs SNT)

- Too easy to miss the chain you are on (ETC vs ETH), although the border I added has helped reduce those

- Not the information the user wants / needs in an easily parsable / skimmible *thing* (table format will help)

---

Separately, I hate how modals sometimes close all by themselves sometimes if you click twice or click outside. I do it on Twitter all the time and I think it's worse with bootstrap v4. I lose tweets ALL THE TIME when I'm trying to highlight something. 

It shouldn't close unless you hit the X or the CANCEL button or hit the esc button (optional)

--

Other than that, I really like the success / error state inside the modal itself, but we'll have to decide how to handle alerts and things. While some successes and errors come from front-end validation, some are message returned directly from the node (e.g. a TX with that hash has already been imported). It would be safer to handle all alerts via the alerts handler, avoiding a potential situation where you sometimes show alert, sometimes put alert in modal, and if you aren't careful, accidentally don't show the alert at all. Making things fail-proof for our future selves is very important so we can build quickly with less worry. 😉

**Comment by dternyak** [comment]
Closing in favor of https://github.com/MyEtherWallet/MyEtherWallet/issues/85
