### ISSUE TITLE
Mobile Web Support

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#512]
- [x] Adjust CSS as time permits for better responsiveness on mobile (or at least ensure at parity with V3)
- [ ] Fix iOS 11 Safari Whitescreen

**Comment by wbobeirne** [comment]
Just a reminder that we have a BrowserStack account, feel free to PM me in slack if you need to do some mobile browser testing. Using Chrome's responsive tools is a good start, but it's always good to make sure it's working fine on the real hardware.

**Comment by wbobeirne** [comment]
Unfortunately BrowserStack doesn't have dev tools for iOS 11, but iOS 9 is getting

> SyntaxError: Invalid character '\u8544'

Looks like the js bundle might be getting some kind of malformed characters. Not sure if this is what's causing iOS 11's problem though.

**Comment by dternyak** [comment]
Re-opening - iOS 11 white-screens onload.
