### ISSUE TITLE
Not enough funds message placement is wrong

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#513]
- **I'm submitting a ...**

  - [x] Bug report
![screenshot from 2019-01-24 20-22-26](https://user-images.githubusercontent.com/19334138/51725240-06fb1b80-2016-11e9-8fdc-43d67137936d.png)

**Comment by kvhnuke** [comment]
Also just remembered fund calculation should 
`amount + txfee <=balance` currently it only checks `amount <= balance`
