### ISSUE TITLE
Make a Cookie For The Pop-up

### ISSUE THREAD

**Issue by masonthecoolguy** [MyEtherWallet/MyEtherWallet#516]
Can you please make a cookie for the pop-up on the website? I hate seeing it every time I go to the website. Thanks.

**Comment by wbobeirne** [comment]
This is the issue queue for version 4, which is currently in alpha. The pop-up is on the current live site (v3) which has an issue for this over in that repository: https://github.com/kvhnuke/etherwallet/issues/1347
