### ISSUE TITLE
"Yes" button on "Are you sure to logout your wallet?" non-responsive. 

### ISSUE THREAD

**Issue by brnpope** [MyEtherWallet/MyEtherWallet#525]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior? "Yes" button is non-responsive. "No" button works.
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem Yes
  - What is the expected behavior? Button will engage. Log out will occur
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system Windows 10 
    - Browser and version Chrome Version 72.0.3626.81 (Official Build) (64-bit)
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  Error occurred using MEWconnect (iOS)

  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by gamalielhere** [comment]
@brnpope Can't seem to replicate. Tested with Ledger, Secalot, Keystore, and Metamask. Closing issue but don't hesitate to reopen if needed.

**Comment by brnpope** [comment]
Its happening with MEWconnect. I'm still experiencing it.

**Comment by gamalielhere** [comment]
#529 should fix it
