### ISSUE TITLE
Move RPC integration tests out of unit tests

### ISSUE THREAD

**Issue by eddiewang** [MyEtherWallet/MyEtherWallet#530]
We don't want the CI checks to fail with the integration tests when our nodes are down, so let's move the integration tests out of the unit tests.

**Comment by dternyak** [comment]
This was either partially or completely solved by https://github.com/MyEtherWallet/MyEtherWallet/pull/529, specifically in https://github.com/MyEtherWallet/MyEtherWallet/pull/529/files#diff-251541cc6541b827d610d6eed2686e58.

@eddiewang Can you confirm this was the only integration test living in unit test land?

**Comment by eddiewang** [comment]
@dternyak noticed that! looks clean. great job. and confirmed those are the only integration tests.
