### ISSUE TITLE
Reduced screen size results in missing many features at the top of the open wallet interface

### ISSUE THREAD

**Issue by stephenmew** [MyEtherWallet/MyEtherWallet#532]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

After accessing your wallet, when the screen is small (like for mobile versions), the 'logout' menu disappears. (All the icons above disappear, but the logout option is probably most important). Other missing options include Language, FAQ, Notifications, and Settings.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Reduce screen size

  - What is the expected behavior?

It should at the very least have the logout option and language options available. FAQ, notifications, and settings are also useful.

  - What is the motivation / use case for changing the behavior?

On mobile systems, it is impossible to function normally without these options.

  - Please tell us about your environment:
    - Operating system

Windows 10

    - Browser and version

Chrome 71.0.3578.98

**Comment by hsurf22** [comment]
For Mobile, "logout button" is inside the menu button.
Done.
