### ISSUE TITLE
Screen resizing smaller results in glitchy blue windows- Hardware wallet

### ISSUE THREAD

**Issue by adewyn** [MyEtherWallet/MyEtherWallet#533]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

When accessing a ledger hardware wallet, if the window is reduced (like for mobile screens), areas for changing the Network and changing the Derivation path turn bright blue and look glitchy.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Access a Ledger (or another) hardware wallet, content turns glitchy

  - What is the expected behavior?

It should look polished and have the darker blue-ish color for consistency.

  - What is the motivation / use case for changing the behavior?

The bright blue is not user friendly or intuitive. It looks messy.

  - Please tell us about your environment:
    - Operating system

Windows 10

    - Browser and version

Chrome 71.0.3578.98

**Comment by gamalielhere** [comment]
This seems to be fixed now
