### ISSUE TITLE
Lite Send

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#542]
When sending Ether or Tokens in the Swap as the origin kind, wallet decrypt unlocks a "lite" send component in V3 that is read-only/disabled with pre-filled `to`, `amount`, and `unit` fields (corresponding to the swap).

- [x] Warning shown in red when balance is smaller than swap amount
- [x] Generate Transaction Button disabled when balance smaller than requested amount
- [x] (Does not exist in V3) Additional user messaging when token balance smaller than requested amount.

<img width="413" alt="screen shot 2017-12-09 at 10 27 13 pm" src="https://user-images.githubusercontent.com/7861465/33802644-2cf2e194-dd30-11e7-97fe-6ba0036f5577.png">

**Comment by dternyak** [comment]
Blocked by https://github.com/MyEtherWallet/MyEtherWallet/pull/456

**Comment by HenryNguyen5** [comment]
If the user has insufficient balance, should we show `Lite-Send` at all? Instead on wallet unlock we could check balances and then just hide `Lite-Send` while showing a notification that they didn't have insufficient funds. Then they can either select a different wallet or send from somewhere else.
