### ISSUE TITLE
Add a welcome modal to v5

### ISSUE THREAD

**Issue by kvhnuke** [MyEtherWallet/MyEtherWallet#547]
- **I'm submitting a ...**

  - [x] Feature request
 
We should add a welcome modal that'll show up only the first time they visit the page to let users know that this is the new version of MEW, I'm afraid  otherwise there will be lots of confused users.

**Comment by jackhuangusa** [comment]
![landing page popup](https://user-images.githubusercontent.com/31494364/52241449-901d1880-2888-11e9-929b-a2568cbd540d.jpg)
