### ISSUE TITLE
Redesign Wallet Unlock Component

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#565]
A few of the mockups in #434 had ideas for a better wallet unlock component. The goals of redesigning it are:

1. Provide more visual distinction between the options. Despite having unlocked hundreds of times, my brain still glazes over when I see 7 identical radio buttons.
2. Disuade private key, keystore, and mnemonic unlocks. Taylor's design keeps the more secure options up top, and shows warnings for the other options
3. More help text wherever possible.

Design is still in flux, so feel free to leave any comments or ideas here.

**Comment by wbobeirne** [comment]
I tried to combine the mockups from #434, and make it fit within our current template. I'm pretty happy with the results:

## Cartoonish icon style from @tayvano's mockups

![unlock-cartoon](https://user-images.githubusercontent.com/649992/33968066-307af5f2-e034-11e7-89f6-5545ffba19f4.png)

## FontAwesome flat icons

![unlock-icon](https://user-images.githubusercontent.com/649992/33968084-40edb4e2-e034-11e7-83ee-f3286a3a32b8.png)

---

I'm leaning towards the latter, since it fits in with our current template a little more, so I did the rest of the mockups using that. But if there's a preference for the former, let me know. You can find the [full set of mockups in this unlock.pdf](https://github.com/MyEtherWallet/MyEtherWallet/files/1557483/unlock.pdf)

**Comment by wbobeirne** [comment]
I also wanted to explore how to present the top row. The examples above use a custom logo for each. In addition to that, I tried out a small square logo with uniform text for each, and text-only versions. Let me know if there's a clear winner!

![icon - logo text](https://user-images.githubusercontent.com/649992/33968742-92579886-e037-11e7-917e-3b23f0bd695d.png)


![icon - text only](https://user-images.githubusercontent.com/649992/33968749-96b27c84-e037-11e7-818a-ea74013ead2b.png)

**Comment by dternyak** [comment]
I'm a big fan of `Small Logo & Text` 👍

**Comment by dternyak** [comment]
After some pondering, I think this view should potentially replace Create New Wallet as the default view.

Additionally, we could a "Create New Wallet" card featured prominently on the top left to assist with on-boarding new users that are hitting the default view. This would simply direct them to the Create New Wallet component.

**Comment by wbobeirne** [comment]
I'll leave default view changing as a part of #557.

Having a link to create from here makes a lot of sense, but I don't have a good idea of where it'll look best. I'll first implement this as is, then play around with how it looks with an additional button in code rather than sketch.
