### ISSUE TITLE
Show loading indicator while decrypting hardware wallets (ledger)

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#578]
Currently, there is no UI indicator while ledger wallet connection is being established. 

In the case when a user has mistakingly logged into Bitcoin instead of Ethereum when using ledger, there will be no UI response at all until we timeout and show a red error.

- [ ] Provide a loading indicator while connection is being established
- [ ] Show messaging to inform the user they may be logged into the wrong application upon timeout

**Comment by tayvano** [comment]
We also recently got a request to remind people to look at their Ledger or TREZOR to confirm the transaction upon generating the transaction. 

Here's our troubleshooting guide for misc. hardware wallet issues for reference: https://myetherwallet.github.io/knowledge-base/hardware-wallets/ledger-hardware-wallet-unable-to-connect-on-myetherwallet.html

**Comment by tayvano** [comment]
Please take a look at #637 as it may solve this / help this
