### ISSUE TITLE
Format hint for contract interaction for bytes32 and uint8

### ISSUE THREAD

**Issue by senselessDev** [MyEtherWallet/MyEtherWallet#587]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  -  `/contract` module shows very useful hints for the expected format of the arguments of types uint256 and address, but they are missing for example for bytes32 and uint8 (see below)

![myetherwallet_contract](https://user-images.githubusercontent.com/8526592/52525357-bc7dce00-2ca8-11e9-9d81-b0cddd8d0ba5.png)

**Comment by gamalielhere** [comment]
@senselessDev this is unrelated to this repo. Please make an issue [here](https://github.com/kvhnuke/etherwallet)
