### ISSUE TITLE
can we add a node for MUSIC?

### ISSUE THREAD

**Issue by krtschmr** [MyEtherWallet/MyEtherWallet#59]
it's fairly a coming coin, same as EXPanse. 
having the ability for users to generate wallets for these coins will help.

they are legit ethereum forks and the concept/idea is nice. give them support!

**Comment by tayvano** [comment]
As a free, open-source service, anyone is free to open a pull request and provide support for new features or chains.We do not attempt to follow other chains or tokens due to the overwhelming backlog of purely-Ethereum things.
