### ISSUE TITLE
Transaction Validity Spec

### ISSUE THREAD

**Issue by HenryNguyen5** [MyEtherWallet/MyEtherWallet#598]
# Valid Ether transactions

| Standard | Standard | Standard | Standard | NonStandard | NonStandard |
| -------- | -------- | -------- | -------- | ----------- | ----------- |
| Nonce    | Nonce    | Nonce    | Nonce    | Nonce       | Nonce       |
| GasPrice | GasPrice | GasPrice | GasPrice | GasPrice    | GasPrice    |
| GasLimit | GasLimit | GasLimit | GasLimit | GasLimit    | GasLimit    |
| To       | To       | To       | To       |             |             |
| Value    | Value    |          |          |             | Value       |
| Data     |          |          | Data     | Data        | Data        |

All other permutations of a ether transaction are invalid

# Valid Token Transactions

| Standard     |
| ------------ |
| Nonce        |
| GasPrice     |
| GasLimit     |
| To           |
|              |
| Data         |
| \*TokenTo    |
| \*TokenValue |

All other permutations of a token transaction are invalid

* These are 'meta' units that are encoded into the data, they describe the recepient address and how many tokens to send

**Comment by dternyak** [comment]
Re-opening until we move this into a long-term document.

**Comment by tayvano** [comment]
Not sure if this belongs here, but all TXs should have a chainid, even though it's not technically required for them to have one. 

The chainid field was added after the ETH/ETC hardfork to add on-chain replay transaction. MyEtherWallet requires any network that we add to the default nodes to have the also updated to include the EIP-155 fork.

If we didn't have to many users I wouldn't bother as it's still a valid TX and will send without issue, but sending a transaction without a specified chainid can result in accidental loss as well as be used for malicious attacks.

**Comment by dternyak** [comment]
Moved to wiki
