### ISSUE TITLE
Invalid Chain ID on POA Network with Ledger

### ISSUE THREAD

**Issue by banteg** [MyEtherWallet/MyEtherWallet#604]
[POA Network](https://poa.network) works fine with Ledger after supplying custom node `https://core.poa.network` and choosing ETH, but the transactions signed with Ledger will fail due to invalid chain id (1 instead of 99, see their [chain spec](https://github.com/oraclesorg/poa-chain-spec/blob/afd65c5cfb79fb115f4c5b9020755f9765cdffa0/spec.json#L24)).

1. Is there a trivial fix for this? If I understand correctly choosing Custom will not include `chainId` at all. A better solution will be adding custom chain id field for such cases. 
2. Are you working closely with the POA team to add a better integration like with RSK, UBQ and EXP?

**Comment by dternyak** [comment]
Hey @banteg 

This is the issue tracker for the V4 re-implementation of MyEtherWallet. I think you may have accidentally filed this issue here instead of https://github.com/kvhnuke/etherwallet.

**Comment by rstormsf** [comment]
@banteg 
Can you please give me some advice on how to fully add the network? 
https://wallet.poa.network/
We don't intend to fork it, I just want to add all support before I submit a PR into main MEW.

https://github.com/oraclesorg/wallet/commit/b2387337c6e9752c07bf644b51db3fe4dce22e19

Please help me out using your best practices.
Right now, I receive a warning for HD paths, even though we use ETH based. 

Could you please take a look at my commit and let me know what else I should add before PR?

**Comment by banteg** [comment]
Hey @dternyak

Right, I filed the issue to the wrong repo. First of all, great work, this implementation solves it.

I tested the alpha with the custom network, it works nicely with json wallets, but gets stuck at `Unlocking...` phase with Ledger.

**Comment by Tim1T** [comment]
everything works fine for me, both unlocking&sending funds

**Comment by rstormsf** [comment]
anyone having this:
```
OPTIONS https://core.poa.network:8545/ net::ERR_CONNECTION_TIMED_OUT
```
?

**Comment by rstormsf** [comment]
@dternyak 
There is an issue if I send a tx from ledger on custom network.
So, I couldn't co
Steps:
1. Provide Custom Node URL: 
https://core.poa.network
in order to connect, I had to use port 443 (SSL) even though the actual node is running on 8545
2. send a tx from ledger
3. Tx actually goes thru, but since we used port 443 instead of 8545, it can't load the actual tx, and throws an error:

```
SyntaxError: Unexpected end of JSON input
    at client.ts:41
    at <anonymous>
react-dom.production.min.js:164 TypeError: Cannot read property 'tx' of undefined
...
utils.js:227 uncaught at c TypeError: Cannot read property 'tx' of undefined
   ...
    at Object.enqueueSetState (https://alpha.myetherwallet.com/vendor.7a7eaf44.js:1:79315)
```

**Comment by wbobeirne** [comment]
Hey @rstormsf, you don't have to use port 443 for SSL, any port can run SSL (443 is just a standard for when the port is not provided.) So it's likely that something on the server responds to the initial check against :443, but it's not actually the node.

I think y'all will get the best support if you hop into our slack. Just shoot me an email (In my profile) and I can get you an invite.

**Comment by rstormsf** [comment]
@wbobeirne I sent you an email.

Also I'm wondering when I try to connect it with metamask, I'm also getting this error:

<img width="1005" alt="screen shot 2017-12-19 at 12 54 15 pm" src="https://user-images.githubusercontent.com/9360827/34180954-55b7aa64-e4c5-11e7-9854-7fc2ae1840ef.png">

**Comment by rstormsf** [comment]
@wbobeirne so if use https://core.poa.network with port 8545 it doesn't connect
if I use https://core.poa.network/ with port 8545 it does connect.

so `/` does matter

**Comment by banteg** [comment]
Looks like it connects to `https://core.poa.network/:8545` in the second case, so the port is actually 443.

**Comment by rstormsf** [comment]
the issue is still the same.

```
Oops!
Something went really wrong, so we're showing you this red error page! 😱

Please contact support@myetherwallet.com if a refresh doesn't fix it (or click it anyway to open a ticket 😊). If you attach the following error, you'll make it a ton easier to fix the issue.

Please make sure the error message does not include any sensitive information before sending it us. We don't want your private keys!
Cannot read property 'tx' of undefined
```

**Comment by tayvano** [comment]
Off the top of my head, this may be related to https://github.com/ethereumjs/ethereumjs-tx/pull/57? Maybe not though?

**Comment by rstormsf** [comment]
Please note it's only problem with v4 MEW, v3 works just fine.
I don't think it's a problem with  ethereumjs/ethereumjs-tx#57 since the tx actually goes thru, it's the problem that MEW v4 can't get tx object after it's published, in order to get the hash...my guess it doesn't correctly construct the requests since the PORT is 8545 and URL is https://... and the fact it only handles the request if `/` is provided at the end of the RPC_URL.

@tayvano 
Have you had a chance to go over our PR https://github.com/kvhnuke/etherwallet/pull/1427
We really don't want scammers to spin out new MEW sites with wallet.poa.networkS, wallet.poaa.network, etc, etc....
