### ISSUE TITLE
Change string in vintage MEW/link

### ISSUE THREAD

**Issue by olgakup** [MyEtherWallet/MyEtherWallet#608]
- **I'm submitting a ...**
  - [x] Bug report

- **Feature Request**

  Change web link to current version, and remove word Beta.
 Update link to the new medium post.

<img width="517" alt="screen shot 2019-02-11 at 10 29 57 am" src="https://user-images.githubusercontent.com/16910687/52584839-028d7b80-2de8-11e9-892b-39c14a0b118e.png">

**Comment by kvhnuke** [comment]
https://github.com/kvhnuke/etherwallet/pull/2229/files
