### ISSUE TITLE
Vintage MEW link missing at footer (and/or header)

### ISSUE THREAD

**Issue by stephenmew** [MyEtherWallet/MyEtherWallet#609]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
We need the vintage MEW link somewhere static, not just in the pop-up that appears once.

  - What are the current issues this feature will solve
Finding vintage MEW

**Comment by kvhnuke** [comment]
fixed
![image](https://user-images.githubusercontent.com/10602065/52626535-3f995280-2e68-11e9-8f4e-0437fa262d39.png)
