### ISSUE TITLE
EXP missing from Networks/Nodes list

### ISSUE THREAD

**Issue by adewyn** [MyEtherWallet/MyEtherWallet#612]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
EXP is missing from Network/Node list

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Check the network list, it's not there

  - What is the expected behavior?
EXP should be in the network list

  - What is the motivation / use case for changing the behavior?
Some people use the EXP node through MEW

  - Please tell us about your environment:
    - Operating system
Windows 10 Pro

    - Browser and version
Latest Chrome browser

**Comment by mkrufky** [comment]
see also #667

**Comment by gamalielhere** [comment]
Should be fixed with the new release.
