### ISSUE TITLE
Disable equivalent values on testnets

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#614]
As much as I wish I was nearly a trillionaire, this could probably be confusing. We should either hide the box, or note that test networks have no value.

<img width="425" alt="screen shot 2017-12-18 at 12 56 14 pm" src="https://user-images.githubusercontent.com/649992/34120240-f00b25ec-e3f2-11e7-8219-bbd193b37984.png">

**Comment by tayvano** [comment]
<img width="760" alt="2017-12-19 at 3 56 10 am" src="https://user-images.githubusercontent.com/7924827/34156100-95f79698-e470-11e7-96d7-e46f61940b20.png">

for the lulz. the last time I told someone that testnet ETH has no value. 😂

Best to hide it on **any network for which we do not have a price API for** to prevent further philosophical debates over semantics. 😉
