### ISSUE TITLE
decimals should be fewer than max for currencies using fewer decimal places

### ISSUE THREAD

**Issue by SteveMieskoski** [MyEtherWallet/MyEtherWallet#614]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
    - the decimals go out to 6 places regardless of the decimal support for the selected currency
  - What is the expected behavior?
    - The number of decimals should reflect the number of decimals a currency supports if it fewer than the max allowed number of decimals
  - What is the motivation / use case for changing the behavior?
    - particularly when handling fiat currencies, there should only be two values after the decimal

**Comment by kvhnuke** [comment]
Fixed in sendCurrency, but I believe you should also check in swap!

**Comment by SteveMieskoski** [comment]
Fixed in swap [5.0.3]
