### ISSUE TITLE
Changing network on unlocked Send doesn't save network

### ISSUE THREAD

**Issue by wbobeirne** [MyEtherWallet/MyEtherWallet#616]
When you've got a wallet open on send, and change networks, the page refreshes with the previous network still selected

Steps to reproduce:
1. Go to /send-transaction
2. Unlock (non-web3) wallet of your choosing
3. Change network
4. Wait, observer refreshed page network

This likely has to do with the mechanism we save to local storage with, and the way network is initially selected. We should probably do something more than hoping the new network ends up in LS before refreshing. With `transaction-refactor` putting everything in Redux, we also may be able to reset all state in sagas when you change network, preventing a refresh.

**Comment by dternyak** [comment]
I believe `transaction-refactor` fixes this by increasing the delay before refresh, but we may be able to completely get rid of the refresh and just reset wallet state on node change now that everything is in redux (as you mentioned).

**Comment by HenryNguyen5** [comment]
@dternyak Yes this is fixed in `transaction-refactor`

**Comment by wbobeirne** [comment]
I experienced this on that branch, had to switch to develop to confirm it wasn't being caused by it.

**Comment by dternyak** [comment]
Closing, should be fixed. Re-opening a new issue to determine if we can get away with setting networks without refreshing.
