### ISSUE TITLE
Display Address on Hardware Wallet

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#624]
Port existing functionality to show account address on hardware wallets.

<img width="390" alt="screen shot 2017-12-18 at 10 50 10 pm" src="https://user-images.githubusercontent.com/7861465/34141282-d3012af2-e445-11e7-9fd4-b2e5e14a72f2.png">

- [ ] Ledger
- [ ] Trezor

**Comment by tayvano** [comment]
Reference: https://github.com/kvhnuke/etherwallet/pull/839/files

**Comment by wbobeirne** [comment]
Trezor also supports this functionality, so we should also implement it for those as well.

**Comment by dternyak** [comment]
@wbobeirne Agreed, updated to issue to make it more clear it is for both currently supported hardware wallets in V4.
