### ISSUE TITLE
Move to BN.js

### ISSUE THREAD

**Issue by crptm** [MyEtherWallet/MyEtherWallet#64]
We already have it as dependency. It can into parsing/writing base16 values. 

- [ ] It does not support decimals so we need some helpers for that
- [ ] we need flow definitions

**Comment by dternyak** [comment]
@wbobeirne Is this something we still want to do?

**Comment by crptm** [comment]
We want to do it. We already ship it for ethereumjs, it is much more lightweight and wasn't noticed in infinite loops :)

**Comment by dternyak** [comment]
It seems _ethereumjs_ libraries have settled on using `BN.js` as a standard for handling large numbers in JavaScript.

Examples:
 - https://github.com/ethereumjs/ethereumjs-util/blob/f53d34aec3213c39d117ddabf25dcbddca13ce83/index.js#L5
 - https://github.com/ethereumjs/ethereumjs-abi/blob/4a33f233cc6a2f50c9a8ae59684ba631c4b91825/package.json#L7

In the interest of following this standard, we should switch to BN.js as well.

**Comment by wbobeirne** [comment]
Looks like this task is going to be a mild pain. I did a little audit of everywhere we use it (As of 8854d42fd99f3d494cdbd4ba4a038930f1e1720a)

We'll likely need to implement a big-numberless way of converting a decimal string into a wei unit string. Fortunately if we switch over to the libs/units classes, I think it should make the bulk of future bignumber handling pretty well contained, aside from gas and a few other instances.

## bignumber.js uses
|File|Conversion steps|
|--------------------------------------|---------|
|common/actions/deterministicWallets.js|1:1 (Type only)|
|common/actions/wallet.js|1:1 (Type only)|
|common/libs/erc20.js|1:1|
|common/libs/transaction.js|Rework to only use wei|
|common/libs/units.js|Rework to force everything into wei / use classes|
|common/reducers/wallet.js|1:1 (Type only)|
|common/selectors/wallet.js|1:1|
|common/utils/formatters.js|Likely needs to be moved into libs/units.js, assumes decimals|
|spec/libs/erc20.spec.js|Reworked to not use decimals|
|spec/libs/contract.spec.js|Unused|
|spec/libs/units.spec.js|Reworked to not make bigs from decimals|
|spec/reducers/wallet.spec.js|1:1|
|spec/utils/formatters.spec.js|Mostly removed, see common/utils/formatter.js|
|common/components/BalanceSidebar/AccountInfo.jsx|1:1 (Type only)|
|common/components/BalanceSidebar/EquivalentValues.jsx|Unused|
|common/components/BalanceSidebar/index.jsx|Unused|
|common/libs/nodes/INode.js|1:1 (Type only)|
|common/libs/wallet/trezor.js|Uncertain, not sure what values a transaction `v` can be|
|.../BalanceSidebar/TokenBalances/TokenRow.jsx|1:1 (Type only)|
|common/containers/Tabs/SendTransaction/index.jsx|1:1|
|common/libs/nodes/rpc/index.js|I think token values may need to be reworked, unsure if they come back in "wei"|
|common/libs/nodes/rpc/utils.js|1:1 (Type only)|
|spec/libs/nodes/rpc/rpc.spec.js|1:1|
|.../SendTransaction/components/ConfirmationModal.jsx|Will need to stop using the toUnit function|

**Comment by wbobeirne** [comment]
Going to hold off on this until @HenryNguyen5 finishes the typescript changeover, to reduce conflicts.
