### ISSUE TITLE
Cannot Close Notifications

### ISSUE THREAD

**Issue by aitrean** [MyEtherWallet/MyEtherWallet#645]
Notifications do not close themselves, and hitting the close button on a notification will dispatch the action, but the notification will not close.

**Comment by dternyak** [comment]
I've done a little investigation here - it's related to our usage of `react-transition-group`.

Removing our usage of the animation fixes the problem, which is not ideal. I haven't yet been able to solve the problem without doing so. 

@james-prado I think you added these transitions, do you mind assisting with the fix?

**Comment by dternyak** [comment]
Fixed in https://github.com/MyEtherWallet/MyEtherWallet/pull/700
