### ISSUE TITLE
Send offline - nonce and gas price fields

### ISSUE THREAD

**Issue by kosecki123** [MyEtherWallet/MyEtherWallet#652]
- [x] Bug report

Offline send - https://www.myetherwallet.com/interface/send-offline

- **Nonce field**
  - Current: Nonce field is not automatically generated and set to latest user nonce
  - Expected: As previous MEW version had "Generate Information" button that filled it, perhaps some sort of refresh icon can be added next to the field to fill the latest value
 
- **Gas price field**
  - Is empty and requires user to put the wei value while settings page hold the Transaction Speed
  - Expected: use settings Transaction Speed and fill gas price field by default with that value

**Comment by gamalielhere** [comment]
Should be fixed with the new release.
