### ISSUE TITLE
when i run the coomand npm start got the following error

### ISSUE THREAD

**Issue by parmarrushabh** [MyEtherWallet/MyEtherWallet#662]
- **I'm submitting a ...**

  - [ ] Feature request
  - [ ] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required
  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

- **Bug Report**
  - What is the current behavior?
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior?
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
    - Browser and version
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by parmarrushabh** [comment]
npm run dev


> myetherwallet@5.0.2 update C:\Users\lenovo\Desktop\MyEtherWallet
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.2 update:packages C:\Users\lenovo\Desktop\MyEtherWallet
> node package-test.js


> myetherwallet@5.0.2 update:lists C:\Users\lenovo\Desktop\MyEtherWallet
> node fetchEthListData.js


> myetherwallet@5.0.2 dev C:\Users\lenovo\Desktop\MyEtherWallet
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 ERROR  Failed to compile with 11 errors                                                                     11:29:27 AM

These dependencies were not found:

* @myetherwallet/eth-token-balance in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/InterfaceLayout/InterfaceLayout.vue?vue&type=script&lang=js&
* ethereum-ens in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/InterfaceLayout/InterfaceLayout.vue?vue&type=script&lang=js&, ./src/partners/kyber/kyber.js
* web3 in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/dapps/BuySubdomain/BuySubdomain.vue?vue&type=script&lang=js& and 6 others

**Comment by kvhnuke** [comment]
You have to do `npm install` before doing `npm start`

**Comment by parmarrushabh** [comment]
but when i run the command npm install it gives me the following error @kvhnuke 

npm install

> scrypt@6.0.3 preinstall C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt
> node node-scrypt-preinstall.js


> secp256k1@2.0.10 install C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1
> npm run rebuild


> secp256k1@2.0.10 rebuild C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1
> node-gyp rebuild


C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.10 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-02-15T05_57_27_836Z-debug.log

> scrypt@6.0.3 install C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt
> node-gyp rebuild


C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.3.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.0.1 requires a peer of eslint@>= 5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN myetherwallet@5.0.2 No repository field.
npm WARN myetherwallet@5.0.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@myetherwallet\mewconnect-web-client\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@2.0.10 (node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@2.0.10 install: `npm run rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-02-15T05_57_37_839Z-debug.log

C:\Users\lenovo\Desktop\MyEtherWallet>npm start

> myetherwallet@5.0.2 start C:\Users\lenovo\Desktop\MyEtherWallet
> npm run update && npm run dev


> myetherwallet@5.0.2 update C:\Users\lenovo\Desktop\MyEtherWallet
> npm run update:packages && npm run update:lists


> myetherwallet@5.0.2 update:packages C:\Users\lenovo\Desktop\MyEtherWallet
> node package-test.js


> myetherwallet@5.0.2 update:lists C:\Users\lenovo\Desktop\MyEtherWallet
> node fetchEthListData.js


> myetherwallet@5.0.2 dev C:\Users\lenovo\Desktop\MyEtherWallet
> vue-cli-service serve

 INFO  Starting development server...
 98% after emitting CopyPlugin

 ERROR  Failed to compile with 11 errors                                                                     11:29:27 AM

These dependencies were not found:

* @myetherwallet/eth-token-balance in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/InterfaceLayout/InterfaceLayout.vue?vue&type=script&lang=js&
* ethereum-ens in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/layouts/InterfaceLayout/InterfaceLayout.vue?vue&type=script&lang=js&, ./src/partners/kyber/kyber.js
* web3 in ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/containers/ConfirmationContainer/components/AddressBlock/AddressBlock.vue?vue&type=script&lang=js&, ./node_modules/cache-loader/dist/cjs.js??ref--12-0!./node_modules/babel-loader/lib!./node_modules/cache-loader/dist/cjs.js??ref--0-0!./node_modules/vue-loader/lib??vue-loader-options!./src/dapps/BuySubdomain/BuySubdomain.vue?vue&type=script&lang=js& and 6 others

To install them, you can run: npm install --save @myetherwallet/eth-token-balance ethereumTerminate batch job (Y/N)? y

C:\Users\lenovo\Desktop\MyEtherWallet>node-gyp rebuild
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lenovo\Desktop\MyEtherWallet>node-gyp
'node-gyp' is not recognized as an internal or external command,
operable program or batch file.

C:\Users\lenovo\Desktop\MyEtherWallet>npm install

> scrypt@6.0.3 preinstall C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt
> node node-scrypt-preinstall.js


> secp256k1@2.0.10 install C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1
> npm run rebuild


> secp256k1@2.0.10 rebuild C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1
> node-gyp rebuild


C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1>if not defined npm_config_node_gyp (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! secp256k1@2.0.10 rebuild: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the secp256k1@2.0.10 rebuild script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
npm WARN Local package.json exists, but node_modules missing, did you mean to install?

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-02-15T06_58_31_017Z-debug.log

> scrypt@6.0.3 install C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt
> node-gyp rebuild


C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt>if not defined npm_config_node_gyp (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:484:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\node-gyp\lib\configure.js:509:16)
gyp ERR! stack     at C:\Users\lenovo\AppData\Roaming\npm\node_modules\npm\node_modules\graceful-fs\polyfills.js:282:31
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:154:21)
gyp ERR! System Windows_NT 10.0.17134
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\lenovo\\AppData\\Roaming\\npm\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\lenovo\Desktop\MyEtherWallet\node_modules\scrypt
gyp ERR! node -v v10.15.1
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok
npm WARN bootstrap@4.3.0 requires a peer of jquery@1.9.1 - 3 but none is installed. You must install peer dependencies yourself.
npm WARN eslint-plugin-prettier@3.0.1 requires a peer of eslint@>= 5.0.0 but none is installed. You must install peer dependencies yourself.
npm WARN myetherwallet@5.0.2 No repository field.
npm WARN myetherwallet@5.0.2 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.4 (node_modules\@myetherwallet\mewconnect-web-client\node_modules\fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.4: wanted {"os":"darwin","arch":"any"} (current: {"os":"win32","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@2.0.10 (node_modules\@myetherwallet\mewconnect-web-client\node_modules\eccrypto\node_modules\secp256k1):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: secp256k1@2.0.10 install: `npm run rebuild`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! scrypt@6.0.3 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the scrypt@6.0.3 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\lenovo\AppData\Roaming\npm-cache\_logs\2019-02-15T06_58_47_854Z-debug.log

**Comment by gamalielhere** [comment]
@parmarrushabh looks like you have to install python first, if you already have it, set `PYTHON` env to where the python installation is location. Start is failing because install is failing.
