### ISSUE TITLE
permanent "disconnected from MEWconnect"

### ISSUE THREAD

**Issue by Senkevich** [MyEtherWallet/MyEtherWallet#664]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
2-5 seconds after connecting MEW Connect, I received a message "Seems like you are disconnected from MEWconnect.." I tried on different desktop PCs and had a stable Internet connection on my phone.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
just like in your instructions for sending eth with MEW Connect

  - What is the expected behavior?
no disconnects
  - What is the motivation / use case for changing the behavior?
unable to use application, send eth
  - Please tell us about your environment:
    - Operating system
WIN 10, ios 12.1.2 
    - Browser and version
Chrome 72.0.3626.109
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
noticed that on "vintage" version disconnect and auto reconnect occur. 
on v5 version only disconnect.
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.
/interface

**Comment by SteveMieskoski** [comment]
Closing as there has been not recent activity and PR #703 included a fix for this.
