### ISSUE TITLE
REGRESSION: Network selection out of sync with previous releases

### ISSUE THREAD

**Issue by mkrufky** [MyEtherWallet/MyEtherWallet#667]
- **I'm submitting a REGRESSION report.

  - NETWORK selection is out of sync with last version of MEW
  - Users are wondering if why their favorite chain has been dropped from MEW
  - Users ask, is the problem in MyEtherWallet?  or is the blockchain broken?
  - This is creating support issues.

For example:

EXPANSE is missing from NETWORK selection
MIX BLOCKCHAIN is missing from NETWORK selection
REOSC is missing from NETWORK selection *and* from HD Derivation path selection

EOSC was removed a long time ago, but it was incorrectly reintroduced in this new release.

There are likely more issues.  Please audit the code and ensure it supports the same features on the same chains that the previous release supported.

supercedes https://github.com/kvhnuke/etherwallet/issues/2232
supercedes https://github.com/kvhnuke/etherwallet/issues/2233

**Comment by gamalielhere** [comment]
@mkrufky These networks should be there now. Let me know if I missed other networks. And feel free to open an issue or reopen this one if relevant.
