### ISSUE TITLE
ENS Registry

### ISSUE THREAD

**Issue by Jusdev89** [MyEtherWallet/MyEtherWallet#667]
I don't get whats going on, I can't set my self as the onwer or I can't set the resolved address:

<img width="1342" alt="screen shot 2017-12-24 at 11 32 54 am" src="https://user-images.githubusercontent.com/8162708/34328805-790972b8-e89e-11e7-8cb5-2905dc2a741c.png">

When I check myEtherWallet, its has the correct address as the deed owner which is me ^^

<img width="967" alt="screen shot 2017-12-24 at 11 33 36 am" src="https://user-images.githubusercontent.com/8162708/34328811-cf933fa6-e89e-11e7-9a7e-4f3ae24438c5.png">

But when I check the name on etherscan it says this is the winning deed:

0x568ba549d130ed8529907acbecba93be9eb7d0a5

I have no idea who this is.

When I try and change the owner or resolved address, this is the error I get:

Warning! Error encountered during contract execution [Bad jump destination] 

Not sure what to do from here.a

**Comment by wbobeirne** [comment]
Hey @Jusdev89 sorry for the late reply,

This is the repository for an in-development new version of MyEtherWallet. You will want to file an issue against the [existing project over here](https://github.com/kvhnuke/etherwallet/issues).

However, when I look at etherscan now, while I'm not sure what a winning deed address is, it is showing your address as the **owner** of the domain. So I think it's all good!
