### ISSUE TITLE
npm build: npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?

### ISSUE THREAD

**Issue by DreamFlasher** [MyEtherWallet/MyEtherWallet#670]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
    - `npm build` yields `npm WARN build `npm build` called with no arguments. Did you mean to `npm run-script build`?`
  - Please tell us about your environment:
    - Operating system
      - Windows Ubuntu Bash
    - Browser and version

I guess the documentation should be changed to `npm run-script build`?

**Comment by gamalielhere** [comment]
Updated the README for this
