### ISSUE TITLE
my eth lost ReplaySafeSplit

### ISSUE THREAD

**Issue by Eng-Emam** [MyEtherWallet/MyEtherWallet#670]
hi from about 2 year's i have 4.3 eth
now i am check my account i can't find it 
but i founded this https://etherscan.io/tx/0xe35af61925b1d8f8f13ffc6e35e01cc277047fe7a088238f5eb85e1efe0b50c8
but i am never make this and i now what it's
how i can restore my eth

**Comment by dternyak** [comment]
Hi @Eng-Emam,

I'm sorry to hear about your issue.

This is the issue tracker for the V4 implementation of MEW, you might find better help by emailing support@myetherwallet.com.

Best,
Daniel

**Comment by tayvano** [comment]
@Eng-Emam 

The transaction you linked to is for the ETC chain and your ETH go no where. This is your TX for the 4.3 ETH: https://etherscan.io/tx/0x18267b8a2b677891b93aad6d161b8a6264a09a9e53a53ce8e603c974d06ce863 which show them going to https://etherscan.io/address/0xe75cb728fd790c937578aab4c4d1d70df63f24b6

**Comment by Eng-Emam** [comment]
so how i can restore it 
or it's lost or stolen
