### ISSUE TITLE
Swap UX improvement 

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#673]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/53293158-7c781a00-3783-11e9-97da-b9d9125a441d.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Remove the drop down menu for different scenario.

**Comment by hsurf22** [comment]
Fixed by SteveMieskoski
