### ISSUE TITLE
Can't download keystore file when running MEW offline

### ISSUE THREAD

**Issue by russdirks** [MyEtherWallet/MyEtherWallet#674]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

Can't create a keystore file when running mew offline (ie. double-click on index.html), due to the fact the download button is grayed out after entering password.

Works fine using online version, or running mew locally under WAMP Stack.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem

Go through the steps to create a new wallet via keystore.
After entering password, expected behaviour is to be able to click the button on the bottom to save the keystore file to local storage, but that is not possible because the button is grayed out.

  - Please tell us about your environment:

Windows 10
Chrome, latest version
Running MEW offline

**Comment by gamalielhere** [comment]
closing due to duplicate #675
