### ISSUE TITLE
Can't access keystore wallet running MEW offline

### ISSUE THREAD

**Issue by russdirks** [MyEtherWallet/MyEtherWallet#675]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?

Running MEW offline, via double-click on index.html.
Go through the usual steps to open wallet via keystore file
After entering password, MEW hangs forever.
Works fine running MEW online, or locally under WAMP stack.

  - Please tell us about your environment:

Windows 10
Chrome, latest version
Running MEW offline

**Comment by gamalielhere** [comment]
@russdirks looks like Chrome doesn't let users use Workers when using local files, do you mind trying on Firefox?

**Comment by mining-visualizer** [comment]
Yup.  Firefox works.

**Comment by gamalielhere** [comment]
@mining-visualizer awesome. We're looking into this

**Comment by gamalielhere** [comment]
@russdirks @mining-visualizer This issue is due to chrome not allowing access to our separate worker file. We'll look more into this.

**Comment by gamalielhere** [comment]
@russdirks @mining-visualizer Closing this issue. should be fixed on the upcoming release
