### ISSUE TITLE
Can't find BNTY on MEW

### ISSUE THREAD

**Issue by CryptoSmileee** [MyEtherWallet/MyEtherWallet#678]
Hello,

I'm able to find BNTY in this list: https://github.com/MyEtherWallet/ethereum-lists/blob/master/tokens/tokens-eth.json

But when I open MEW then I can't see BNTY as a default token.

**Comment by wbobeirne** [comment]
Hey @CryptoSmileee, I believe you want to file an issue against the current live site's repo over here: https://github.com/kvhnuke/etherwallet/issues. This repository is for an upcoming rewrite of that site.

MEW v3 uses this file: https://github.com/kvhnuke/etherwallet/blob/mercury/app/scripts/tokens/ethTokens.json for loading tokens. You should open an issue asking for an update.
