### ISSUE TITLE
Add the gas price information

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#681]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/53050418-1e2efc80-344e-11e9-8871-2081f3fea89e.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Display the gas price information while user Send Tx/ Swap/... , "Edit" button will link to settings to edit default gas fee. 
  - What are the current issues this feature will solve
Need to put the gas price at obvious area.

**Comment by SteveMieskoski** [comment]
Included in release 5.0.10 via PR #925
