### ISSUE TITLE
Tokens search bar not working

### ISSUE THREAD

**Issue by waterdrop01** [MyEtherWallet/MyEtherWallet#686]
**BUG**
 Here is what I see:
![screenshot from 2019-02-20 09-26-59](https://user-images.githubusercontent.com/47316824/53077358-16289880-34f2-11e9-9538-f9d70fd4d669.png)

I suggest the top 200 tokens of coinmarketcap should be searchable (without having to add a "custom token"),

Thank you for your feedback on this!

**Comment by gamalielhere** [comment]
@waterdrop01 that's because that's what we have listed for ropsten. If you switched to ethereum network, it should show more tokens, which in turn shows better search results. Closing this as is not an issue.

**Comment by waterdrop01** [comment]
Thank you @gamalielhere , may I know where is the registry for these tokens information (name, address...etc)? (ie: where to submit a PR if some info needs to be fixed)
Thanks!

**Comment by gamalielhere** [comment]
@waterdrop01 You can make PR's here: https://github.com/MyEtherWallet/ethereum-lists/ and the tokens should sync.

**Comment by waterdrop01** [comment]
Got it, thanks. I'm wondering if there is a way to fill in information for testnets as well? I know a few projects that also have an "official" ERC 20 address of their token for testnets (ropsten, rinkeby, kovan)....

other question: are these files still used somewhere in MEW (worth sending a PR as well?):
- https://github.com/MyEtherWallet/MyEtherWallet/blob/8fbb3e2ce47282e25bc7ad390425153bef52a478/src/partners/changelly/config/currencies.js
- https://github.com/MyEtherWallet/MyEtherWallet/blob/8fbb3e2ce47282e25bc7ad390425153bef52a478/src/partners/partnersConfig/EthereumTokens.js

**Comment by gamalielhere** [comment]
@waterdrop01 There is, if you add your token on the appropriate network folder, it will be listed on the site when you're using the appropriate network. You can check [here](https://github.com/MyEtherWallet/ethereum-lists/blob/master/README.md#tokens) for instructions on how to add tokens to the list.

These files are used by our swap page. I'm not sure what you mean by sending PR.
