### ISSUE TITLE
Add option to export extended public key

### ISSUE THREAD

**Issue by waterdrop01** [MyEtherWallet/MyEtherWallet#687]
**Feature request**

Given MEW has access to the mnemonic/seed/extended private key, AND that MEW/Metamask are all HD wallets (deriving only one address but still HD wallets), there should be an option to export the `extended public key` so that users could easily import the xpubkey into **watch only** wallets.

That's something very common with Bitcoin, that is gaining traction in Ethereum.

Thank you for you feedback on this!

**Comment by deknowny** [comment]
Still actual question, any solution in existing wallets?
