### ISSUE TITLE
Hardwares page

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#689]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/53124338-f3a57800-350f-11e9-8ff8-197140d1d9b4.png)

![image](https://user-images.githubusercontent.com/31494364/53124344-f7d19580-350f-11e9-9e90-4a2e5b16c858.png)

![image](https://user-images.githubusercontent.com/31494364/53125594-3caafb80-3513-11e9-92c9-bbdbbdce7365.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Add a new page for Hardwares while user want to buy the hard wallet.
  - What are the current issues this feature will solve
Improved UX

**Comment by SteveMieskoski** [comment]
Done. Link to said page is present in the Discover portion of the footer.
