### ISSUE TITLE
Show message when the user has to confirm a transaction on a hardware wallet

### ISSUE THREAD

**Issue by Mrtenz** [MyEtherWallet/MyEtherWallet#696]
To make it clear to users that they have to confirm a transaction in order to sign it (at least on a Ledger Wallet, but I assume the same goes for a Trezor), I suggest adding a message somewhere after they press on the 'Generate Transaction' button.

**Comment by dternyak** [comment]
@Mrtenz Have you tried the latest develop? This feature has already been merged :)

**Comment by Mrtenz** [comment]
I was not aware that this had already been added. Sorry... :)
