### ISSUE TITLE
Token Conflict Resolution

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#704]
#### NOTE: This issue is largely a request for comment, as we need to develop a spec on how we should override / resolve conflicts before proceeding with the implementation. 

In cases where custom tokens and the default token list conflict with each other, we need to determine a conflict resolution process and override with either the custom token or the default token.

How should we handle conflicts between default/custom tokens when the default list updates with an existing custom token?
         - New token launches (TOKN)
         - MEW does not yet include TOKN in the default list
         - User inputs TOKN as a custom token
         - Later, MEW updates the default token list to include TOKN

- [ ] Do we clear the custom token in this case (and clear from LS)?
- [ ] What if the symbols are identical, but the contract addresses differ?
- [ ] What if the contract addresses are identical, but the symbols differ?
- [ ] What if the decimals differ?

**Comment by wbobeirne** [comment]
I think in the future, we'll end up expanding tokens with more metadata. Icons, full names, links, etc. So I think it's worthwhile to replace custom tokens users add with the real deal, if we end up adding them.

However, I think the way we use ticker as a unique ID right now is bad. It's very likely that we'll end up with a sizable conflict and some point, and there are plenty of small conflicts today. So here's what I'm thinking:

* If a custom token matches the address & decimal of a hard coded token, we remove it. Even if the ticker is wrong, some tokens change tickers if there's a conflict.
* Anywhere we enforce uniqueness (dictionaries, react element keys) we need to use a more unique thing than ticker. Perhaps something like ticker + address + decimal.
* Anywhere that we store token information long-term, we need to consider what things are possible to change. Tickers can definitely change, but it may even be possible for addresses and decimals to change too, assuming something catastrophic happens and the original contract is replaced or something like that.

The third one is the only thing that stumps me. If we can't be sure a token keeps its info, how else can we store and identify it?

**Comment by dternyak** [comment]
To your third point - this can largely be handled by maintainers of the token lists, unless I'm misunderstanding your statement.

I think between your first two points, we have enough of a spec for robust token conflict management. However, I favor amending the first point to remove the check for identical decimal and rely only on contract address. 

To summarize:
- Default token list is taken as the source of truth
- If a custom token matches the **contract address** of an existing default token, remove the custom token.
- If a custom token matches the **symbol** of an existing default token, remove the custom token.
    - NOTE: Users will still be able to have multiple tokens with similar symbols by adding a SYMB (2) or otherwise mutating the symbol name. 


We'll also need to ensure that we aren't listing multiple tokens with identical symbols in our own default token list. I'm not sure if this is an issue today, but I wanted to make a note of it.

**Comment by wbobeirne** [comment]
> this can largely be handled by maintainers of the token lists, unless I'm misunderstanding your statement.

I'm talking about local storage. Right now we store ticker for which tokens a wallet tracks, but that could be a problem if a token changes their ticker. Maybe it's minor enough to ignore though, users can always re-scan. I say we punt on this until we're told it's a problem by somebody.

The rest of that sounds good though. We can run a quick de-dupe every time someone unlocks their wallet, before we request token balances. Should be a fast enough process.
