### ISSUE TITLE
Non-webusb KeepKeys aren't going to work with MEW

### ISSUE THREAD

**Issue by keepkeyjon** [MyEtherWallet/MyEtherWallet#707]
We just noticed that keepkey.js was offering to pair with non-webusb KeepKeys, which isn't going to work:

```
An attempt to claim a USB device interface has been blocked because it implements a protected interface class.
```

 That probably spills over to some user frustration... anyway, the fix should be to update to [v1.2.1](https://github.com/keepkey/keepkey.js/releases/tag/v1.2.1), which includes this commit: https://github.com/keepkey/keepkey.js/commit/0c5b570d3c927aea172a6eaa347e2bec49e210a6

**Comment by keepkeyjon** [comment]
We're also limited to browsers that support WebUsb, which at the moment is Chrome and Opera. Not sure how to suggest that to users in your UI. Maybe gray out the KeepKey option, with a tooltip on those unsupported browsers?

**Comment by gamalielhere** [comment]
@keepkeyjon I'll go ahead and disable keepkey for other browsers not chrome and opera

**Comment by keepkeyjon** [comment]
I just pushed a different fix for this, which should reduce support requests on it / users thinking their device doesn't work. The new behavior is to allow selection of both HID and WebUSB keepkeys in the browser prompt, but throw an "update required" message if a HID device was selected.

That's implemented in  [v1.2.2](https://github.com/keepkey/keepkey.js/releases/tag/v1.2.2)

**Comment by gamalielhere** [comment]
@keepkeyjon what would you need on our end?

**Comment by keepkeyjon** [comment]
I think just pull the new package version when convenient.

**Comment by gamalielhere** [comment]
Awesome. Thank you for informing us!

**Comment by keepkeyjon** [comment]
not sure if the thrown error is turned into a UI thing, but at least it will show up in console logs, making debugging it easier.
