### ISSUE TITLE
Add Tx information in wallet page

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#715]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/53293188-045e2400-3784-11e9-962a-d1f354fa5836.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Add Tx information while user send Tx/Swap/... Default optional Regular, and also user can setup after click edit button. 
  - What are the current issues this feature will solve
User complain that they can not find the Gas Fee very easily.

**Comment by SteveMieskoski** [comment]
Included in release 5.0.10 via PR #925
