### ISSUE TITLE
Doesn't detect token balances when it is below 1

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#717]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - If you access an account that has any ERC-20 token and if that balance is between `0` and `1`, then it shows `0` as token balance.

**Comment by gamalielhere** [comment]
I'm not sure this is accurate as seen here: 
<img width="354" alt="screen shot 2019-02-25 at 3 03 23 pm" src="https://user-images.githubusercontent.com/16236741/53374880-8ed28f00-390e-11e9-9411-4f5426ef37e5.png">

**Comment by alepc253** [comment]
Thanks @gamalielhere, this is what I see:
- Network: RSK (mainnet)
- Address: 0xe6671d3846c57de1c559ff2da7bc0f4b4fea9521

When balance is 1:

<img width="1143" alt="captura de pantalla 2019-02-26 a la s 14 18 01" src="https://user-images.githubusercontent.com/3451282/53433197-bdb23900-39d2-11e9-99d1-4ed172bd4650.png">
<img width="1218" alt="captura de pantalla 2019-02-26 a la s 14 20 04" src="https://user-images.githubusercontent.com/3451282/53433218-c9056480-39d2-11e9-830d-3e5f97a987cf.png">

And when balance is 0.5:

<img width="1170" alt="captura de pantalla 2019-02-26 a la s 14 24 26" src="https://user-images.githubusercontent.com/3451282/53433257-da4e7100-39d2-11e9-867a-6f6fb40a696d.png">
<img width="1181" alt="captura de pantalla 2019-02-26 a la s 14 24 53" src="https://user-images.githubusercontent.com/3451282/53433274-e0445200-39d2-11e9-8d78-6724540ab83a.png">

**Comment by gamalielhere** [comment]
@alepc253 is there a token faucet for testnet? I wanna figure out why this is happening

**Comment by gamalielhere** [comment]
<img width="979" alt="screen shot 2019-03-01 at 2 51 20 pm" src="https://user-images.githubusercontent.com/16236741/53671074-b6d53180-3c31-11e9-84f6-5c36b033b75f.png">

**Comment by gamalielhere** [comment]
Closing this as this seems to be fixed.
