### ISSUE TITLE
Checksum problem with address fields in "Interact with contract"

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#718]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - Interacting with contracts using RSK network, setting address fields with RSK checksummed addresses, it fails because of web3 address validation.

**Comment by SteveMieskoski** [comment]
Closing as related PR #736 was merged on 2/28/2019
