### ISSUE TITLE
[Help Wanted] How many ledger nano s addresses can be used?

### ISSUE THREAD

**Issue by andrewkm** [MyEtherWallet/MyEtherWallet#720]
Using my Ledger Nano S with MyEtherWallet and I seem to be able to click "More Addresses" endlessly when on the default m/44'/60'/0' for Ledger.

How many of these are actually mine and how many are stored in my Ledger Nano S?

Can I simply send coins to all these addresses, and they will be on my Ledger Nano S forever? Kind of trying to grasp the actual amount of addresses I have access to.

Any help would be appreciated. Thanks.

**Comment by skubakdj** [comment]
Hi @andrewkm! All of these addresses are yours and all of them can be used. Ledger implements some fancy cryptography to turn your seed phrase into an unlimited number of public/private keypairs. You can read more about this on our knowledge base article [here](https://myetherwallet.github.io/knowledge-base/hardware-wallets/multiple-addresses-on-hardware-wallet.html).
