### ISSUE TITLE
Add Tx history link in the wallet page Nav-bar

### ISSUE THREAD

**Issue by jackhuangusa** [MyEtherWallet/MyEtherWallet#729]
- **I'm submitting a ...**

  - [x] Feature request
  - [ ] Bug report

![image](https://user-images.githubusercontent.com/31494364/53442256-c1879080-39bd-11e9-9096-c4ce21ff14a9.png)

- **Feature Request**

  - Briefly explain the feature you would like us to implement
Add "Transaction History" link in the wallet page Nav-bar, those links will link to the page relative about current address.

  - What are the current issues this feature will solve
User can easily find their Transaction history

**Comment by hsurf22** [comment]
https://github.com/MyEtherWallet/MyEtherWallet/pull/865
