### ISSUE TITLE
MEW does not provide options for hardware wallets when signing messages

### ISSUE THREAD

**Issue by mperklin** [MyEtherWallet/MyEtherWallet#73]
Mew's compatibility with Trezor and Ledger Nano S wallets on the [Send Tokens](https://www.myetherwallet.com/#send-transaction) page makes it a very powerful webpage.

However, these options are not present on the [Sign Message](https://www.myetherwallet.com/signmsg.html) page.

I'd love to see MEW duplicate the existing hardware wallet functionality for signing messages as is already implemented for sending tokens.

**Comment by tayvano** [comment]
https://github.com/kvhnuke/etherwallet/issues/409

https://github.com/kvhnuke/etherwallet/issues/651
