### ISSUE TITLE
Failed TX (Bad Instruction)

### ISSUE THREAD

**Issue by markfoster123a** [MyEtherWallet/MyEtherWallet#733]
Hi, I sent some WISH tokens from myetherwallet but on etherscan the tx failed and said contract failed due to bad instruction. How can I receive my tokens back to myetherwallet?
TxHash:0xbf5d8107b232d4d1f90b8bf8d4f5c8b7d62e0e81daedcbf2033492b759b29936 
TxReceipt Status:Fail
Block Height:4856769 (41 block confirmations)
TimeStamp:11 mins ago (Jan-05-2018 06:29:55 AM +UTC)
From:0x2c59de62accac419fc43f3a911d77c0d40d07873
To:Contract 0x1b22c32cd936cb97c28c5690a0695a82abf688e6 (MyWishToken)  
 Warning! Error encountered during contract execution [Bad instruction] 
  ERC-20 Token Transfer Failed to complete, check with sender for more information.Value: 0 Ether ($0.00) Gas Limit: 200000 Gas Used By Txn: 200000 Gas Price: 0.00000003 Ether (30 Gwei) Actual Tx Cost/Fee: 0.006 Ether ($6.04) Cumulative Gas Used: 6818561 Nonce: 63

**Comment by dternyak** [comment]
Hi @markfoster123a 

This is the V4 issue tracker. My guess is that you have experienced this on the existing site at myetherwallet.com, where the issue tracker is found at github.com/kvhnuke/etherwallet.

The bad instruction warning you received is a fairly generic error message, but it's possible the gas limit was simply too low. You may be able to get additional help by emailing support@myetherwallet.com if this problem persists.

Best,
Daniel
