### ISSUE TITLE
Clear `dist` between builds

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#744]

**Comment by wbobeirne** [comment]
Thanks for opening this. I see we have rimraf running, but I think it's misconfigured. Something like https://github.com/johnagan/clean-webpack-plugin should be more of a sure-fire thing, but if we want to avoid external dependencies, nothing too difficult about running our own with https://nodejs.org/api/fs.html#fs_fs_rmdirsync_path.
