### ISSUE TITLE
Rotate Promos

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#750]
Promo's are chosen randomly, and persist until the next wallet session.

- [ ] Rotate promos every 10 seconds.

<img width="449" alt="screen shot 2018-01-08 at 11 26 11 am" src="https://user-images.githubusercontent.com/7861465/34683150-c1390700-f466-11e7-9e30-c5244e946a3d.png">

**Comment by wbobeirne** [comment]
Would also like to see a little bit of animation on this if it auto rotates as well, to be less jarring. Just a quick swipe or fade.
