### ISSUE TITLE
Inconsistency in confirmation popup at send-transaction

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#755]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - If you try to send a transaction in RSK network, confirmation popup shows ETH currency symbol and icon:

<img width="670" alt="captura de pantalla 2019-03-01 a la s 14 45 44" src="https://user-images.githubusercontent.com/3451282/53656134-167f0d00-3c31-11e9-84e7-27156e357d02.png">

**Comment by gamalielhere** [comment]
@alepc253 can you verify on the footer that you're on v5.0.5?

**Comment by alepc253** [comment]
@gamalielhere I was suspecting that... I'm right now on that, give me a moment

**Comment by alepc253** [comment]
@gamalielhere awesome! it's fixed... I rose the issue before updating my fork, based in former notes I did

**Comment by gamalielhere** [comment]
@alepc253  Good catch! I noticed this yesterday too and fixed it for the release.
