### ISSUE TITLE
Error revealing ENS bid

### ISSUE THREAD

**Issue by brnpope** [MyEtherWallet/MyEtherWallet#765]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Feature Request**

  - Briefly explain the feature you would like us to implement
  - What are the current issues this feature will solve
  - Is this feature cross compatible with other ethereum networks
  - Are you willing to help us with development support if required
  - Where can this be added? e.g: `/interface`, `/create-wallet`, etc.

- **Bug Report**
  - What is the current behavior?
  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
  - What is the expected behavior?
  - What is the motivation / use case for changing the behavior?
  - Please tell us about your environment:
    - Operating system
    - Browser and version
  - Other information (e.g. detailed explanation, stacktraces, related issues, suggestions how to fix, links for us to have context, eg. stackoverflow, gitter, etc)
  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.

**Comment by brnpope** [comment]
See screenshot
[MyEtherWalletENSerror.pdf](https://github.com/MyEtherWallet/MyEtherWallet/files/2928457/MyEtherWalletENSerror.pdf)

**Comment by gamalielhere** [comment]
Closing as this will be irrelevant as of today.
