### ISSUE TITLE
Invalid ERC-20 Tokens listed

### ISSUE THREAD

**Issue by AdrianMF** [MyEtherWallet/MyEtherWallet#777]
In the section "Token Balances" the following tokens return
(error_21) Not a valid ERC-20 token
If they are invalid, should they not be removed from the list? Also as the return errors when you click "Show Only Balances" after loading, they still remain with the error rather than being removed.

The tokens are
BCV, INSP, PIXEL, RCT, RVL

**Comment by dternyak** [comment]
Hey Adrian,

This is the issue tracker for V4, not the existing production site. My guess is you're experiencing this issue on the production site.

We're working on a fix for this and other issues in the latest release, which should be out very soon.

Best,
Daniel
