### ISSUE TITLE
Change LYMPO token contract

### ISSUE THREAD

**Issue by MariusLympo** [MyEtherWallet/MyEtherWallet#778]
- **Change Request**

Would like to inform that we did the token swap. 

From February 27th 9:00 UTC, existing LYM token with contract https://etherscan.io/token/0x57ad67acf9bf015e4820fbd66ea1a21bed8852ec was swapped with a 1:1 ratio with new LYM token with same decimals - 18; same name LYM (Lympo). New, upgraded contract - https://etherscan.io/token/0xc690f7c7fcffa6a82b79fab7508c466fefdfc8c5 

Our official announcement. Please find below 
https://medium.com/lympo-io/its-time-to-upgrade-the-lym-token-token-swap-information-f1b4aea9a94a

Etherscan already swapped our contracts and we would like to make a possibility to put old Lympo contract as a custom token and keep new contract LYM token as default in MEW. This will help our users and will not make confusing in the future.

**Comment by gamalielhere** [comment]
@MariusLympo users has to add it themselves to be a custom token. This token will be updated on the next release and has been updated here: https://github.com/MyEtherWallet/ethereum-lists/commit/51c24df668871892a83f36eecaf4fcd5c2f45000
