### ISSUE TITLE
Sidebar

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#78]
This is the sidebar that shows up on on Send and a few other pages. It should probably be its own container, to keep it pretty autonomous (Instead of a component that purely receives props.)

- [x] Account Address
- [x] Account Balance (ETH)
- [x] Token Balances
- [x] Transaction History (links ATM)
- [x] Equivalent Values
- [ ] Equivalent Values - Tokens
- [x] Donate Button

**Comment by wbobeirne** [comment]
I just realized this is a dupe of #90, so I'll close in favor of that.
