### ISSUE TITLE
Error - Make sure contract data is on 

### ISSUE THREAD

**Issue by dorpik** [MyEtherWallet/MyEtherWallet#784]
Im trying to transfer tokens from MEW 

Im getting an error - Makes sure contract data is on ?

any ideas what is the reason and solution ?

Thanks

**Comment by dternyak** [comment]
Hi Dorpik,

This is the issue tracker for the re-implementation of the existing myetherwallet.com.

You might find it useful to post in github.com/kvhnuke/etherwallet, or contact support@myetherwallet.com.

Best,
Daniel
