### ISSUE TITLE
Setup Test for Pinned Package Versions

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#794]
- [ ] Disallow non-exact versions (`~`, `^`) in package.json

**Comment by dternyak** [comment]
@jclancy93 I think this is right up your alley ;)

**Comment by wbobeirne** [comment]
I actually don't think this would run as a part of the linter, as package.json isn't known to webpack or typescript. I think we're best off with a jest test, ala the token and contract tests, that simply traverses the json file and looks for issues.

**Comment by dternyak** [comment]
Totally on point. 👍
