### ISSUE TITLE
Wallet Decrypt

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#80]
### Requirements

- [x] 1. Keystore
- [x] 1b. Presale JSON
- [x] 2. Raw private key
- [x] 2b. Deprecated Encrypted Private Key
- [x] 3. Bip39 Mnemonic with custom path / any number of words / password
- [ ] 5. Ledger
- [x] 6. Trezor
- [ ] 7. Address only (will be used on view wallet and send page for offline?)

##### Future (Low Priority)

"Is having the wallet info disappear on each tab-change a feature? Would it be better if it persisted between tabs? (The only implication I can think of is how would a user "sign out" of their wallet so they could choose another one.)"

- [ ] 5 minutes -> show warning that their wallet is unlocked in the top tabby-guy (meta title tag)
- [ ] 30 minutes of no interaction -> lock wallet, force user to unlock again
- [ ] If user wants to use a different wallet, tell them to refresh the freaking page?
- [ ] I'll make a little wallet icon with a cross through it or something that they can click to clear the current wallet from the current state and show the decrypt panel again
- [ ] Keepkey Hardware Wallet
- [ ] Improve UX of decryption of keys with high n values kvhnuke/etherwallet: Issue #486
- [ ] Hitting enter should unlock wallet

Github Ref

1. Make sure to strip beginning 0x from raw private keys: kvhnuke/etherwallet#400
3. Allow Metamask users to use metamask + mew? kvhnuke/etherwallet#238
4. High n values in keystores -> frozen browser kvhnuke/etherwallet#43

**Comment by crptm** [comment]
I think we can have #2 anyway just treat it as address only?

**Comment by dternyak** [comment]
Took it out

**Comment by wbobeirne** [comment]
Trezor is up via #137, lays groundwork for Ledger and Mnemonic.

**Comment by wbobeirne** [comment]
Pulled myself off of this as Trezor is in. I think we should consider breaking this monolithic task out into many more smaller granular tasks. I see 4-5 possible PRs contained in this, and many of these are questions about how we should implement future stuff, not well defined certain tasks.

**Comment by dternyak** [comment]
Agreed. If you're interested, it would be great to have you break this up into more well defined and smaller issues (especially since you should have a well developed mental model based on your trezor work).

**Comment by wbobeirne** [comment]
I have split this task out into #214, #215, #216, #217, #218, #219, and #220 for the remaining outstanding issues. Closing this one out and following up on those instead.
