### ISSUE TITLE
Says "Send ETH & Tokens" even if the currency symbol is another

### ISSUE THREAD

**Issue by alepc253** [MyEtherWallet/MyEtherWallet#811]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - Both side menu and title say "Send ETH & Tokens" even if the currency symbol (or network name) is another.

**Comment by jackhuangusa** [comment]
Thanks for your feedback.
![Screen Shot 2019-03-15 at 3 20 15 PM](https://user-images.githubusercontent.com/31494364/54464984-32f16e00-4736-11e9-8635-a5e46b18013d.png)

**Comment by gamalielhere** [comment]
Included in #814
