### ISSUE TITLE
Tiniest +/- the user can hardly see

### ISSUE THREAD

**Issue by jidanni** [MyEtherWallet/MyEtherWallet#822]
I was testing [offline](https://myetherwallet.github.io/knowledge-base/offline/running-myetherwallet-locally.html). There is the tiniest
`<a class="collapse-button"><span ng-show="wd" class="ng-hide">+</span><span ng-show="!wd" class="">-</span></a>`
`+`/`-` toggle button that the user can barely see!
If he accidentally ends up clicking on it (`-`) there will be a big white area in the middle of the screen open up. And unless one looks hard one cannot find the tiny `+` to restore it. Maybe some kind of stylesheet is missing offline. I did not test it online.

**Comment by dternyak** [comment]
This is the V4 repo which no longer uses this UI. Please take a look at https://alpha.myetherwallet.com for an up-to-date version of the UI.
