### ISSUE TITLE
Off-center Nonce Field

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#834]
<img width="833" alt="screen shot 2018-01-15 at 11 31 10 am" src="https://user-images.githubusercontent.com/7861465/34954860-a355873c-f9e7-11e7-86b1-5595ae7d6a32.png">

**Comment by oskarszoon** [comment]
@eddiewang I was playing around with the alpha codebase and this bug annoyed me more than it should have :). The fix is available in the pull request
