### ISSUE TITLE
Advanced Gas Price Input Validation

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#839]
- [ ] Don't allow negative gas price
- [ ] Set upper bound on gas price. 10000 Gwei? Open to input.

**Comment by wbobeirne** [comment]
One thing of note here is I didn't re-use the GasPriceFieldFactory in gas slider, but I probably should. The slider itself shouldn't need validation (Since it's not user-controlled ranges) but the input in advanced mode should probably be converted to the common factory or input component.

**Comment by skubakdj** [comment]
AFAIK, we don't yet have a standard component for gas price, only for gas limit. Validation in #872 has been added on top of existing code, but I'd be down to do a full implementation at some point to get more experience with HoCs.
