### ISSUE TITLE
Redux Test Suite Expansion

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#84]

**Comment by bfillmer** [comment]
General coverage improvements or....?

**Comment by dternyak** [comment]
Yes.
I'm not sure if we need to formalize a specific number, but it should be
significantly higher than it is today (with many reducers / sagas
completely untested).

**Comment by bfillmer** [comment]
WIP @ https://github.com/MyEtherWallet/MyEtherWallet/tree/redux-test-improvements

@dternyak One improvement to consider is leveraging snapshot testing for these. Effectively replace defining expected results with snapshots that are auto-generated. Example: https://github.com/bfillmer/todo-and-tonic/blob/master/src/state/reducers/todos.spec.js

When iterating on the test the first time through you update the snapshot until you see the state you expect, then leave it. In the future if any code changes would affect the state shape the snapshots won't match up and Jest will let you know. If it's an expected change you can simply update the snapshot, if not then you know to start digging into the issue.

**Comment by dternyak** [comment]
I've heard good things about snapshot testing as well. Seems like a good approach 👍
