### ISSUE TITLE
RSK Ledger App is not working in MEW

### ISSUE THREAD

**Issue by jonathansmirnoff** [MyEtherWallet/MyEtherWallet#849]
- **I'm submitting a ...**
  - [ ] Feature request
  - [X] Bug report

- **Bug Report**
  - MEW is not working with RSK Ledger APP.  Steps to Reproduce:
    - Go to *Access My Wallet*
    - Select *Hardware*
    - Select *Ledger* (previous you have to unlock the device and open RSK App)
    -  Click on *Choose Hardware*
    -  Then you will get the error **Ledger device: UNKNOWN_ERROR (0X6804)**
  -  If you open the ethereum app, you can access without problem. This is happing with RSK Mainnet and testnet apps. 
  - It's possible to use the same device and RSK apps in MyCrypto without any issue. So I think it's a specific issue of MEW.
 -  Ledger Info: Ledger Nano, Firmware `1.5.5` and RSK Apps version `1.2.0`

**Comment by SteveMieskoski** [comment]
This is likely related to ledger apps in general and is due to a change in how they process BIP32/BIP44 paths.  The PR #910 included in release 5.0.10 should fix this issue. Will reopen if this is not the case.
