### ISSUE TITLE
Confirmation Modal

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#85]
## Send TX Confirmation Modal should display:

- [ ] Warning: You are about to....
- [ ] [ Address ] + [ AddressIcon from ] -> [ Value ] [ CoinType ] -> [ Address ] + [ AddressIcon ] to
- [ ] The [ ETH ] node you are sending through is provided by [ MyEtherWallet ].
- [ ] Address From:
- [ ] Address To:
- [ ] Value:
- [ ] CoinType:
- [ ] Gas Limit:
- [ ] Gas Price:
- [ ] Nonce:
- [ ] Data:
- [ ] Chain ID:
- [ ] [Unsigned TX Textarea]
- [ ] [Signed TX Textarea]
- [ ] Cancel Button
- [ ] Yes, I'm sure Button

### Future:

Current issues with current conf modals

1. People dont read them (had someone the other day literally tell me we need a confirmation for the confirmation....)

3. Too easy to miss the coin you are sending (e.g. ETH vs SNT)

5. Too easy to miss the chain you are on (ETC vs ETH), although the border I added has helped reduce those

7. Not the information the user wants / needs in an easily parsable / skimmible thing (table format will help)

#### Misc notes from Taylor:
"Separately, I hate how modals sometimes close all by themselves sometimes if you click twice or click outside. I do it on Twitter all the time and I think it's worse with bootstrap v4. I lose tweets ALL THE TIME when I'm trying to highlight something.

It shouldn't close unless you hit the X or the CANCEL button or hit the esc button (optional)

--

Other than that, I really like the success / error state inside the modal itself, but we'll have to decide how to handle alerts and things. While some successes and errors come from front-end validation, some are message returned directly from the node (e.g. a TX with that hash has already been imported). It would be safer to handle all alerts via the alerts handler, avoiding a potential situation where you sometimes show alert, sometimes put alert in modal, and if you aren't careful, accidentally don't show the alert at all. Making things fail-proof for our future selves is very important so we can build quickly with less worry. 😉"

**Comment by wbobeirne** [comment]
This was taken care of with #108.
