### ISSUE TITLE
Bad calculation of nonce

### ISSUE THREAD

**Issue by jonathansmirnoff** [MyEtherWallet/MyEtherWallet#850]
- **I'm submitting a ...**
  - [ ] Feature request
  - [X] Bug report

- **Bug Report**
  - If a transaction is not mined, this transaction it's considering in the nonce count. So it's posible to corrupt the local db and not allow to do any transfer from this account. The only solution to this is to force a particular nonce or clean the db.
   - **Steps to Reproduce**:
     - Get a new account with gas.
     - Create a tx and force a lower gas limit.
     - Check that the transaction appears in Notifications in pending state and never is confirmed or failed.
     - Create a new tx and review that the suggested nonce is increased by 1.
     - Repeat these steps to get nonce higher, like 20. After that situation you will not be able to do any transaction from that account.
  
  - **Workaround**
    - It is important to use the method `eth_getTransactionCount` to get the correct value of the nonce and avoid to use local db transaction count.
Also if the local cache is cleaned MEW checks the nonce using `eth_getTransactionCount`

**Comment by gamalielhere** [comment]
bump

**Comment by alepc253** [comment]
Hi @gamalielhere, any thoughts about this issue? Does it make sense to work in a PR to solve this?
