### ISSUE TITLE
Cannot run from filesystem in Brave.

### ISSUE THREAD

**Issue by MicahZoltu** [MyEtherWallet/MyEtherWallet#855]
- **I'm submitting a ...**
  - [X] Bug report

- **Bug Report**
1. Download the latest releases from GitHub
1. Launch Brave.
1. Open index.html in Brave.
1. Notice that in the browser console you receive n error that access to window.localStorage is denied for this document.

I'm guessing the issue is that Brave doesn't support local storage access for pages loaded from localhost.  It feels like it should be possible to utilize most of MEW without localstorage access, can this feature be wrapped up so if unavailable the rest of MEW works without it?

**Comment by SteveMieskoski** [comment]
@MicahZoltu I was able to get Brave to open the site, but I had to change the cookie control setting in Brave shields defaults to allow all cookies. Hope this helps. 
![Screenshot from 2019-04-10 19-58-06](https://user-images.githubusercontent.com/19334138/55927810-36f49c80-5bcb-11e9-987b-33e13e672ef1.png)

**Comment by MicahZoltu** [comment]
Thanks for the workaround.  Will this issue remain open to try to make MM work with MetaMask without having to disable cookie control?

**Comment by MicahZoltu** [comment]
Why was this closed?  Has the issue been resolved?

**Comment by MicahZoltu** [comment]
Can I just say that I hate stale bot.  Issues don't magically fix themselves!

This is still a problem.

**Comment by kvhnuke** [comment]
@MicahZoltu unfortunately this is not on our end, this is a security "feature" in brave.
Closing as we dont have control over how brave implements their features

**Comment by MicahZoltu** [comment]
@kvhnuke It seems that MyEtherWallet should be able to work just fine without local storage.  At the least, it should be able to gracefully degrade.
