### ISSUE TITLE
Cannot change gas on contract calls.

### ISSUE THREAD

**Issue by MicahZoltu** [MyEtherWallet/MyEtherWallet#856]
- **I'm submitting a ...**
  - [X] Feature request

- **Feature Request**
When submitting a transaction via a custom contract call, I should be able to set the gas price.  I can fill in the contract details , but I am never given the opportunity to set the gas price.

Note: I was using a ledger for signing, in case that matters.

**Comment by MicahZoltu** [comment]
This is still a problem.

**Comment by MicahZoltu** [comment]
Is there a way to disable the stale bot for feature requests?  Until the feature is actively implemented, this issue will continue to remain "active" since features don't magically get implemented by themselves (unlike bugs, which _sometimes_ fix themselves).

**Comment by kvhnuke** [comment]
You can change the gas price in settings, click on the upper right corner logo and select settings

**Comment by MicahZoltu** [comment]
@kvhnuke Ah, I wasn't aware of that feature.  Thanks!
