### ISSUE TITLE
Ledger times out too quickly.

### ISSUE THREAD

**Issue by MicahZoltu** [MyEtherWallet/MyEtherWallet#857]
- **I'm submitting a ...**
  - [X] Bug report

- **Bug Report**
When signing a transaction with a Ledger Nano S, if I read through the prompts on the ledger to verify the transaction is what I expect, by the time I get through them all and confirm MEW has timed out the transaction.

Note: When this happens, the UI gets into a state where I have to reset everything to proceed.  The confirmation dialog has to be closed, and when I close it the Read/Write contract (operation I was trying to do) is stuck with a spinner.  The only way to get past the spinner is to go back, which puts me back at a blank contract screen where I have to provide the ABI + address again.

**Comment by SteveMieskoski** [comment]
See PR #861 , which increased the timeout duration
