### ISSUE TITLE
Signature backward compatibality

### ISSUE THREAD

**Issue by realcodywburns** [MyEtherWallet/MyEtherWallet#869]
Messages signed with version 3.x are not able to be verified in 4.x due to the more expressive formatting. Signature vs sig, message vs msg, etc

**Comment by wbobeirne** [comment]
Great catch on this oversight. We should probably revert to the old keys, rather than trying to create a mapping, so that v3 is also compatible with v4 signed messages.

**Comment by dternyak** [comment]
Thanks for catching this @realcodywburns. We'll make sure to get this fixed before launching V4.
