### ISSUE TITLE
How to get listed on "Select Existing Contract" dropdown for both ETH and ETC?

### ISSUE THREAD

**Issue by ProphetDaniel** [MyEtherWallet/MyEtherWallet#87]
* **I'm submitting a ...**
    - [X] Feature request
    - [  ] Bug report

* **Feature Request**
    - I couldn't find any info on how to achieve this.

* **Bug Report**
    - If you Click the Select Existing Contract, a few selected contracts are there. And there is no way or indication about how to add yours.

**Comment by gamalielhere** [comment]
@ProphetDaniel you can go to [https://github.com/MyEtherWallet/ethereum-lists/](https://github.com/MyEtherWallet/ethereum-lists/), make a PR and follow the format.
