### ISSUE TITLE
My Ether Wallet- Locked out 

### ISSUE THREAD

**Issue by eshin90** [MyEtherWallet/MyEtherWallet#877]
My macbook has recently been wiped out from a failed Sierra OS update that was facilitated by recent news of Apple's faulty chip/battery slow down. I took it to the Apple Store and the technicians reinstalled the previous version but had deleted all my files in the process. I had previously stored my Keystore file on my mac and have reached out to Apple technicians but couldn't restore my previous files from Time Machine. I dont have the Private Key or UTC file either... all I have is the Public address and password. 

Is there anyway for me to retrieve the contents inside the wallet?
I have 2,000 Tokens inside and I will give 1,000 to anyone who can help get them out. 

Best, 
ES

**Comment by wbobeirne** [comment]
Hey @eshin90, that's awful to hear, I'm really sorry. Without the keystore file or private key, I'm afraid there isn't much anyone can do. Your best bet would be to **stop using your mac right now** and try to find an expert in hard drive file recovery. The files could potentially still be on the hard drive, not yet overwritten, but the more you use it, the slimmer that chance gets.

This issue queue is intended for the development of v4 of MEW, so I'm going to close this issue. I'm terribly sorry this has happened to you though.
