### ISSUE TITLE
Increase n-value of keystore files to `8192`

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#896]
Ethereum keystores have been added to hashcat. I'm not longer comfortable using a low of an n-value. Also, n values must be 2^n. In this case, 8192 is 2^13.

https://stealthsploit.com/2018/01/04/ethereum-wallet-cracking-pt-2-gpu-vs-cpu/

2^13 puts us at GPU-incompatible under 32 GB cards. 2^14 at 64GB cards. Both are sufficiently stronger than the current values and should be high enough for the foreseeable future.

Attackers can still CPU brute-force but that’s a miserable undertaking and making them miserable is enough for me.

**Comment by dternyak** [comment]
I copied this comment into https://github.com/MyEtherWallet/MyEtherWallet/issues/889 (original version of this issue).

Going to close this one since the other already exists.
