### ISSUE TITLE
Warn users if they are sending tokens to a token contract address (address in the list in /ethereum-lists)? 

### ISSUE THREAD

**Issue by tayvano** [MyEtherWallet/MyEtherWallet#900]
Non-blocking, but would be excellent for UX. Same vein as an "Address not checksummed" warning where it displays but doesn't actually prevent user from sending if they truly want to.

We're having more and more users who send their tokens *to* the token contract address and these token teams can't / won't help them recover their funds, which is the real shame here.

**Comment by wbobeirne** [comment]
Using the addresses in `/ethereum-lists` is probably going to be implemented in a separate ticket, at some point we should get rid of all hard-coded lists in this repo and key everything off of `/ethereum-lists`.
