### ISSUE TITLE
Transaction with specific data fails from Ledger wallet in Google Chrome

### ISSUE THREAD

**Issue by voldemarz** [MyEtherWallet/MyEtherWallet#913]
- **I'm submitting a ...**

  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
When using Ledger Nano S and Google Chrome, it appears that some specific kinds of data field contents cause incorrectly generated transactions resulting in wrong "from" field. Thus transaction fails complaining that there is not enough funds.

This is similar issue as with mycrypto.com where I also reported bug https://github.com/MyCryptoHQ/MyCrypto/issues/2485

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
1. Access wallet using Ledger Nano S (I have one with Firmware 1.4.2, MCU 1.6).
2. Try to send transaction worth 0 ETH to own address with data fields contents being 
0xaa0b7db72e4ce97d7a3090b086c7a48b1df5c0986fd2ab42ab6b69a1543d2c5b55c00d960000000000000000000000000000000000000000000000000000000000712cdd0000000000000000000000000000000000000000000000000000000000000060000000000000000000000000000000000000000000000000000000000000004110bc253955794fb2e444675db13cf351ce4cf6635ffb8584f33b15728a5823293707af47f700c2577ab0b3448e20d004d90059494125919bad118bab318b02e30000000000000000000000000000000000000000000000000000000000000000
3. Confirm transaction on ledger
4. Confirm transaction in web popup (observe that "from" address is displayed as expected here)
5. Receive error claiming that insufficient funds

  - What is the expected behavior?
Transaction doesn't fail.

  - Please tell us about your environment:
Browser: Google Chrome (issue not present in Brave or Opera)
Browser version: Version 73.0.3683.103 (Official Build) (64-bit)
Operating system: Windows 10 (version 1803)
Reproduced on 2 different devices.

  - Where can this be found?
/access-my-wallet

See screenshots

![mew1](https://user-images.githubusercontent.com/1264210/55677017-d884a100-58e0-11e9-994d-d3d156edff75.png)
![mew2](https://user-images.githubusercontent.com/1264210/55677022-dc182800-58e0-11e9-8394-1a621ca6e25f.png)

**Comment by SteveMieskoski** [comment]
OP reported that updating ledger to firmware 1.5.5 and MCU 1.7 cleared up the issue. [See Here](https://github.com/MyCryptoHQ/MyCrypto/issues/2485#issuecomment-480550876)

**Comment by voldemarz** [comment]
@SteveMieskoski I was the OP. I think it's more likely that issue is not gone completely, just needs different kind of data to trigger it after FW update. The fact that issue was not appearing in all browsers seems imply that root cause was not in Ledger.
