### ISSUE TITLE
Can't reach bottom of the page due to no scroll bar

### ISSUE THREAD

**Issue by voldemarz** [MyEtherWallet/MyEtherWallet#914]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  - What is the current behavior?
Due to no scroll bar I can't reach bottom of the page including the Send Transaction button.

  - If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem
Just access the wallet.

  - What is the expected behavior?
I can scroll to the bottom of the page.

  - Please tell us about your environment:
Browser: Google Chrome (issue not present in Brave or Opera)
Browser version: Version 73.0.3683.103 (Official Build) (64-bit)
Operating system: Windows 10 (version 1803)
Laptop with display resolution 3200x1800 and scaling set to 200% in Windows display settings.

  - Where can this be found? e.g: `/interface`, `/create-wallet`, etc.
/access-my-wallet

![image](https://user-images.githubusercontent.com/1264210/55677110-2fd74100-58e2-11e9-817b-cd4f32af2b7b.png)

**Comment by SteveMieskoski** [comment]
PR #941 should fix the problem
