### ISSUE TITLE
View with Address Only

### ISSUE THREAD

**Issue by dternyak** [MyEtherWallet/MyEtherWallet#92]
- [x] Show Address
- [x] Show Balances
- [ ] Print Paper Wallet

Github Ref

1. Feature: kvhnuke/etherwallet: Issue #507 Bookmarkable / refreshable page
2. Feature: Printable mnemonics if they unlock via mnemonic kvhnuke/etherwallet: Issue #493

**Comment by wbobeirne** [comment]
From discussion on weekly call, I think the implementation of this is going to be:

1) Remove "View Wallet Info" tab
2) Rename "Send Ether & Tokens" tab to "View Wallet & Send" (Feel free to suggest something better)
3) Make this tab have subtabs (ala contracts) for sending and viewing wallet info. The latter is where we'll add redownload paper wallet / redownload wallet file / convert to password wallet etc.

This will remove the need for a second tab for this, and remove the need for unlocking your wallet twice to do these things. Let me know if any of that doesn't sound good.

**Comment by dternyak** [comment]
R/e renaming the send tab -- I'm in favor of "Account"

**Comment by wbobeirne** [comment]
Started off on this but unfortunately the changeover to `ethereumjs-wallet` is making this a little tough to fit in. Their [wallet constructors](https://github.com/ethereumjs/ethereumjs-wallet#wallet-api) only have a `fromPublicKey`, not a `fromAddress`. As far as I know, there's no way to derive the public key from the wallet address. So I think my current plan is to stub out the wallet as best as I can. Hopefully this doesn't result in strange behavior where we fail to account for the read-only view.

**Comment by wbobeirne** [comment]
Disregard previous comment, first PR up that works with this :)

WRT "Account", my only concern would be people assuming they have some kind of server-side MEW account. But maybe I'm putting too much stake into that word. I'll start with that for the next PR.

**Comment by wbobeirne** [comment]
I'm hesitant to try and rework the send tab too much while #456 is on the horizon, so I think I'm going to limit my progress this sprint to #386 and #387. I'll circle back around to creating a proper wallet info tab once the refactor is over and merged.

**Comment by wbobeirne** [comment]
This is merged into `transaction-refactor`, so I'm marking this closed, though it's not in develop yet.
