### ISSUE TITLE
clicking transaction hash link doesn't work

### ISSUE THREAD

**Issue by dgobaud** [MyEtherWallet/MyEtherWallet#923]
after submitting a transaction clicking the hash in the green success message at the bottom doesn't work in Chrome 63.0.3239.132 (Official Build) (64-bit)

**Comment by wbobeirne** [comment]
Hey @dgobaud, just to confirm you're experiencing this on the alpha site at https://alpha.myetherwallet.com, correct? If you're using https://myetherwallet.com, you'll want to post this to https://github.com/kvhnuke/etherwallet.

**Comment by dgobaud** [comment]
its on live will repost thanks
