### ISSUE TITLE
token (deployed by other crowdsale) not showing up

### ISSUE THREAD

**Issue by SCBuergel** [MyEtherWallet/MyEtherWallet#926]
I have a crowdsale that creates a token. The crowdsale [shows up on Etherscan](https://rinkeby.etherscan.io/address/0xf45772f7f459209e398193c80c453807255361e0) and can also be used on MyEtherWallet. I read the token address which gets created by the crowdsale constructor via MEW but it is [not visible on Etherscan](https://rinkeby.etherscan.io/address/0xad819c06a0ee792a9f16cbc5b4acb33fc4a7e4b5) and does also not show any values when interfacing via MEW. I was quite sure that I did not make a mistake here, so I checked in my browser console using Metamask:
```
> function cb(e,r){console.log(e,r);}
> web3.eth.getCode('0xad819c06a0ee792a9f16cbc5b4acb33fc4a7e4b5', cb) // shows code so it worked!
```

also trying to read some properties works well:
```
> let tokn = web3.eth.contract(tokenAbi).at(tokenAddress)
> function cb(e,r){console.log(e,r);}
> tokn.owner(cb)
null "0xf45772f7f459209e398193c80c453807255361e0"

```
Is this a bug in MyEtherWallet and Etherscan?

(also posted on https://ethereum.stackexchange.com/questions/37530/token-deployed-by-other-crowdsale-not-showing-up-on-etherscan-or-myetherwallet)

**Comment by kangarang** [comment]
hi, may I ask how exactly you're getting the value `0xad819c06a0ee792a9f16cbc5b4acb33fc4a7e4b5`? it looks like that's an external address, not a smart contract address

take a look at the left column on your [txn history](https://rinkeby.etherscan.io/address/0x399ffebe53762f438fa6a629edf72bbfcceb6bc3) -- it seems two contracts were deployed (`0xf442b07c995...` and `0xf45772f7f45...`); however subsequent transactions did not successfully execute (hence, the ! on the original transaction `0x9c6a5b114cacf...`)

**Comment by SCBuergel** [comment]
[By now MEW does show the values from public storage vars at that address. I can e.g. read `symbol`, `owner` etc and the problem only remains on Etherscan.io where I dont see any code. Hence I close this issue.]

Thanks for looking into this.
>may I ask how exactly you're getting the value `0xad819c06a0ee792a9f16cbc5b4acb33fc4a7e4b5`?

Either via MEW or via web3 console: Use the contract address of the crowdsale `0xf45772F7f459209E398193C80C453807255361e0` and this snippet is all we need as abi:
```
[{"constant":true,"inputs":[],"name":"token","outputs":[{"name":"","type":"address"}],"payable":false,"stateMutability":"view","type":"function"}]
```
Then in MEW go on the "Contract" tab, paste address and ABI given above. Reading the only function `token` returns the token address `0xad819c06a0ee792a9f16cbc5b4acb33fc4a7e4b5`.

>it looks like that's an external address, not a smart contract address
That is exactly the problem. It seems as if this was an EOA for Etherscan (and earlier it was the same problem for MEW). However, when using web3 as stated in my post above then you do see code behind it and that code is also functional.
