### ISSUE TITLE
[Bug Report]In Mac OS, it maybe need some packages

### ISSUE THREAD

**Issue by rushairer** [MyEtherWallet/MyEtherWallet#927]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

- **Bug Report**
  When I run "npm run build:offline" in Mac OS, need some packages

 ``` shell
npm i --save-dev jpegtran-bin optipng-bin mozjpeg
```

**Comment by rushairer** [comment]
well

**Comment by gamalielhere** [comment]
@rushairer I apologize for the delay. Before running `npm run build:offline` do you run `npm install`?

**Comment by rushairer** [comment]
Sure, i did. @gamalielhere 

Thanks for helping.
