### ISSUE TITLE
Still need to copy most of v3 README.md into v4 README.md

### ISSUE THREAD

**Issue by jidanni** [MyEtherWallet/MyEtherWallet#933]
You still need to copy a lot of what is in
https://github.com/kvhnuke/etherwallet/blob/mercury/README.md
and paste it into
https://github.com/MyEtherWallet/MyEtherWallet/blob/develop/README.md
to make the latter a fully usable document.

**Comment by dternyak** [comment]
@jidanni We'll be sure to update the readme appropriately when we move to production release.

I'd love to have you help ensure that our documentation is up to par before we launch. In the meantime, I hope you're okay with me closing this issue due to being overly broad.

Thanks, 
Daniel

**Comment by jidanni** [comment]
OK. I guess
> You can create a wallet completely offline.
> ...
Is no longer possible in v4 anyway.

**Comment by dternyak** [comment]
@jidanni It is possible, and we'll be updating our documentation to better reflect how to do that as we move into a production release.

**Comment by dternyak** [comment]
@jidanni I'll make a note on your other PR to specifically address this. Thanks for bringing this to our attention 👍
