### ISSUE TITLE
Adding contracts to "select an item" list

### ISSUE THREAD

**Issue by ademenev** [MyEtherWallet/MyEtherWallet#943]
- **I'm submitting a ...**

  - [X] Feature request
  - [ ] Bug report

- **Feature Request**

After deploying a contract, it is available in "Select an item" list on "Interact with contract" screen. But for existing contracts, one has to fill in contract address and ABI every time. It would be very useful to have an option to save the address and ABI for future use

**Comment by gamalielhere** [comment]
@ademenev I'm not sure what you mean, interacting with contract page autofills the fields when selecting a contract to interact with.

**Comment by NefarioDr** [comment]
> @ademenev I'm not sure what you mean, interacting with contract page autofills the fields when selecting a contract to interact with.

If I can 'select a contract...' from the drop down list without copy&past contract address and ABI,  it will be really useful. But now, there are a few candidates in the list. How can I add my favorite contract address to the drop down list that I can select it without copy and past? Is there an option ? 
THX

**Comment by ademenev** [comment]
See comment above. I can’t explain better

ср, 17 апр. 2019 г. в 9:06, gamalielhere <notifications@github.com>:

**Comment by gamalielhere** [comment]
@NefarioDr you can add your contract at our [main list](https://github.com/MyEtherWallet/ethereum-lists/tree/master/src/contracts)

@ademenev I get what you're saying now. At most, we can store the contracts locally. It will be saved only in that computer.
