### ISSUE TITLE
NPM installation error for help,Thanks.

### ISSUE THREAD

**Issue by northeusunshine** [MyEtherWallet/MyEtherWallet#989]
Hi,
When I run "npm install" command, there are error messages as below,please help,thanks a lot!
===CONFIGURATIONS=========================
My OS is centos 7, and the software configurations are:
1 node v8.3.0
2 npm 6.9.0
3 GCC Version
Using built-in specs.
COLLECT_GCC=gcc
COLLECT_LTO_WRAPPER=/usr/libexec/gcc/x86_64-redhat-linux/4.8.5/lto-wrapper
Target: x86_64-redhat-linux
Configured with: ../configure --prefix=/usr --mandir=/usr/share/man --infodir=/usr/share/info --with-bugurl=http://bugzilla.redhat.com/bugzilla --enable-bootstrap --enable-shared --enable-threads=posix --enable-checking=release --with-system-zlib --enable-__cxa_atexit --disable-libunwind-exceptions --enable-gnu-unique-object --enable-linker-build-id --with-linker-hash-style=gnu --enable-languages=c,c++,objc,obj-c++,java,fortran,ada,go,lto --enable-plugin --enable-initfini-array --disable-libgcj --with-isl=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/isl-install --with-cloog=/builddir/build/BUILD/gcc-4.8.5-20150702/obj-x86_64-redhat-linux/cloog-install --enable-gnu-indirect-function --with-tune=generic --with-arch_32=x86-64 --build=x86_64-redhat-linux
Thread model: posix
gcc version 4.8.5 20150623 (Red Hat 4.8.5-36) (GCC)
===ERROR MESSAGE=========================
> bufferutil@4.0.1 install /root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/bufferutil
> node-gyp-build

make: Entering directory `/root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/bufferutil/build'
  CC(target) Release/obj.target/bufferutil/src/bufferutil.o
../src/bufferutil.c: In function ‘Init’:
../src/bufferutil.c:156:3: error: too many arguments to function ‘napi_create_function’
   status = napi_create_function(env, NULL, 0, Mask, NULL, &mask);
   ^
In file included from ../src/bufferutil.c:3:0:
/root/.node-gyp/8.3.0/include/node/node_api.h:148:25: note: declared here
 NAPI_EXTERN napi_status napi_create_function(napi_env env,
                         ^
../src/bufferutil.c:159:3: error: too many arguments to function ‘napi_create_function’
   status = napi_create_function(env, NULL, 0, Unmask, NULL, &unmask);
   ^
In file included from ../src/bufferutil.c:3:0:
/root/.node-gyp/8.3.0/include/node/node_api.h:148:25: note: declared here
 NAPI_EXTERN napi_status napi_create_function(napi_env env,
                         ^
../src/bufferutil.c: At top level:
../src/bufferutil.c:171:1: warning: initialization from incompatible pointer type [enabled by default]
 NAPI_MODULE(NODE_GYP_MODULE_NAME, Init)
 ^
../src/bufferutil.c:171:1: warning: (near initialization for ‘_module.nm_register_func’) [enabled by default]
make: *** [Release/obj.target/bufferutil/src/bufferutil.o] Error 1
make: Leaving directory `/root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/bufferutil/build'
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/root/downloads/MyEtherWallet/node_modules/node-gyp/lib/build.js:262:23)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-957.10.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/root/downloads/MyEtherWallet/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/bufferutil
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 

> wrtc@0.2.1 install /root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc
> node scripts/install.js

Searching for a pre-built wrtc binary
node-pre-gyp WARN Using request for node-pre-gyp https download 
[wrtc] Success: "/root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/wrtc/build/Release/wrtc.node" is installed via remote
Installed a pre-built wrtc binary

> yorkie@2.0.0 install /root/downloads/MyEtherWallet/node_modules/@myetherwallet/mewconnect-web-client/node_modules/yorkie
> node bin/install.js

setting up Git hooks
trying to install from sub 'node_module' directory, skipping Git hooks installation

> canvas@1.6.13 install /root/downloads/MyEtherWallet/node_modules/canvas
> node-gyp rebuild

Package cairo was not found in the pkg-config search path.
Perhaps you should add the directory containing `cairo.pc'
to the PKG_CONFIG_PATH environment variable
No package 'cairo' found
gyp: Call to './util/has_lib.sh freetype' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp ERR! configure error 
gyp ERR! stack Error: `gyp` failed with exit code: 1
gyp ERR! stack     at ChildProcess.onCpExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:345:16)
gyp ERR! stack     at emitTwo (events.js:125:13)
gyp ERR! stack     at ChildProcess.emit (events.js:213:7)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
gyp ERR! System Linux 3.10.0-957.10.1.el7.x86_64
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /root/downloads/MyEtherWallet/node_modules/canvas
gyp ERR! node -v v8.3.0
gyp ERR! node-gyp -v v3.8.0
gyp ERR! not ok 
npm WARN myetherwallet@5.0.10 No license field.
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.8 (node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.8: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@1.2.7 (node_modules/@myetherwallet/mewconnect-web-client/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.7: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.1 (node_modules/@myetherwallet/mewconnect-web-client/node_modules/bufferutil):
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: bufferutil@4.0.1 install: `node-gyp-build`
npm WARN optional SKIPPING OPTIONAL DEPENDENCY: Exit status 1

npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! canvas@1.6.13 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the canvas@1.6.13 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     /root/.npm/_logs/2019-04-24T07_21_46_128Z-debug.log

**Comment by 503945930** [comment]
https://stackoverflow.com/questions/22100213/package-cairo-was-not-found-in-the-pkg-config-search-path-node-j-s-install-canv

https://github.com/otrv4/pidgin-otrng/issues/104


you can try

**Comment by Loveless1445** [comment]
That is because your being protected. I just checked it out and  It
actually denied me access and told me that there is a bug inside of that so
basically that is the reason why
