### ISSUE TITLE
Trezor works with old version, doesn't work with old

### ISSUE THREAD

**Issue by KatyaMik** [MyEtherWallet/MyEtherWallet#999]
- **I'm submitting a ...**

  - [ ] Feature request
  - [x] Bug report

https://www.reddit.com/r/MyEtherWallet/comments/besjhb/new_mew_does_not_work_with_trezor_modelt_legacy/

When I click on the Trezor to confirm the Send operation, at the second time, when there is a prompt to press/hold, it just gets stuck there. I just see the green circle on the Trezor, and the MEW web page is frozen. It seems like the Trezor and MEW web app are not communicating.

As soon as I choose the MEW Legacy option, the problem goes away. This makes me think the cause is the new MEW web page.

**Comment by kvhnuke** [comment]
I believe this is solved now
